### ISSUE TITLE
ASCellNode sized incorrectly by ASTableView if delegate not set

### ISSUE THREAD

**Issue by isair** [facebook/AsyncDisplayKit#299] opened 2015-02-09 20:05 UTC
In my controller if I set my table view's delegate then the cells are sized correctly, if I remove that line then my cells get sized to the default row height of the table view for some reason. I implemented no functions from the table view delegate protocol in the controller.

**Comment by secretiverhyme** [comment] 2015-02-09 21:14
Thanks for the report!  This was fixed in #237, which will be included in the upcoming 1.2 release.

**Closed by secretiverhyme** 2015-02-09 21:14 UTC
Labels: bug, duplicate

**Comment by RuiAAPeres** [comment] 2015-10-03 01:01
@secretiverhyme I was able to reproduce this again with the current version (if delegate is not set, the cell's height will be 49.0f)

**Comment by nguyenhuy** [comment] 2015-10-03 17:43
Interesting. I suppose that you are using v1.2.3, right? It's hard for me to believe that such an old bug like this comes back, although it might be possible due to recent changes. Can you reproduce it in one of our examples, like Kitten example? What do your set up code and node(s) look like?

**Comment by RuiAAPeres** [comment] 2015-10-04 00:09
Hey, I am using carthage and I am pointing to this [commit](https://github.com/facebook/AsyncDisplayKit/commit/c8518c7fa6304f99db84b5480afce8f0b6ddb66e). I will check in one of the examples later.

**Comment by appleguy** [comment] 2015-10-04 00:22
@RuiAAPeres thanks for confirming the commit you're using — needless to say, that one should be pretty current and we wouldn't expect this issue to be occurring.  Please do open a new task with additional details as soon as you have a chance, as this is the only report I've seen of this for a long time.

**Comment by RuiAAPeres** [comment] 2015-10-04 01:13
Hey @appleguy you can find the testing project [here](https://dl.dropboxusercontent.com/u/14102938/TestDelegate.zip). It was build with the following:

* Xcode 7.0.1 (7A1001)
* Carthage 0.8.0
* Tested on simulator iPhone6s Plus with iOS 9.0

**Expected results:**

* Independently of line 21 (`self.tableView.asyncDelegate = self`) being commented or not, the cells will have a random size.

**Actual results:**

*  If it's commented, the cells height will use the default one (49points). If not, they will have a random size.
