### ISSUE TITLE
[ASCellNode] Implement support for dragging on a cell to reveal a multi-button menu.

### ISSUE THREAD

**Issue by alexrmacleod** [facebook/AsyncDisplayKit#1586] opened 2016-04-23 16:53 UTC
ASControlNode image works for a little bit until it doesn't. check out the image below, it's self explanatory.  

![img_6079 2](https://cloud.githubusercontent.com/assets/7895493/14762771/0eec15d4-09b6-11e6-8a72-0fc5f0ae679d.PNG)

I translated the SocialAppLayout example written in Objective c to swift. And this strange image bug seems to be happening in the swift version. Below is the project.

[SocialAppLayoutSwift.zip](https://github.com/facebook/AsyncDisplayKit/files/233068/SocialAppLayoutSwift.zip)

Add it to the -> https://github.com/facebook/AsyncDisplayKit/tree/master/examples for all the swift coders out there. once this bug is fixed that is. 

I noticed the SocialAppLayout uses ASControlNode for the buttons... why is that.... you guys built ASButtonNode? what are the benefits of using one over the other?

**Comment by hannahmbanana** [comment] 2016-04-24 07:00
@alexrmacleod: Good question! :) 

ASButtonNode was added after this example app was created. This example app needs some updating, including converting the ASControlNode you identified into an ASButtonNode. So you were correct in your intuition that it would be better as an ASButtonNode. 

As for the difference between ASButtonNode vs ASControlNode: ASButtonNode is a subclass of ASControlNode and adds different features like title text support, background/foreground images, different states, etc. Similar to how a UIButton extends a UIControl. 

Could you provide more information on how to reproduce this image bug? I ran your project in the simulator (thanks for including it!) but was not able to reproduce the issue with clicking, scrolling, etc. 

It may have to do with rasterization, which I see is toggled in the `didSelectRowAtIndexPath` method. Try commenting that out and see if it resolves the bug.

**Comment by alexrmacleod** [comment] 2016-04-24 11:30
@hannahmbanana thanks for the response, you were right... the lack of rasterization in the `didSelectRowAtIndexPath` was causing the issue with the background image on the `ASControlNode`. Below is what fixed the problem.

```
func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
    
    let postNode: PostNode = (tableNode.view.nodeForRowAtIndexPath(indexPath) as! PostNode)
    var post: Post = self.socialAppDataSource[indexPath.row] as! Post
    var shouldRasterize: Bool = postNode.shouldRasterizeDescendants
    shouldRasterize = !shouldRasterize
    postNode.shouldRasterizeDescendants = shouldRasterize
    
    tableNode.view.deselectRowAtIndexPath(indexPath, animated: false)
 }
```

However there is a new problem, when I select a cell, the "hairline" divider on the postNode disappears after the cellNode is de-selected. I think its a problem related to #1417 . Did you find a solution for this?

**Comment by hannahmbanana** [comment] 2016-04-24 19:30
@alexrmacleod: #1417 (rasterization) is still a known problem. 

For now, try removing the rasterization stuff completely. It was in the SocialAppLayout example mainly for developers of ASDK to test this special use feature. I think it should probably be removed. Most apps don't need it anywhere, but if you don't depend on background color it should still be useable. 

Are you on the ASDK slack? If you're interested in using this ASDK feature, it'd be good to get more info there. 

Rasterization flattens the whole node subtree into just a single view, which eliminates subviews and sublayers from being created. It's a valuable advanced performance optimization, but it will prevent you from independently animating anything in the subtree. In certain cases, if individual subnodes change (e.g. 3 network image nodes), it will have to reload each time.

**Comment by appleguy** [comment] 2016-04-24 22:54
@alexrmacleod, I agree with @hannahmbanana that we should actually remove the tap-to-rasterize hidden feature of SocialAppLayout - even in the ObjC version.

The known issue here is that some kinds of rasterized elements don't properly reflect their backgroundColor, if they were initially displayed non-rasterized and then rasterization is enabled (as occurs with the tap-to-rasterize).  Especially to toggle the rasterization state is an astoundingly rare thing to do in a real app, and I'd recommend avoiding rasterization until you become pretty familiar with the framework and even learn a few of the implementation details.  It has big side effects like losing touch handling for subnodes of that tree, but is extremely powerful as a carefully wielded performance tool.

**Comment by appleguy** [comment] 2016-04-24 22:55
Because the core issue here is almost certainly the same as #1417, or are closely related and would be resolved as part of the same change, I'm going to close this out. Please feel free to join us on slack to discuss any of your work, And you're also welcome to file more issues here.  Email me for a slack invite.

**Comment by alexrmacleod** [comment] 2016-04-27 06:35
Current situation, without tap-to-rasterize the image bug persists, with tap-to-rasterize the image bug is gone but the divider disappears. for now I removed the divider and used 
`self.tableNode.view.separatorStyle = UITableViewCellSeparatorStyle.SingleLine`

@hannahmbanana In the new sample project provided below as far as I can see there is no rasterizeation happening in this project but the image bug persists. 

To replicate the bug:
1: Launch app in simulator iphone 6s
2: in the navigation bar tap the "following" segment in the segment control
3: tap the first cell in the tableview cell (should highlight then de-select)
4: tap the like button and the image bug should occur. 

I am trying to achieve a tableviewcell effect like on the Twitter ios app. When you tap a cell on the twitter tableview it highlights and pushes to a new controller, then when you swipe back the highlighted state slowly fades out. Is this possible with ASTableView? or should I build this app using a regular UItableViewController where this effect happens by default and use AsyncDisplayKit to build the view components inside a UITableViewCell.  

Basically I have been plagued with poor performance (using the typical storyboard and autolayout) and want to build a tableviewcontroller thats has 60fps scrolling. 

Also inside the likeNode.swift file on line 87 I added the following. 
`self.postNode!.passthroughNonlinkTouches = true`
It seems that its not working. shouldn't the github url in the bottom cell of the followingTableViewController be tappable? or am I wrong?

@hannahmbanana Finally I know this is a little off topic but how do you make something like [MGSwipeTableCell](https://github.com/MortimerGoro/MGSwipeTableCell) work on ASTableNode? how would I go about making that a reality? now at the end of the post it seems using the regular UITableViewController + MGSwipeTableCell + AsyncDisplayKit for building the views/buttons inside a custom UITableViewCell is the best way to move forward. Please advise... 

@appleguy I emailed AsyncDisplayKit@gmail.com for a slack invite. did you receive? 
[StockChat.zip](https://github.com/facebook/AsyncDisplayKit/files/238020/StockChat.zip)

**Comment by hannahmbanana** [comment] 2016-04-27 09:02
@alexrmacleod: Thanks for the update with sample project and replication steps! I will check it out tomorrow. I believe I sent you an invite 9 days ago (check your email for a Slack invite email from me, hannah). If not, email AsyncDisplayKit@gmail.com and I send you another invite.

**Comment by hannahmbanana** [comment] 2016-04-27 09:04
@alexrmacleod: Your email ended up in the spam folder. Good thing you alerted me to this, because there were a bunch of other requests in there as well!

**Comment by appleguy** [comment] 2016-04-28 06:13
@alexrmacleod we're committed to helping you figure this out.  Reopening.  If the only issue is the separator, you should try out just adding a simple ASDisplayNode with .backgroundColor set.  Make sure rasterization is off as it is exactly this case that doesn't work reliably with rasterization in the current framework version.

**Comment by hannahmbanana** [comment] 2016-04-28 06:22
@alexrmacleod: Regarding the MGSwipeTableCell. It is definitely not possible to use a UITableViewCell subclass directly, but it is possible to wrap any other type of UIView (for example UIButton, UIImageView, colored square UIViews, etc) and put them inside node hierarchies.

There are 2 ways to do this, and whether it is possible to reuse the code from the MGSwipeTableCell at all is unclear, but it probably would be best done with the first approach below:

1. Use the didLoad method in your ASCellNode subclass, which is called on the main thread and is the earliest opportunity to access the self.view of the node. Here, you can add any number of regular UIViews as subviews, even a deep hierarchy of multiple levels of views. Views that are manually added in this way cannot be positioned using a layoutSpec, so you must either set autolayout constraints on them, or preferentially use the -layout method in exactly the same way as you might use -layoutSubviews when writing a view subclass. 

2. Using a node to wrap custom views. The advantage of this approach is primarily for when it is useful to assemble the full hierarchy of elements off the main thread, such as when you need these elements to participate in the asynchronous layout pass (using layoutSpecThatFits:)

        [[ASDisplayNode alloc] initWithViewBlock:^UIView *{
             return [[BEMCheckBox alloc] init];
        }];

**Comment by hannahmbanana** [comment] 2016-04-28 07:09
@alexrmacleod: Thanks for the sample project & replication steps! I am now able to reproduce the image bug. 

Following @appleguy's advice, I set a breakpoint in `ASImageNode`'s `displayWithParameters:` method and checked the `.isOpaque` parameter. It was set to YES. If opaque is set YES and the image is clear or has no color behind it, UIKit will use black by default. 

This might be an issue with the your image file. It could also be that somewhere in your app you are setting opaque. 

A quick hack that should work would be to set the background color of the node that represents the heart to be white (i.e. match the table background color).

I try this out really quickly and see if it works.

**Comment by hannahmbanana** [comment] 2016-04-28 07:38
@alexrmacleod: (rest of answers copied from our github convo)

This property - .passthroughNonlinkTouches - has nothing to do with handling the link tap. All it does is pass through touch events that do NOT land on a link to any views that may be beneath the text node. perhaps the only common use for this is to allow table cells to be selected when tapping a text node that has a link in it

RE:  ASTableView twitter effect - this is possible. As long as the selected state of the cell looks as you intend, it will not fade out until you call `deselectRowAtIndexPath:` This means, instead of triggering the deselection at the moment that the delegate call for the cell being selected is triggered, instead call that method in the `viewControllerViewWillAppear` or ViewDidAppear depending on how long you want the selection state to linger. This is a standard effect (much less common since iOS7, but in iOS6 and earlier this was recommended by apple as best practice to reinforce to the user which cell they had just returned from the detail controller of. If this doesn’t work for you, you may not be selecting the row as you intend, so set a breakpoint in the didSelectRow.. just to make sure it’s being called. When you move deselctRowAtIndexPath: to viewControllerViewWillAppear, you will need to use the method selectedIndexPaths (or something like that - can’t remember the name off the top of my head) since the indexPath won’t be available

**Comment by alexrmacleod** [comment] 2016-04-30 11:31
I find that using `self.iconNode!.backgroundColor = UIColor.clearColor()` would make things a little easier if your cells have a custom background colour.

Question 1:
Re: MGSwipeTableCell - option 2 means it is possible to take something like **BEMCheckBox** and wrap it in a **ASDisplayNode** however because **MGSwipeTableCell** is a subclass of **UITableViewCell** and I'm currently using **ASTableNode** which only works with **ASCellNode** there really isn't a quick fix for this and would probably be much more work than its worth?

Example:
What I am aiming for is the below image of a Cell from another app. Which has something like MGSwipeTableCell going on as well. 

![fullsizerender 23](https://cloud.githubusercontent.com/assets/7895493/14935550/5fd2e516-0f08-11e6-900f-733db5f655ed.jpg)

What I currently have. 

![fullsizerender 24](https://cloud.githubusercontent.com/assets/7895493/14935552/818fc62e-0f08-11e6-8704-9ef62aa24c30.jpg)

Eventually I will put the mini line chart in the middle of each cell and was worried that if I do that it could cause a regular UITableViewCell to drop lots of FPS when scrolling.  

Question 2:
So if am I to use MGSwipeTableCell. I should just use the regular **UITableViewController**, build the cells programatically using **UIStackView** and, try to keep the cells as simple as possible by avoiding storyboard, interface builder and autoLayout? and perhaps i'll be able to add the lineChart down the road and it won't effect performance too much? 

Thanks for the twitter effect explanation. Nice actionable advice.

**Comment by appleguy** [comment] 2016-05-01 07:16
@alexrmacleod haha, having seen those (very cleanly designed) screenshots, I'm definitely really engaged with helping you figure this out.  However, I think the best way is to simply rebuild the swiping functionality, and we could put it in ASCellNode itself.

The one problem is that I have a significant time crunch in the next few days.  I'm wondering if you would be able to send over the code, dropped into a Cmd-D duplicate of any project in Examples / (you can just rename the folder, and delete any code not necessary to get up and running one ASCellNode in a similar environment to your app where we could test dragging to reveal the menu).

If this sounds OK, you could cut out any data model and any other part of the app, just hardcoding some string values.  If you feel motivated, it would be better to have it as a table with 100-200 items, maybe repeating ~10 stock infos of varying lengths, character sets, etc.  Then I could profile it and make sure scrolling is optimized.

Then, it'd be up to you, but this would actually make a sweet app for examples/ .  Or I can keep the code completely confidential and delete it after our work.

Make sure to ping @maicki, @hannahmbanana and myself for any questions on Slack.  I don't think there's a great route to use MGSwipeTableCell and make very direct use of ASDK though.

**Comment by alexrmacleod** [comment] 2016-05-01 15:27
**Do you have a video of interacting with a few examples of this component, maybe with 1, 2, 3 items etc?**

@appleguy, @maicki, @hannahmbanana I don’t have a video but I made a gif below. Take note of how when the buttons are exposed on one TableViewCell, you can swipe another TableViewCell and the original TableViewCell with the buttons exposed closes automatically. The same goes for vertical swiping on the UITableView. If there is a button exposed on a swiped TableViewCell the user can still interact with the UITableView by swiping vertically, and the swiped TableViewCell closes automagically.    

![ascellnode and beyond](https://cloud.githubusercontent.com/assets/7895493/14941787/26bfa254-0fdb-11e6-8bac-fe1312368366.gif)

Also in this [link](https://github.com/MortimerGoro/MGSwipeTableCell) there are more gifs showing what the swipe gestures could look like. I really like the Border transition, Static transition and Drag transition.

**(you can just do Cmd-D on any folder in examples, rename the folder, and delete any code not necessary to get up and running one ASCellNode in a similar environment to your app where we could test dragging to reveal the menu).**

Will this do? 
[Swift.zip](https://github.com/facebook/AsyncDisplayKit/files/244185/Swift.zip)

**Then, it'd be up to you, but this would actually make a sweet app for examples/ . Or I can keep the code completely confidential and delete it after our work.**

Lets make a sample app, if you can get this working the AsyncDisplayKit community is going to need a sample to play around with. Willing to help where I can.

I watched your asyncDisplayKit talks on youtube and remembered you saying you built the apple stock app. One of my favourite apps and hands down the best stock charts i’ve seen in iOS, simple, fast and easy on the eyes! 🙌

**Comment by maicki** [comment] 2016-05-18 13:32
@appleguy @hannahmbanana @alexrmacleod Hi all, after reading through this whole issue it seems like there are multiple conversations / issues are going on. Just top out of my head is the background color problem in the image nodes, the request for a cell swipe component, updating the sample in Swift ... can you please take a couple of minutes and create new issues for each of them, link to this issue and close this issue? Thanks!

**Comment by codeOfRobin** [comment] 2016-12-11 20:57
@alexrmacleod Were you able to get a swipe action working?

**Comment by garrettmoon** [comment] 2017-02-09 19:49
I'm going to close this for now. We're trying to move community debugging over to [slack](http://asdk-slack-auto-invite.herokuapp.com/). As @maicki mentioned it looks like this is becoming multiple issues. If there are still bugs, please report them in new issues. Thank you all for your input!

**Closed by garrettmoon** 2017-02-09 19:49 UTC
Labels: API improvement, Enhancement
