### ISSUE TITLE
ASDK v2  - ASDisplayNode, ASStackLayoutSpec and style.height

### ISSUE THREAD

**Issue by stephenkopylov** [facebook/AsyncDisplayKit#2787] opened 2016-12-16 10:22 UTC
Hi, guys, thanks for v2.0 release! After only a day of refactoring I eliminated all deprecated methods in my project =D

But it looks like I've found another small problem.
I will try to explain it.

So, I have two display nodes with fixed sizes (200x200). They are vertically stacked in stack spec (ASStackLayoutSpec), placed in the center of the screen by ASRelativeLayoutSpec.
But, I need to add a separator with fixed height between them. And here starts a problem.

ASDisplayNode, as separator, with "style.height = 10.f" are pushing the stack to the 100% width of supernode.
At the same time, ASButtonNode works perfectly.

The problem appears only in v2.0 and in previous versions all was fine (with flexBasis).

Screenshot:
![screen-shot-2016-12-16-at-12 06 19](https://cloud.githubusercontent.com/assets/5202281/21259319/848332b8-c389-11e6-9794-a25258387d16.jpg)

Sample:
https://github.com/stephenkopylov/ASDKLimitedHeightProblem

**Comment by nguyenhuy** [comment] 2016-12-16 11:54
Very interesting question. Thank you for asking!

The difference you are seeing is caused by the fact that ASButtonNode and ASDisplayNode size themselves differently. 

ASButtonNode internally uses [a stack spec](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASButtonNode.mm#L480). And because the separator button has neither an image nor a title set to it, its stack spec is empty  and has no intrinsic size. When your outer vertical spec asks it to calculate a layout, it first returns a size of (0.f, 10.f). Then the vertical spec asks it to stretch to match the width of other buttons. So it ends up having a width of 200.f as you would expect.

On the other hand, the default behaviour of ASDisplayNode is [to use the maximum size passed to it as its size](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L2691). And the maximum width in this case is the screen width.

Assuming you want your separator to have a view with a background color, I'd like to suggest the following setup. The most important difference in my setup is that I restrict the width of the vertical stack to 200.f, and then I use a ratio spec on each of the button nodes to make sure they are square. This way, you can easily change the width of the whole stack to another value, either at compile time or runtime.

```objective-c
- (instancetype)init
{
    self = [super initWithNode:[ASDisplayNode new]];
    
    if ( self ) {
        self.node.backgroundColor = [UIColor whiteColor];
        
        self.firstNode = [ASDisplayNode new];
        self.firstNode.backgroundColor = [UIColor lightGrayColor];
        [self.node addSubnode:self.firstNode];
        
        self.separatorNode = [ASDisplayNode new];
        self.separatorNode.style.height = ASDimensionMakeWithPoints(10.f);
        self.separatorNode.backgroundColor = [UIColor redColor];
        [self.node addSubnode:self.separatorNode];
        
        self.secondNode = [ASDisplayNode new];
        self.secondNode.backgroundColor = [UIColor darkGrayColor];
        [self.node addSubnode:self.secondNode];
        
        __weak typeof(self)weakSelf = self;
        
        self.node.layoutSpecBlock = ^ASLayoutSpec *(ASDisplayNode *_Nonnull node, ASSizeRange constrainedSize) {
            __strong typeof(self)strongSelf = weakSelf;
          
            ASRatioLayoutSpec *firstReatioSpec = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:1 child:strongSelf.firstNode];
            ASRatioLayoutSpec *secondReatioSpec = [ASRatioLayoutSpec ratioLayoutSpecWithRatio:1 child:strongSelf.secondNode];
          
            ASStackLayoutSpec *stackSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical spacing:0.f justifyContent:ASStackLayoutJustifyContentCenter alignItems:ASStackLayoutAlignItemsStretch children:@[firstReatioSpec, strongSelf.separatorNode, secondReatioSpec]];
            stackSpec.style.width = ASDimensionMake(200.f);
          
            ASRelativeLayoutSpec *relativeSpec = [ASRelativeLayoutSpec relativePositionLayoutSpecWithHorizontalPosition:ASRelativeLayoutSpecPositionCenter verticalPosition:ASRelativeLayoutSpecPositionCenter sizingOption:ASRelativeLayoutSpecSizingOptionMinimumSize child:stackSpec];
            
            return relativeSpec;
        };
    }
    
    return self;
}
```

**Comment by stephenkopylov** [comment] 2016-12-16 12:25
Thank you, @nguyenhuy 

The strange thing is the fact that in previous version of ASDK it have worked as I expected. Nothing about it found in release and migration notes. Now it just works with other logic. =(

>And the maximum width in this case is the screen width.
But, in my case maximum width is the stackSpec's width. And, because stackSpec can not stretch this two elements with fixed sizes, its maximum width limited by maximum width of its elements. Isn't it right?
It was so in ASDK 1.9.x but not in v2 =(

**Comment by nguyenhuy** [comment] 2016-12-16 14:13
@stephenkopylov I think you are right that there has been a behavior change here. For 1.9.x, vanilla ASDisplayNode layout code would return the bigger value among `_preferredFrameSize` (which is zero by default) and `constrainedSize.*min*` ([code in 1.9.2](https://github.com/facebook/AsyncDisplayKit/blob/e344f03608887d150607b854dc0fe5efad6580ec/AsyncDisplayKit/ASDisplayNode.mm#L2070)). While on 2.0, since we deprecate `preferredFrameSize` and actually don't have an ivar for it, [`constrainedSize.max` is returned](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASDisplayNode.mm#L2691). Sorry we missed this hard-to-detect behavior change. We need to update the change log and/or migration guide. cc @hannahmbanana @maicki .

> But, in my case maximum width is the stackSpec's width. And, because stackSpec can not stretch this two elements with fixed sizes, its maximum width limited by maximum width of its elements. Isn't it right?
Yes, that is right ([code here](https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/Private/ASStackUnpositionedLayout.mm)). But in this case the separator is the longest element because of the above new behavior, bigger than the width of the 2 buttons. The stack actually asks those buttons to stretch, to which they refuse because they have a fixed size . Does that makes sense?

**Comment by stephenkopylov** [comment] 2016-12-16 14:26
@nguyenhuy
Understood, thank you. =)
I already have rewrote the similar parts of my code with the new logic.
As I think, the main question is - what is more logical and reasonable behavior? Which behaviour will be expectable by new users - the new, or the old?

**Comment by hannahmbanana** [comment] 2017-02-09 21:54
Huy - could you make an call on what should happen with this issue?

**Comment by nguyenhuy** [comment] 2017-03-10 17:17
@stephenkopylov Sorry for this late response. I think either behavior is fine. I'm gonna close this issue. Let us know on [Slack](asyncdisplaykit.org/slack) if you have any questions!

**Closed by nguyenhuy** 2017-03-10 17:17 UTC
Labels: Needs Triage
