### ISSUE TITLE
[Supplementary Nodes] Implementation specifics for subclasses of FlowLayout

### ISSUE THREAD

**Issue by ChrisSchneider** [facebook/AsyncDisplayKit#866] opened 2015-11-19 14:54 UTC
When the UICollectionViewLayout changes the size supplementary views (using collectionView:layout:referenceSizeForFooterInSection:), the UICollectionReusableView is positioned correctly, but the ASCellNode is not relayouted (calculateSizeThatFits: or layout: are not called)

**Comment by levi** [comment] 2015-11-19 16:56
That doesn't sound like expected behavior. @ChrisScheider can you post some of your code so I can see how you're interfacing with the supplementary API? I'd be more than happy to help you get this working asap.

**Comment by ChrisSchneider** [comment] 2015-11-20 09:36
Thank you for your response & help.

I'm using a subclass of UICollectionViewFlowLayout, which basically changes the section footer's frame and overrides shouldInvalidateLayoutForBoundsChange to return false.

In my ViewController I use collectionView:layout:referenceSizeForFooterInSection to either return CGSizeZero to hide or CGSize(width: 40, height: 40) to show the footer.

The footer is a subclass of ASCellNode which always returns a cell.





    public override func layoutAttributesForElementsInRect(rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        ...
        if footerFrame.intersects(rect) {
            let indexPath = NSIndexPath(forItem: 0, inSection: 0)
            if let attributes = layoutAttributesForSupplementaryViewOfKind(UICollectionElementKindSectionFooter, atIndexPath: indexPath) {
                layouts.append(attributes)
            }
        }
        return layouts
    }

    public override func layoutAttributesForSupplementaryViewOfKind(elementKind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionViewLayoutAttributes? {
        let attributes = super.layoutAttributesForSupplementaryViewOfKind(elementKind, atIndexPath: indexPath)
        if elementKind == UICollectionElementKindSectionFooter {
            if let attributes = attributes?.copy() as? UICollectionViewLayoutAttributes {
                attributes.frame = footerFrame
                return attributes
            }
        }
        return attributes  
    }


    func collectionView(_: ASCollectionView!, layout _: UICollectionViewLayout!, referenceSizeForFooterInSection _: Int) -> CGSize {
      return (isRefreshing) ? CGSize(width: 40, height: 40) ? CGSizeZero
}


    func collectionView(collectionView: ASCollectionView!, nodeForSupplementaryElementOfKind kind: String!, atIndexPath indexPath: NSIndexPath!) -> ASCellNode! {
        let node = ASCellNode()
        node.backgroundColor = UIColor.redColor()
        return node
    }

**Comment by appleguy** [comment] 2015-11-29 02:09
@ChrisSchneider By subclassing, I'm fairly confident this means you need to implement the ...LayoutInspecting API.  I didn't study your code snippet in detail, but can you confirm that you've looked at LayoutInspecting and are fairly confident you've implemented it?

This isn't required for the base FlowLayout class, but it is required for all other layouts to use supplementary nodes.

**Comment by levi** [comment] 2015-11-30 15:10
OK, I have a good understanding why this isn't behaving as your expect. Collection view layouts call `invalidateLayout` on themselves whenever you're performing the bounds change. ASCollectionView is currently not responding to this relayout event, as it's currently setup to only relayout elements in two scenarios: 1) When reloadData is called 2) when layoutSubviews is called. The latter scenario performs a similar behavior as to what you're expecting, calling `[_dataController relayoutAllNodes]` to remeasure and position the nodes from within their respective cells.

The fact that ASCollectionView ignores `invalidateLayout` events is something I've noticed in the past and would like to fix in the coming months. You can follow along in issue #691. In the meantime, I might suggest overriding `invalidateLayout` in your subclass and exposing the `dataController` attribute on ASCollectionView locally. This will give you the ability to call `[self.collectionView.dataController relayoutAllNodes]` from within you collection view layout and ensure that the nodes are measured on the main thread on bounds change.

**Comment by appleguy** [comment] 2016-06-06 05:48
@ChrisSchneider - thanks for contributing to the AsyncDisplayKit community by asking this question. I'm going to close this issue since it's now a duplicate of #691. If you are still having troubles, feel free to reopen this issue or ping us on the ASDK Slack channel (#1582).

**Closed by appleguy** 2016-06-06 05:48 UTC
Labels: community debugging
