### ISSUE TITLE
[ADK 1.2] ASBasicImageDownloaderContext calls completionBlock only for the last request

### ISSUE THREAD

**Issue by mvasiliniuc** [facebook/AsyncDisplayKit#465] opened 2015-05-23 19:45 UTC
This is the simplified scenario:
In a ASTableView, all ASCellNodes contain a ASNetworkImageNode.
All cells/nodes receive the same image URL to display so all ASNetworkImageNodes will simultaneous  try to download the content of the same URL.

Problem: Only the last cell that requested the download will actually receive it and all other ASNetworkImageNodes will remain empty (without an image).

Associated issues:
- ASNetworkImageNodeDelegate methods are NOT called for the 'problematic' ASNetworkImageNodes.
- ASNetworkImageNodeDelegate methods are called multiple times for the ASNetworkImageNode that receives the image.

I suspect this started happening after ASBasicImageDownloader switched from a dedicated ASBasicImageDownloaderMetadata for each received URL, to a ASBasicImageDownloaderContext which handles all identical requests (same URL). (You can find this in the downloadImageWithURL implementation of the ASBasicImageDownloader).
For all the downloadImageWithURL calls (requests) with the same URL, we end up with only one retained completion block (the last one). The NSURLSessionDownloadDelegate implementations will end up calling this completion block for each request made for that specific URL.

Is this a desired behaviour?

Thanks!

**Comment by markmark1** [comment] 2015-06-07 11:27
I see this behavior too it's not desirable and needs to be fixed

**Comment by appleguy** [comment] 2015-06-07 23:56
@mvasiliniuc, thanks for the detailed report — it really helps.  @markmark1 I also appreciate your confirmation, and apologize for the trouble.

I believe @rnystrom was the most recent committer to this code, and I'm not currently familiar with the implementation here.  If Ryan is unable to, I'll prioritize investigating this.

**Comment by appleguy** [comment] 2015-06-08 01:33
I was able to reproduce the issue.  Sorry all, this is indeed a shitty bug.  We didn't catch it because it's a less common case for the same URL to be downloaded by multiple image nodes, and the basic downloader included with ASDK is one a handful of parts of the framework that are not battle-tested at scale in Facebook apps (since the Facebook network library is large and very custom, we had to write a new one to OSS ASDK).

We'll fix this very soon and I'll probably roll a 1.2.1 primarily for this issue.

**Comment by markmark1** [comment] 2015-06-08 02:08
Thanks a lot apple guy can't wait to use async displaykiT

**Comment by appleguy** [comment] 2015-06-08 15:43
I have the bug cornered and will upload a fix in the next day or two.  Thanks again for the report, and your patience as we refine these components for the community :)

**Comment by markmark1** [comment] 2015-06-08 15:48
You rock apple guy can't wait to test fix thanks

**Comment by markmark1** [comment] 2015-06-08 18:04
What is metal and how does it fit into either pop or ck or asyncdisplaykit
http://stackoverflow.com/questions/24046125/compiling-and-running-the-metal-examples

Any thoughts ideas appreciated

**Comment by appleguy** [comment] 2015-06-10 23:53
Fix merged to master--please test it out and let us know how it goes.  I will aim to release a 1.2.1 this weekend.

**Comment by tiepvuvan** [comment] 2015-06-11 01:46
Just pulled commit for fix this problem, but ASNetworkImageNode crash right away when set URL.

**Comment by markmark1** [comment] 2015-06-11 01:50
How to test it integrate git head or pods latest ?

**Comment by tiepvuvan** [comment] 2015-06-11 01:52
@markmark1: just add :head to your pod
Eg: pod 'AsyncDisplayKit', :head

Then run 'pod install' again.

**Comment by appleguy** [comment] 2015-06-14 05:57
@tiepvuvan @markmark1 check out the PR merged today.  Should be fixed.  Unfortunately the original fix did contain a crash, which I found right after merging it, but decided not to revert so the author could fix (which he did promptly, and then took me a couple days to merge -- sorry!)  I am 99% confident we're ready to close this out, but will leave it open until I hear some successes :+1:

**Comment by tiepvuvan** [comment] 2015-06-15 08:50
@appleguy: I've pulled the latest code and it's working perfectly :) thank you guys

**Comment by markmark1** [comment] 2015-06-15 13:56
I'll check it today too guessing it will work appleguy

**Comment by mvasiliniuc** [comment] 2015-07-12 17:23
Finally got the chance to test the latest ADK versions and the fix implicitly. It works fine. Sorry for the late validation. Thanks a lot for the quick response and support!

**Comment by appleguy** [comment] 2015-11-01 19:13
Glad this worked out.  I think ASNetworkImageNode is finally in good shape; there was a retain cycle in some cases that is now resolved as well, so we're back to a no-known-bugs state.

**Closed by appleguy** 2015-11-01 19:13 UTC
Labels: bug
