### ISSUE TITLE
[ASTableView] 'selectRowAtIndexPath' should be added to the editingTransactionQueue, performed after pending cell additions are done.

### ISSUE THREAD

**Issue by ImJCabus** [facebook/AsyncDisplayKit#1499] opened 2016-04-09 21:52 UTC
#627 shows a screenshot of my exact problem (same code location, same EXC_BAD_ACCESS).
However, it was closed without ever being answered -.-

I noticed that the crash happens when calling selectRow pretty 'early' in the tableview's lifecycle. E.g. in viewDidLoad() of an enclosing viewController.

When I delay the invocation of selectRow for a few second (2 - 4), the crash does not happen.

**Comment by appleguy** [comment] 2016-04-09 22:54
@ImJCabus can you provide some logs from what the exception prints out? Can you provide a screen shot of your exact reproduction case?

What actions do you perform to trigger the crash? Does it occur at the same moment every time or is there an element of randomness? Have you tried reproducing it in a smaller application, such as any one of the example applications provided with repository?

**Comment by ImJCabus** [comment] 2016-04-09 23:26
I'm running ASDK version 1.9.7

![screen shot 2016-04-10 at 01 16 18](https://cloud.githubusercontent.com/assets/6830248/14407032/e5036c78-feba-11e5-969b-d3ecbb89448e.png)

As you can see the crash the location is the same as in #627.

![screen shot 2016-04-10 at 01 21 22](https://cloud.githubusercontent.com/assets/6830248/14407031/e4e098ce-feba-11e5-8814-3b559a05d0aa.png)

Here is the beginning of the call stack.
The tableView is added to self.view in loadView()

**Comment by ImJCabus** [comment] 2016-04-10 00:03
<img width="840" alt="screen shot 2016-04-10 at 02 02 23" src="https://cloud.githubusercontent.com/assets/6830248/14407199/4bdeda40-fec0-11e5-8c71-b84e42acef84.png">

Adding a call to `reloadDataImmediately` before `selectRow` resolves the issue...
Any ideas? Is this normal behaviour?

**Comment by appleguy** [comment] 2016-04-10 02:31
@ImJCabus aha, yes it is - perhaps unfortunately.  You should use reloadDataWithCompletion: to avoid blocking the main thread, though.

As the name implies, data loading and layout is asynchronous.  So you could be selecting a row that does not actually exist at the moment.  This is an issue I will leave open because we can pretty easily integrate this API so it puts the select operation on the "editing transaction queue", so that it is automatically performed after operations queued to that point have been run.

You should install 1.9.7.1 though, some real worthwhile improvements there!

**Comment by ImJCabus** [comment] 2016-04-10 09:43
@appleguy ah I see.
Sometimes, the asynchrony still catches me :)
I would be nice, if the framework handled this behind the scenes transparently.
The behaviour would resemble UIKit and I guess I'm not the only one who stumbled over this gotcha :)

Thanks for making it clear to me though!

**Comment by appleguy** [comment] 2016-06-06 05:43
The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send us an email at AsyncDisplayKit@gmail.com or ping us on ASDK's Slack (#1582). If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Closed by appleguy** 2016-06-06 05:43 UTC
Labels: API improvement, ASTableView, Move to Ship
