### ISSUE TITLE
[ASTextNode] Highlighting layer clips to the bounds of the layer that allows highlight drawing

### ISSUE THREAD

**Issue by ide** [facebook/AsyncDisplayKit#263] opened 2015-01-26 23:39 UTC
I have an ASTextNode that allows highlighting (`node.layer.as_allowsHighlightDrawing = YES`) but the highlight overlay layer is clipped and does not show rounded rects. I believe this is because the frame of the layer is set to the bounds of the text node, and CALayers can't draw outside of their bounds.

In this case I would say the fix is to set `overlayLayer.frame = UIEdgeInsetsOutsetRect(overlayLayer.padding, highlightTargetLayer.bounds)`, where UIEdgeInsetsOutsetRect uses the given insets to expand a rect. This way the highlight overlay layer will always have enough room for its padding.

Maybe the current behavior is intentional? But I find it counterintuitive and my current workaround is to set the `as_allowsHighlightDrawing` on the root node and use `clipsToBounds` if I have subnodes that shouldn't let the highlight overlay bleed out of them (on a related note I'd like to specify the padding of the highlighting). Also I think this approach maybe paves the way for removing `as_allowsHighlightDrawing` -- would be nice if it were automatic.

**Comment by kylehickinson** [comment] 2015-01-27 00:01
Hey @ide, I actually brought this up a while back (#79), based on the discussion, it is intended behaviour to preserve proper text layout of the `ASTextNode` itself.

**Comment by secretiverhyme** [comment] 2015-01-27 00:02
Hah, @kylehickinson beat me to it.  Yes, this is intentional — this API is rather nonintuitive though, and could stand to be improved.

**Comment by ide** [comment] 2015-01-27 00:05
Thanks for the context @kylehickinson. One thing that's different about what I'm proposing - if I'm reading the previous discussion correctly - is to outset the highlight layer instead of insetting the text node. This preserves the text layout, which could open the door for making the highlight layer automatic (since it doesn't affect layout)

**Comment by appleguy** [comment] 2016-03-25 19:01
The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Closed by appleguy** 2016-03-25 19:01 UTC
Labels: ASTextNode, documentation
