### ISSUE TITLE
[Swift] Specifically for Archive builds, #import <AsyncDisplayKit/AsyncDisplayKit.h> 'file not found'

### ISSUE THREAD

**Issue by ProjectDent** [facebook/AsyncDisplayKit#431] opened 2015-04-18 02:10 UTC
I followed the instructions to manually integrate AsyncDisplayKit with my app. It builds and runs fine, but when I go to Archive, it points me to my bridging header file, the line `#import <AsyncDisplayKit/AsyncDisplayKit.h>`, giving me the error `'<AsyncDisplayKit/AsyncDisplayKit.h>' file not found`.

Under Framework Header Paths, I've now added the AsyncDisplayKit folder, but this hasn't solved the problem. I'm not sure what the problem is or what I can do about it.

**Comment by ProjectDent** [comment] 2015-04-19 11:43
Confirmed by trying this with a test project.

**Comment by ProjectDent** [comment] 2015-04-19 13:50
I detailed this issue here:

http://stackoverflow.com/questions/29730394/failed-to-import-bridging-header-file-not-found-when-archiving-my-project

**Comment by habitatus** [comment] 2015-05-14 20:19
@ProjectDent I'm having the same issue. Did you ever resolve it?

**Comment by ProjectDent** [comment] 2015-05-15 16:13
@habitatus I removed the project files, and just imported all AsyncDisplayKit files into my project manually.

**Comment by habitatus** [comment] 2015-05-15 19:48
@ProjectDent That seems reasonable. Changing the #import <header> to #import "header" throughout the ASDK did the trick for me.
Thank you!

**Comment by appleguy** [comment] 2015-05-18 02:15
@ProjectDent thanks for reporting this.  Could you test out locally applying this PR to see if it resolves this particular issue with the #import syntax you had previously?  #449 

Alternatively, if you can upload a sample project, I'll test it out and make sure this works properly.

**Comment by kusmi** [comment] 2015-07-16 14:58
I'm using 1.2.2 and still see this issue. I'm not using Pods, but import the AsyncDisplayKit directly as written in AsyncDisplayKit documentation.

**Comment by klivin** [comment] 2016-04-06 23:07
Has there been any progress with this issue as this still exists, and makes for supporting iOS 7.1 impossible as Carthage solution is iOS 8 and later (similar to the cocoapods framework support)

**Comment by appleguy** [comment] 2016-04-08 07:17
@klivin are you sure it is not an issue such as the one described on this page under "archiving works a little differently?"

http://stackoverflow.com/questions/5543854/xcode-4-cant-locate-public-header-files-from-static-library-dependency

I have not seen any other reports of this, but if you can provide more concrete details such as a simple test project that reproduces the issue, we can certainly fix it. Without a way to reproduce, we have no way to test the fix.

**Comment by appleguy** [comment] 2016-04-08 07:18
@klivin what version are you building against currently?

**Comment by hannahmbanana** [comment] 2016-04-27 06:46
@klivin: were you able to resolve the archiving issue? If so, can you share what worked?

**Comment by Adlai-Holler** [comment] 2016-05-17 17:50
@ProjectDent #1663 suggests that this issue would be fixed by CocoaPods 1.0.0. Could you try completely wiping Podfile.lock plus the pods integration, ensuring that version's installed, and archiving?

**Comment by appleguy** [comment] 2016-06-06 02:36
@ProjectDent - thanks for contributing to the AsyncDisplayKit community by asking your question here! Due to the length of time it's been since this thread was active, I'm going to mark this issue as closed. If any of you (including @habitatus @kusmi @klivin) are still having troubles, feel free to reopen this issue or a new one, OR contact us on the ASDK Slack channel (#1582). I hope you have been able to use the framework!

**Closed by appleguy** 2016-06-06 02:36 UTC
Labels: close if no reply, Swift
