### ISSUE TITLE
Layout transition isn't resizing cells properly

### ISSUE THREAD

**Issue by tomizimobile** [facebook/AsyncDisplayKit#2713] opened 2016-12-05 20:19 UTC
Just noticed today that one of my transitions is no longer working correctly. It's a transition in a subclass of ASCellNode, that will either shrink or grow to show different content based on the state of a button. Everything works as expected up until commit 7861c63a680f516fc69cd083d462469f0a175697. Now, when the cell is supposed to grow, the content of the cell is drawn aligned to the center of the cell and spills out of the top/bottom, and the cell is not resized. When it is supposed to shrink, the content seems to be drawn aligned to the center of the old size of the cell, but the cell seems to be resized.

**Comment by hannahmbanana** [comment] 2016-12-05 20:37
@tomizimobile - would it be possible to attach screen shots or, ideally, a sample project? Thanks!

**Comment by tomizimobile** [comment] 2016-12-05 20:46
Sure, I don't have the time right now to make a sample project, but here's screenshots showing how it's supposed to look, and how it looks after each of the transitions mentioned.

[Archive 2.zip](https://github.com/facebook/AsyncDisplayKit/files/632228/Archive.2.zip)

**Comment by hannahmbanana** [comment] 2016-12-05 20:50
@tomizimobile - could you try updating to master? I believe @maicki made a layout change in the last few days that might have fixed this.

**Comment by tomizimobile** [comment] 2016-12-05 20:52
@hannahmbanana I should've mentioned, I was working with master this morning and saw this issue, and that's when I narrowed the problem down to that commit.

**Comment by tomizimobile** [comment] 2016-12-05 21:01
oh and for clarification on those screenshots - in the unfollowed versions, what appears to be the 2nd of 3 cells is actually just part of the first cell. The animation moves the button up or down to collapse/expand that space.

**Comment by maicki** [comment] 2016-12-07 22:02
@tomizimobile Hey, can you please pull the latest from master and if possible provide some kind of really small example. I try to reproduce with a similar setup as you have, but unfortunately I'm not able to. Thanks!

**Comment by tomizimobile** [comment] 2016-12-08 13:10
@maicki here you go - I've taken that exact class and stripped it down a bit, in case it's something very specific to the way i'm animating things or something like that. Look at the bottom of `ModalViewController.swift` for the class `HeaderNode`

[ASDK-crash.zip](https://github.com/facebook/AsyncDisplayKit/files/639469/ASDK-crash.zip)

**Comment by maicki** [comment] 2016-12-08 17:35
@tomizimobile I looked into this into a bit more details today. The important change we did with 2.0 is to shift the responsibility to resize a specific node of a hierarchy to the supernode of it. In this case as you use a layout transition within a cell the cell is responsible for updating it's size based on the new layout. Unfortunately you don't update the size of the node in your `animateLayoutTransition` implementation. You can see the right behavior if you just call `super.animateLayoutTransition(context)` or instead of calling `transitionLayout()` call `setNeedsLayout()`. In case of `setNeedsLayout()` the display node internally will update the size to the new layout without calling the layout transition api.

**Comment by tomizimobile** [comment] 2016-12-08 18:32
@maicki huh, I didn't know that just by calling `super.animateLayoutTransition(context)` it would perform all the necessary animations for me by default, neat! I don't think that was available when I initially did this. I'd much rather just call `transitionLayout...` and not override `animateLayoutTransition` at all. I've got a couple concerns with that though. 
- Can I customize the speed of the animation? It looks like the nodes move at a different rate than the cell resizes
- In that project, the title of the button `follow` changes based on the state, and it doesn't seem like it's resizing properly. If you change line 212 in `ModalViewController.swift` to `follow.isSelected = true`, you'll see after the transition that the new title is cut off, because the initial title is smaller than the title after the transition. (It works fine if I override `animateLayoutTransition` and add `follow.setNeedsLayout()`, but I figured this would be handled)

**Comment by garrettmoon** [comment] 2016-12-12 18:32
@maicki can you investigate for 2.0.1 and punt if necessary?

**Comment by maicki** [comment] 2016-12-15 14:16
@tomizimobile Hey I looked a bit more into this and there are a couple of ways to prevent this:
1. You can call `follow.setNeedsLayout` to the follow button before calling `super.animateLayoutTransition(context);`
2. You can call the layout transition api with should measure `async: false`: `transitionLayout(withAnimation: true, shouldMeasureAsync: false, measurementCompletion: nil)`.

The problem currently could be that the follow button is get a layout pass before we call through with the new size due to the async nature. The transition api will be one of main focuses for 2.1+ that I will work on and I have a couple of ideas to tackle this kind of problem. I think as the this problem is not related anymore to the main title / issue I will close this issue. @tomizimobile can you please open a new issue with the new issue (text truncating), we would appreciate it. Thanks!

**Closed by maicki** 2016-12-15 14:16 UTC
Labels: P3
