### ISSUE TITLE
[ASInterfaceState] Regression: plain view-hosted nodes don't automatically fetch data anymore

### ISSUE THREAD

**Issue by tettoffensive** [facebook/AsyncDisplayKit#897] opened 2015-11-30 20:46 UTC
I just updated the pod to the latest master to get the fix to the table view #884 and then started seeing some of my ASNetworkImage nodes that are directly in UIViews not displaying they just continue to show the defaultImage. The source of the error seems to be this change in `- (void)setURL:(NSURL *)URL resetToDefault:(BOOL)reset`

New code:
```
  if (self.interfaceState & ASInterfaceStateFetchData) {
    [self fetchData];
  }
```

Old code:
```
 if (self.nodeLoaded && self.layer.superlayer)
    [self _lazilyLoadImageIfNecessary];
```

**Comment by Adlai-Holler** [comment] 2015-12-01 06:46
I'm sorry for this regression, thanks for bringing it up! At the heart of this issue is our reliance on the range controller to inform nodes of their interface state. Unfortunately I'm not sure the old code is super good either – this code may be called on a background thread but it accesses the `superlayer` property, and having a superlayer hardly implies that we should download an image. 

@appleguy Would it be insane to, as long as only our cell nodes will get interface state info, check to see if we have an `ASCellNode` ancestor? Something roughly like `if ((self.as_cellNode == nil && self.isNodeLoaded) || self.interfaceState & ASInterfaceStateFetchData)`? It's not gorgeous, but it should get us decent interim behavior – cell nodes will load intelligently and all other nodes will fire away the download immediately, so long as the node is loaded. And then when the node gets loaded, if we're not in a cell node, we fire away also.

**Comment by appleguy** [comment] 2015-12-04 03:35
@tettoffensive The best way to fix this right now is actually to call setInterfaceState: yourself on the node.  I have the property set to readonly, but that's simply because I wanted to provide better documentation for the appropriate use cases to do this before making the API that flexible.

Likewise, I apologize for this regression, and thank you for reporting it.  Though it immediately makes sense and the cause is well-understood, I did NOT realize this would affect current clients of the framework and would have proceeded differently with this change had I known that.

Could you share with me the details on why you are containing a node directly within a standard UIView?  There are a couple behaviors that don't work well with this; most notably, nothing will trigger rendering (or indeed even data fetching) before the view is added to the hierarchy, and that often doesn't happen until the element is visible onscreen.  So it basically deactivates all of the fancy preloading stuff that makes ASDK apps feel "seamless" in that content is usually there and rendered even with smooth scrolling.  You will, of course, still be getting big benefits from rendering staying off the main thread.

You might consider using ASViewController in your scenario.  Though it doesn't support interfaceState today, it will in an upcoming release this month.  It will not only automatically set interfaceState on the node tree that it hosts, but also allow the user to set custom interface states so you can trigger data loading or rendering before the VC is visible.

@Adlai-Holler — I think your suggested workaround is the best course of action until these other usages / flexibilities of interfaceState are built out.  Once those things are done, we might consider restricting use of nodes in arbitrary UIViews, perhaps by requiring a certain property be enabled that explains to engineers the implications / tradeoffs of doing this.  The other path is to consider this a valid use case for ASDK and retain first class support for it, with automatic interfaceState changes according to the limited information available from UIView / CALayer hierarchy change notifications.  My main hesitation with that is simple: I'm not that sure what use cases that would help support, since it seems to me like a pretty bad issue for asynchronous rendering to never be triggered until something is visible.

**Comment by appleguy** [comment] 2015-12-04 03:37
I will ship a 1.9.3 shortly after we fix this, which should be by the end of this weekend.

**Comment by tettoffensive** [comment] 2015-12-04 16:15
@appleguy while most of the time my use of ASDK is for complex hierarchies
of views involving table and collection views and custom nodes, I got used
to using ASNetworkImageNode (along with caching via SDWebImage). It is
extremely convenient for things like user profile photos. And I often just
need that on a UIView like the toolbar or profile view. Since UIView has
addSubnode and there has to be some entry point into AS mode hierarchy, I
figured this was supported.
I like the flexibility of being able to mix like this without needing more
complexity.

**Comment by Adlai-Holler** [comment] 2015-12-04 19:35
@appleguy What he said.

**Comment by Adlai-Holler** [comment] 2015-12-04 21:39
@tettoffensive Could you check if #913 fixes the image loading?

**Comment by appleguy** [comment] 2015-12-06 01:37
@tettoffensive I'll leave this open until you've had a chance to confirm.  We are still working actively on some of the issues of 1.9.2.  It is possible that master will actually have a higher risk of deadlocking until my next change eliminates an element that has been essential to each reported deadlock.  If you do have a moment to test before Sunday night, that will help build confidence that 1.9.3 is in much better shape than 1.9.2 went out with.

**Comment by appleguy** [comment] 2015-12-07 06:04
@tettoffensive 1.9.3 going out soon.  Very interested in the result if you are able to test later - I have pretty high confidence now that the fix is developed and landed.  We did add a test related to this as well, but this is an area where more testing is definitely required to ensure it never breaks again..

**Closed by appleguy** 2015-12-07 06:04 UTC
Labels: API improvement, fix landed

**Comment by tettoffensive** [comment] 2015-12-07 18:20
@appleguy Sorry wasn't able to test until this morning. Just pulled the latest master which I believe has the fix. It seems to work. Thanks @Adlai-Holler!

**Comment by Adlai-Holler** [comment] 2015-12-07 19:57
No problem!
