### ISSUE TITLE
AsTableView reloadData and reloadRowsAtIndexPaths are very heavy

### ISSUE THREAD

**Issue by asolakhyan** [facebook/AsyncDisplayKit#344] opened 2015-02-28 23:06 UTC
Hi,

I have multiple table view controllers which share data and the app architecture basically sends a signal to the respective controller which reloads the data.
This does not work well after I switched to use ASTableView. ReloadData is very expensive (as it states in the doc), but I was surprised to see reloadRowsAtIndexPaths is expensive as well. The cell flickers. I am using ADK version 1.1.1.  
Many people suggest using begin/end updates, but in my case it's not implemented:
- (void)beginUpdates
{
  [self throwUnimplementedException];
}

Is there a workaround to this problem? Will really appreciate any help.

Thanks.

-A

**Comment by secretiverhyme** [comment] 2015-03-01 22:49
ASTableView's `-beginUpdates` and `-endUpdates` are available in master and will be included in the upcoming 1.2 release.  You can try it out now by pointing your Podfile at the GitHub repository directly.

Cell reloads aren't as expensive as a full `-reloadData` call, but they're not yet optimised and there may be a better way to achieve what you're trying to do.  You're likely seeing flickering because the new nodes come onscreen before they're fully rendered -- this can be avoided with a few cumbersome workarounds, but we're hoping to solve this more elegantly directly in ASTableView.

Have you considered using updates (delete & insert rows) instead of reloads?  We strongly recommend using updates where possible for a number of reasons.  @toulouse's [BKDeltaCalculator](https://github.com/Basket/BKDeltaCalculator) might be helpful if you're not sure how to start.

cc @tanliboy

**Comment by asolakhyan** [comment] 2015-03-02 03:06
Thanks a lot. The github version works nice. Thank you.
I did change the architecture to insert/delete/update row indexes instead of reloadData. With begin/end update working the flickering is minimal.
It's interesting.. I've tried instead of refreshing the whole cell, refresh just a sub node (ASImageNode) in my case. It did not work. Didn't go into much debugging, will do it this week, but changing the image from one to another did not take effect unless reloadRowsAtIndexPaths was called. Any idea why this might be happening? If I tap on the image and change it in the callback block, things work just fine. 

Thanks again.

-a

**Comment by lxcid** [comment] 2015-03-03 14:23
I followed @secretiverhyme recommendation and tried out BKDeltaCalculator. I still face some issue when it come to wrapping delta changes in begin and end updates.

BKDeltaCalculator calculate insert and delete changes accurately, but at the same time it generates a lot of move changes that are resultant from the insert and delete changes. Technically they are accurate and when applied to UITableView, it work as expected, UITableView will not animate those extra move changes.

When I use it with ASTableView, I notice some issues. To better explains I had to use an example:

Lets say I have an initial array of `[ 1, 2, 3, 4, 5 ]`. I would like to insert `0` to the front and remove the last element, in this case `5`. The final array should look like `[ 0, 1, 2, 3, 4 ]`.

BKDeltaCalculator will generate the following delta results, insert at index 0, delete at index 4 and move at `0 to 1`, `1 to 2`, `2 to 3` and `3 to 4`.

If this is applied to `UITableView`, only the insert and delete are animated, the move are ignored.

If this is applied to `ASTableView`, the first node get a refresh but not updated, it is still showing the old node, even though the new node is being queried through `tableView:nodeForRowAtIndexPath:`.

Initially I thought if I calculated the correct move, things will work alright and true enough the problem is gone.

Then come another issue, If I ever use `reloadRowsAtIndexPaths:withRowAnimation:` in begin and end updates, it is unclear if the method uses the data prior to the begin and end updates or uses the latest state of the data.

Let say, I tried to reload the those unchanged cells (basically those cell that are calculated as moved in BKDeltaCalculator). If I use the old index paths, it will complains that the animation clashes with the insertion index (0). If I use the new index paths, it will complains that the animation clashes with the deletion index (4).

UITableView documents did specify that reload is similar to delete so it uses the old index paths.

This is currently my finding. I'll try to extend kitten to illustrates the problem if possible.

**Comment by asolakhyan** [comment] 2015-03-03 14:43
In my case I already had a delta calculator of my own, so I did not use BKDeltaCalculator. I enhanced mine, so besides the index paths it also drills down to which individual node in the cell should be updated. This is were I run into the problem, as nodes wouldn't get refreshed. It sounds like the issue I am facing is described in #346 "nodeForItemAtIndexPath: as method equivalent to ASCollectionView's cellForItemAtIndexPath".

**Comment by lxcid** [comment] 2015-03-03 16:19
@asolakhyan Thanks! Glad to know I'm not the only one facing the issue.

I fork and branch ASDK here (https://github.com/lxcid/AsyncDisplayKit/tree/bug/delta-changes) to illustrate the problem.

You can tweak the `USE_UIKIT` between `0` and `1` to switch between ASDK and UIKit implementation. You need to update the pod first.

I also notice that if I use `asyncDataFetching`, it will crash.

So basically, UIKit function as intended, ASDK without async works but the update is wrong. ASDK with async crashes.

Here's the video https://www.dropbox.com/s/itdfom0jorn4u6t/delta-change-bug.mp4?dl=0

**Comment by lxcid** [comment] 2015-03-05 17:52
I dig a bit deeper and allow me to explain further.

Lets say we have an initial array of `[ 1, 2, 3, 4 ]`. We then insert `0` to the beginning of the array and then remove the last element in the array. The final array should look like this `[ 0, 1, 2, 3 ]`.

If we uses `BKDeltaCalculator`, it will generate the following delta changes to the table view. These action will all be batched into an array of pending blocks to be execute later:

- Remove `4` at index `3` : `[ 1, 2, 3 ]`
- Insert `0` at index `0` : `[ 0, 1, 2, 3 ]`
- Move index `0` to index `1` : `[ 1, 0, 2, 3 ]`
- Move index `1` to index `2` : `[ 1, 2, 0, 3 ]`
- Move index `2` to index `3` : `[ 1, 2, 3, 0 ]`

As you can see, the final array does not match the delta changes. This will explain the video, why the first item got moved to the last item.

This could seems like `BKDeltaCalculator` is calculating delta wrongly. But it might not necessary be the case if we consider that `BKDeltaCalculator` is calculating the delta from the old array to the new array. The from index is based on the old array and the to index is based on the new array.

`UITableView` does adhere to this convention it seems, as illustrated in the example.

---

Lets say I remove all false positives from the delta changes. So in this case it will only generate the insertion and deletion and no move. This will definitely work nicely with ASDK until we try to reload those cells that we have moved inside the begin and end updates calls.

The problem is that the order of the calls to reload, delete and insert are important. If reload is called after delete and insert, the index of the reload will be ambiguous. In our example, reloading either the first index and last index will make UIKit complains that we tried to do 2 actions to a single cell (Either insert then reload or delete then reload).

This can be rectified (I have yet to tested it yet) by making sure reload are done before delete and then insert. In this case, it is closer to UITableView implementation where reload and delete is based on old array index.

I think the solution might be to group pending blocks of reload, delete and insert in their own array and call them in order, maybe reload, delete and insert.

**Comment by ryanfitz** [comment] 2015-03-08 18:03
I've been working on handling inserts / deletes / reloads to ASTableView cells. I'm using the latest AsyncDisplayKit on master, I've run into a number of issues / bugs, but think I've found a working solution. Here is a [gist](https://gist.github.com/ryanfitz/672be998a1c25887ed2a) showing my solution. 

I created a [lib](https://github.com/ryanfitz/RFSectionDelta) similar to `BKDeltaCalculator` to create change sets between old / new data, I then pass those change sets over to my function for running the tableview updates. I have found that the current implementations of `reloadSections`, `reloadRowsAtIndexPaths`, `moveSections`, and `moveRowAtIndexPath` do not work as expected and typically resulted in crashes. Instead of using any of those methods, I only use delete and insert operations. All the deletes must be run before any inserts. 

Another issue I've found is that calling either `insertRowsAtIndexPaths` or `insertSections` will lock the datasource and any further tableView updates called within the `beginUpdates` block will cause a `datasource locked` exception to be thrown. I would expect that the data source to get locked once, execute all tableView update operations called within the `beginUpdates` / `endUpdates` block and then unlock the datasource, instead its attempting to lock the data source multiple times within the updates block causing a crash.

-----------------
With the [gist](https://gist.github.com/ryanfitz/672be998a1c25887ed2a) I posted combined with [RFSectionDelta](https://github.com/ryanfitz/RFSectionDelta) everything seems to be working fairly well for my app which requires pull to refresh, infinite scroll and also cells which need to move positions. The biggest issue I've seen so far is sometimes I still see nodes flickering in and then moving off screen.

**Comment by asolakhyan** [comment] 2015-03-09 19:27
Btw, as @lxcid mentioned if I delete at index 0 and insert at index 0 within begin/end update umbrella, I get animations cannot be applied to the same element exception. Even though minor, I think it's a bug. Now, the original discussion started with slow reload, I don't know if you guys want to keep this one as discussion and have other issues as bugs?

**Comment by appleguy** [comment] 2016-02-07 06:04
@asolakhyan @lxcid @ryanfitz most of the issues touched on here have been resolved for quite a while, but the capstone is the following PR that just landed a few days ago: https://github.com/facebook/AsyncDisplayKit/pull/1173

Give it a try when you have a chance and let me know if there are any issues.

reloadRowsAtIndexPaths: should certainly be very efficient, so again let me know if there are issues you detect there.

reloadData Will be faster very soon, as soon as this other PR lands: https://github.com/facebook/AsyncDisplayKit/pull/1171 however, as has been extensively discussed here, Apps should strictly minimize use of record data in any case… The differing approaches mentioned are certainly a great way to do this.

Just as a reminder, if you are seeing issues with flashing, simply enable the .neverShowPlaceholders option on your ASCellNodes and you will still get concurrent rendering with a guarantee that Display is finished before the runloop is allowed to proceed, and thus before the next frame is composited.

**Closed by appleguy** 2016-02-07 06:04 UTC
Labels: bug (P1), discussion
