### ISSUE TITLE
[ASPagerNode] Add support for showing a page control.

### ISSUE THREAD

**Issue by x401om** [facebook/AsyncDisplayKit#1188] opened 2016-02-05 12:47 UTC
Hello! Now there is no way to add any UIPageControl-like component using nodes. Is it possible to add this functional as single node or right into ASPagerNode?

**Comment by appleguy** [comment] 2016-02-07 07:15
@x401om this would be a great feature to add, thanks for suggesting it! The main thing to consider is the API. I think it would be fine to use UIPageControl for this, as it almost certainly would not be the cause of any performance issues.

This could be added quite easily by creating a page control in the -didLoad method of ASPagerNode, or at the time that a property like .showPageControl is enabled, if .isNodeLoaded == YES.

Feel free to put up a pull request with such an implementation if you are interested, and I am pretty confident that we can get it to it a landable state within one or two revisions!

**Comment by appleguy** [comment] 2016-03-25 20:12
@x401om - The community is planning an exciting long term road map for the project and getting organized around how to deliver these feature requests. We are moving to a new issue tracker with more sophisticated planning capabilities (check out www.realArtists.com and their new product: Ship!). 

If you are interested in helping contribute to this component or any other, don’t hesitate to send me an email at AsyncDisplayKit@gmail.com. If you would like to contribute for a few weeks, I can also add you to our Ship bug tracker so that you can see what everyone is working on and actively coordinate with us. 

As always, keep filing issues and submitting pull requests here on Github and we will only move things to the new tracker if they require long term coordination.

**Closed by appleguy** 2016-03-25 20:12 UTC
Labels: API improvement, feature — minor
