### ISSUE TITLE
ASCollectionView crashes when trying to reload cells

### ISSUE THREAD

**Issue by mll** [facebook/AsyncDisplayKit#784] opened 2015-10-28 09:15 UTC
I use the stable version (1.2.3). I observed that reloading a cell in performBatchUpdates block causes the app to crash *sometimes*. This is caused by reloading being actually removing and adding a cell. 

This leaves ASDK in an unwanted state for a short time when internal data source (Range controller) has once cell less (due to asynchronous nature of ASCollectionView). When somebody scrolls to the bottom fast enough and hits this particular timeframe, exception is raised that access is being requested to the last cell whereas internal data source (Range controller) has one cell less at this point.

**Comment by nguyenhuy** [comment] 2015-10-28 09:28
This book problem is fixed on master (and the coming v1.9). Please check
out the new code.

Btw, if you don't want the "remove and insert" behaviour of reload, there
is a new -relayoutNodeAtIndexPath: API (also on master). It causes a new
layout pass on the existing cell node and handles animations just like
UIKit reload counterparts. Most of the time, you just need to set some
flags on the node (so that it knows how to layout next time) and then call
relayout. Sample code can be found in Kittens example.

Let us know if you run into other problems. Cheers!

**Comment by mll** [comment] 2015-10-28 09:31
As i work on a stable application now, I am looking forward to stable 1.9 release.

**Comment by nguyenhuy** [comment] 2015-10-28 10:17
I think it's not a huge risk if you rely on `master` right now, because is is actually quite stable and 1.9 will be cut from it this week. But it's your call :)

Btw, thanks for reporting this issue.

**Comment by tettoffensive** [comment] 2015-10-30 19:06
I just got a crash with ASCollectionView when it was reloadDataWithCompletion. I'm on the master branch. Not sure if this is related to the crash you got?

```
467924482 ChannelsAppDelegate.m:42 - CRASH: request for index path for global index 360279022 when there are only 10 items in the collection view
467924482 ChannelsAppDelegate.m:43 - Stack Trace: (
	0   CoreFoundation                      0x0000000183338f74 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000197e3ff80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183338e2c <redacted> + 0
	3   Foundation                          0x0000000184227f3c <redacted> + 112
	4   UIKit                               0x0000000188a6fb18 <redacted> + 304
	5   UIKit                               0x0000000188a6ea70 <redacted> + 560
	6   UIKit                               0x0000000188a6e828 <redacted> + 352
	7   UIKit                               0x00000001890776b8 <redacted> + 2308
	8   UIKit                               0x0000000189075adc <redacted> + 12448
	9   UIKit                               0x0000000188a6c7bc <redacted> + 364
	10  AsyncDisplayKit                     0x00000001012291e0 __85-[ASCollectionView rangeController:didInsertNodes:atIndexPaths:withAnimationOptions:]_block_invoke315 + 76
	11  UIKit                               0x000000018889dda4 <redacted> + 80
	12  AsyncDisplayKit                     0x0000000101228f98 -[ASCollectionView rangeController:didInsertNodes:atIndexPaths:withAnimationOptions:] + 1116
	13  AsyncDisplayKit                     0x00000001012a0c58 __85-[ASRangeController dataController:didInsertNodes:atIndexPaths:withAnimationOptions:]_block_invoke127 + 108
	14  AsyncDisplayKit                     0x0000000101256a70 _Z37ASDisplayNodePerformBlockOnMainThreadU13block_pointerFvvE + 104
	15  AsyncDisplayKit                     0x00000001012a08e4 -[ASRangeController dataController:didInsertNodes:atIndexPaths:withAnimationOptions:] + 848
	16  AsyncDisplayKit                     0x00000001012343d4 __67-[ASDataController _insertNodes:atIndexPaths:withAnimationOptions:]_block_invoke + 188
	17  AsyncDisplayKit                     0x0000000101232e54 __63-[ASDataController insertNodes:ofKind:atIndexPaths:completion:]_block_invoke + 132
	18  AsyncDisplayKit                     0x0000000101256b80 ___Z37ASDisplayNodePerformBlockOnMainThreadU13block_pointerFvvE_block_invoke + 40
	19  libdispatch.dylib                   0x0000000101d1dd70 _dispatch_call_block_and_release + 24
	20  libdispatch.dylib                   0x0000000101d1dd30 _dispatch_client_callout + 16
	21  libdispatch.dylib                   0x0000000101d23780 _dispatch_main_queue_callback_4CF + 2096
	22  CoreFoundation                      0x00000001832f0258 <redacted> + 12
	23  CoreFoundation                      0x00000001832ee0c0 <redacted> + 1628
	24  CoreFoundation                      0x000000018321cdc0 CFRunLoopRunSpecific + 384
	25  GraphicsServices                    0x000000018e370088 GSEventRunModal + 180
	26  UIKit                               0x00000001888f6f44 UIApplicationMain + 204
	27  Channels                            0x00000001001553c4 main + 124
	28  libdyld.dylib                       0x000000019866a8b8 <redacted> + 4
)
2015-10-30 12:01:21.925 Channels[3664:1266127] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'request for index path for global index 360279022 when there are only 10 items in the collection view'
```

```
- (void)rangeController:(ASRangeController *)rangeController didInsertNodes:(NSArray *)nodes atIndexPaths:(NSArray *)indexPaths withAnimationOptions:(ASDataControllerAnimationOptions)animationOptions
{
  ASDisplayNodeAssertMainThread();

  if (!self.asyncDataSource || _superIsPendingDataLoad) {
    return; // if the asyncDataSource has become invalid while we are processing, ignore this request to avoid crashes
  }

  if (_performingBatchUpdates) {
    [_batchUpdateBlocks addObject:^{
      [super insertItemsAtIndexPaths:indexPaths];
    }];
  } else {
    [UIView performWithoutAnimation:^{
      [super insertItemsAtIndexPaths:indexPaths]; // crash HERE line 836
    }];
  }
}
```

**Comment by appleguy** [comment] 2015-10-31 01:42
@tettoffensive I have actually never seen one like that — with the index so radically far out of the reasonable range.  Could you share any other information?  Is the crash reproducible, even occasionally?  What is your general access pattern — inserts, moves, deletes, item or section reloads, whole-view reloads?

**Comment by tettoffensive** [comment] 2015-10-31 05:57
whole view reloads. I've seen it a couple times. it *might* be the case when that the table was getting loaded while it was already in the middle of reloading. I have changed somethings around so that shouldn't be happening any more, but will let you know if I see it again.

**Comment by appleguy** [comment] 2015-11-08 04:56
@tettoffensive please do let me know if you can reproduce it, even by intentionally thrashing the table.  Check out examples/ASTableViewStressTest and see if you can make that trigger it if you have any theories on how to cause it.

Crashes are completely unacceptable provided the delegate / dataSource state are consistent — calling reload repeatedly during a load is definitely no exception.

**Closed by appleguy** 2015-11-08 04:56 UTC

**Comment by tettoffensive** [comment] 2015-11-09 19:39
"Crashes are completely unacceptable provided the delegate / dataSource state are consistent — calling reload repeatedly during a load is definitely no exception."

@appleguy What about if the datasource changes. The data source is set to a NSDictionary of NSArrays which do get updated when new data is pulled down from the server.

**Comment by xilin** [comment] 2017-04-13 06:31
@tettoffensive see [here](https://github.com/facebook/AsyncDisplayKit/issues/2618). The datasource should be thread safe.
