### ISSUE TITLE
[ASImageNode, ASRatioLayoutSpec] Incorrect layout when loading images with different delay

### ISSUE THREAD

**Issue by yxztj** [facebook/AsyncDisplayKit#1187] opened 2016-02-05 10:42 UTC
Repro:
1. Create an ASTableView, with each cellNode containing 2 imageNodes(ratio 1:1).
2. Set images asynchronously with different delay.
When images are set after 0.1s(after layout is done), we get the expected results like this:
<img width="250" alt="screen shot 2016-02-05 at 6 31 08 pm" src="https://cloud.githubusercontent.com/assets/3334458/12843935/556fd34a-cc37-11e5-8ffd-5abdacd2562f.png">
But when setting 0.0s delay(or set synchronously just try to set image before layout), we get the unexpected layout:
<img width="250" alt="screen shot 2016-02-05 at 6 31 22 pm" src="https://cloud.githubusercontent.com/assets/3334458/12843959/77d0ac7a-cc37-11e5-8ec6-b81e0d9f83d9.png">
I've created a repo to demonstrate the issue: [ASImageNodeLayoutIssue](https://github.com/yxztj/ASImageNodeLayoutIssue)

It's weird to get different layout results just because of different image load time. Is it a possible bug or am I missing anything?

**Comment by appleguy** [comment] 2016-02-07 07:52
@yxztj thanks **a lot** for creating the test project and reporting this.  We will figure this one out.

cc @nguyenhuy, @levi do you even have a guess as to what could cause this?

**Comment by appleguy** [comment] 2016-02-07 08:02
I think this may have to do with the fact that ASImageNode does not use layoutSpecThatFits:, but instead calculateSizeThatFits:...but I'm really not onto a clear lead yet.  I can reproduce though.

**Comment by appleguy** [comment] 2016-02-07 08:05
My last comment is probably nonsense because the image node doesn't manage any subnodes to put in the layout spec anyway.

Interestingly even if the dispatch is entirely removed and the image is set synchronously on both image nodes, it still doesn't work.  I would have expected the opposite, but by performing them in two different runloops, that is the only case that works.

**Comment by appleguy** [comment] 2016-02-07 08:10
OK, so this actually also allows it to work.  So they can both be set on the same runloop.  Just NOT on the runloop that they are created / added / initial layout is performed on?!

>       let node1 = ASImageNode()
      node1.backgroundColor = UIColor.lightGrayColor()
      testNodes.append(node1)
      self.addSubnode(node1)

      let node2 = ASImageNode()
      node2.backgroundColor = UIColor.lightGrayColor()
      testNodes.append(node2)
      self.addSubnode(node2)
      
      // Change delay to 0.1 would bring the expected layout.
      let nanoSeconds = Int64(0.1 * Double(NSEC_PER_SEC))
      let time = dispatch_time(DISPATCH_TIME_NOW, nanoSeconds)
      
      dispatch_after(time, dispatch_get_main_queue(), {
          node1.image = UIImage(named: "test1")
          node2.image = UIImage(named: "test2")
      })

**Comment by appleguy** [comment] 2016-02-07 08:17
Ha!  This DOES layout correctly.  It's almost as though the image setting is messing something up...but ONLY if it happens in the same runloop as the initial creation?!

      let node1 = ASImageNode()
      testNodes.append(node1)
      node1.backgroundColor = UIColor.redColor()
      self.addSubnode(node1)

      let node2 = ASImageNode()
      testNodes.append(node2)
      node2.backgroundColor = UIColor.blueColor()
      self.addSubnode(node2)
      
      // Change delay to 0.1 would bring the expected layout.
      let nanoSeconds = Int64(0.0 * Double(NSEC_PER_SEC))
      let time = dispatch_time(DISPATCH_TIME_NOW, nanoSeconds)
      
      dispatch_after(time, dispatch_get_main_queue(), {
//          node1.image = UIImage(named: "test1")
//          node2.image = UIImage(named: "test2")
      })

**Comment by appleguy** [comment] 2016-11-18 22:38
@maicki @yxztj can one of you verify this is fixed in master?  It should be.

**Comment by maicki** [comment] 2016-11-23 00:24
Hey @yxztj, this is actually the expected behavior.

I try to explain it a bit more in detail: If you set a ratio of 1.0 / 1.0 the ratio tries to use the constrained size that get's passed in to figure out the constrained size for the child that needs to calculate it's size based ont he passed in constrained size. Unfortunately because the way the overall layout is described the passed in constrained size in the ratio specs will be (0, 0), (Infinity, Infinity). As said ratio layout spec tries to figure out what's the best size is based on the child by passing in this constrained size into the ASImageNode child. There are now two cases:
1. Image is already set on the ASImageNode (with 0.0 delay): As in the time the ratio spec asks for the size based on the child image node and the image node already has an image assigned it will return this size for itself. Based on that the stack spec that contains the ratio spec tries to layout the two ratio specs but as it exceeds the width it will layout the left image node the size it would like to be and shrinks the right image
2. Image is not set on the ASImageNode (with 0.1 delay): In this case the ratio layout spec is passing in the unconstrained size to the child and as no image is set the image node will returned the passed in size as size of itself. Based on this the stack spec that contains the ratio specs tries to layout the two ratios specs but as both of these will have width and height unconstrained it will give it a width of 50% (minus the spacing). As the images are than set after the layout pass happened the images will both look like they have %50 width and a ratio of 1/1 what is actually not really true, the images are smaller as 1/1. With 2.0 it's actually a wrong behavior to use the image nodes this way and a log will be printed out as there is no size given to ASImageNode's that don't have a specific size set via `style.preferredSize` or an image assigned where the `ASImageNode` can determine the size

I will close that issue for now as this is expected behavior. Please reopen if there are open questions / issues. Thanks!

**Closed by maicki** 2016-11-23 00:24 UTC
Labels: Bug, P3

**Comment by appleguy** [comment] 2016-11-23 05:28
@maicki thank you for explaining!  As long as 2.0 is now printing out that warning log, this seems like a great resolution.  Before that log, it was harder to tell as a developer that the layout was under-specified.
