### ISSUE TITLE
[ASCellNode] interface state sometimes doesn't update

### ISSUE THREAD

**Issue by knopp** [facebook/AsyncDisplayKit#1011] opened 2015-12-28 22:16 UTC
This happens when

`[UICollectionView scrollToItemAtIndexPath:atScrollPosition:animated:NO]` is called from within the `[ASCollectionView reloadDataWithCompletion:]` block

i.e.

```objectivec
[collectionView reloadDataWithCompletion:^{
    [collectionView scrollToItemAtIndexPath:activeIndexPath
                           atScrollPosition:UICollectionViewScrollPositionCenteredVertically animated:NO];
}];
```

the problem seems to be caused by `[ASRangeController _updateVisibleNodeIndexPaths]`
```objectivec
// Notify to remove indexpaths that are leftover that are not visible or included in the _layoutController calculated paths
NSMutableSet *removedIndexPaths = _rangeIsValid ? [_rangeTypeIndexPaths[rangeKey] mutableCopy] : [NSMutableSet set];
```
in this instance, `_rangeIsValid` is set to false, because items are being still added, and thus `removedIndexPaths` will always be set to empty set; `addedIndexPaths` works properly because it doesn't check for `_rangeIsValid`;

Why this inconsistency? Is the `_rangeIsValid`? check really necessary when determining `removedIndexPaths`? When I remove it, i get correctly reported interface state
```objectivec
// Notify to remove indexpaths that are leftover that are not visible or included in the _layoutController calculated paths
NSMutableSet *removedIndexPaths = [_rangeTypeIndexPaths[rangeKey] mutableCopy];
```

**Comment by appleguy** [comment] 2015-12-29 03:17
@knopp Good bug - thank you for reporting this.

I am actually planning to rewrite ASRangeController soon.  If you look in ASDisplayNode+Beta.h, you'll see the option that Pinterest is currently using internally, which basically means that ASRangeHandler (especially ASRangeHandlerRender) can go away and be driven entirely by ASInterfaceState.  This will also mean that the range update method can be made super efficient, and do one pass over the nodes to determine every range that each node should be in, and then just call setInterfaceState: on the node with the full bitfield.  Then the node will automatically perform only the state transitions necessary, and not even recursively call its subnodes to update if there is no change in the ASInterfaceState.  It will actually be more efficient than the current system even though setInterfaceState: will be called relatively frequently, and will eliminate almost all of the state that ASRangeController currently needs to track and keep in sync with ASDataController.  If you have any interest in attempting this change (to be enabled only when the new render ahead system is enabled), feel free to give it a shot - just let me know if so, because in that case I would spend my effort on another part of the many areas of the framework I want to upgrade in the next few weeks :).

The other key areas I'm working on involve the reloading options for table / collection which will enable super high efficiency synchronous loading to ensure the minimal amount of main thread blocking occurs to get the visible range populated, performing concurrent measurement and display on just enough cells to fill that visible area (even if the visible area is scrolled down many screens from the top).  This should allow you to consolidate the two calls to be something more like -loadDataToEnsureDisplayInRect:(CGRect) scrollToVisible:(BOOL).

That said, I will investigate this tonight or tomorrow to see if there is a targeted fix that I can land in time for 1.9.4.  Just to confirm, what commit / version are you testing on?  Please make sure to try out master just to be certain, because there have been a variety of changes / improvements.

Please continue to file any issues for either feature requests or suboptimal behaviors you've observed from using the framework - I can tell you are fairly experienced and would very highly value your input on a variety of topics.

**Comment by knopp** [comment] 2015-12-29 04:07
Hi,

this is with current master (4c4f0c8932c44704778762503284364ba1a79a0c). I'll take a look at new rendering range tomorrow. 

As for the new call, you still need to know the size for all nodes before the one you're scrolling to, so that you can calculate the rect to display, right? Thus if you want to scroll to the latest cell after load, you have to build all previous nodes anyway to layout and measure them. That could be quite a lot of work for synchronous reload, what am I missing here?

**Comment by knopp** [comment] 2015-12-29 15:53
So, couple of things. `[ASDisplayNode shouldUseNewRenderingRange]` doesn't seem to make any difference in my case (at least with respect of how `ASRangeController` handles removed items.

My change in first comment (updating deleted nodes regardless of `_rangeIsValid`) causes a crash where the `ASRangeController` sometimes tries to access deleted nodes after reload. I think that might be the reason why deleted nodes were not updated when `_rangeIsValid` is false. 

Still, that doesn't really work for me, since in it's current state this causes nodes to be left marked as visible even though they are long gone offscreen. So instead I changed the `didDeleteNodes:` method to remove deleted indexPaths from `_rangeTypeIndexPaths`

```objectivec
- (void)dataController:(ASDataController *)dataController didDeleteNodes:(NSArray *)nodes atIndexPaths:(NSArray *)indexPaths withAnimationOptions:(ASDataControllerAnimationOptions)animationOptions {
  ASPerformBlockOnMainThread(^{
    _rangeIsValid = NO;
    
    // When removing nodes we need to make sure that removed indexPaths are not left in _rangeTypeIndexPaths,
    // otherwise _updateVisibleNodeIndexPaths may try to retrieve nodes from dataSource that aren't there anymore
    for (NSInteger i = 0; i < ASLayoutRangeTypeCount; i++) {
      ASLayoutRangeType rangeType = (ASLayoutRangeType)i;
      id rangeKey = @(rangeType);
      NSMutableSet *rangePaths = [_rangeTypeIndexPaths[rangeKey] mutableCopy];
      for (NSIndexPath *path in indexPaths) {
        [rangePaths removeObject:path];
      }
      _rangeTypeIndexPaths[rangeKey] = rangePaths;
    }
    [_delegate rangeController:self didDeleteNodes:nodes atIndexPaths:indexPaths withAnimationOptions:animationOptions];
  });
}
```

This way it no longer crashes (`_updateVisibleNodeIndexPaths` is not trying to access deleted nodes anymore) and I get proper interface state on all nodes.

**Comment by appleguy** [comment] 2015-12-30 05:04
@knopp I was unclear - my apologies.  The mode I mentioned does not currently impact ASRangeController's implementation, but it will in the next week or so.  With that mode on, it is no longer necessary to have the complex, stateful implementation seen in ASRangeHandlerRender.  Because of the removal of the need to maintain the nodes in the workingWindow when they are not visible (and thus treat visibility different than offscreen-but-should-display), it will be possible to dramatically simplify and optimize the implementation of ASRangeController to set the correct ASInterfaceState on every node on every pass.  I believe this will either directly resolve, or much more readily enable resolving the issue you've pointed out.

So far I have not been able to reproduce.  Using my latest PR (it should be landed by the time you read this, #1014) I added this code to the VerticalWithinHorizontalScrolling example to be triggered after tapping the Redo button in the navigation bar:

  [_pagerNode.view reloadDataWithCompletion:^{
    [_pagerNode.view scrollToItemAtIndexPath:[NSIndexPath indexPathForItem:5 inSection:0]
                           atScrollPosition:UICollectionViewScrollPositionCenteredVertically animated:NO];
  }];

Once I have a reproduction case, I will make it a top priority to ensure this is fixed.  Sadly I may need to release 1.9.4 without this, because 1.9.3 has a few bugs that are more serious than this (at least, judging by the fact that several people have reported them, whereas this still-extremely-serious bug looks to be affecting fewer people as it is the first report).  I think this is the most urgent bug in the framework right now, so you have my commitment to work through a solution - both short-term (hopefully an elegant workaround), and long-term (structural / architectural improvements that also eliminate the conditions that made this bug possible).

Let me know if you have any tips on a change I can make to any one of the example projects to trigger this!

**Comment by appleguy** [comment] 2015-12-30 07:22
@knopp I'm going to hold the release one final day - in part so I can conduct additional testing tomorrow, but primarily for this issue (it's the last one in the 1.9.4 milestone).  If you are able to describe a code change (or upload a small patch file) to apply to one of the ASDK example apps, which I think should be possible to use as a base to trigger what you've found, that would be tremendously helpful to enable the solution making 1.9.4 (I have a long drive to family's house tomorrow so it won't be a full day for me).

That said, don't worry if you're not available or can't seem to get it to reproduce — we can let 1.9.4 go with this issue, and I will immediately proceed to work on the more structural improvements.  Note however that there may not be another release until a 2.0 Beta in mid-late January which could contain some other risky changes such as the +Beta.h mode I referenced.  I will roll a 1.9.5 if any other bugs are found with 1.9.4 that warrant a special release on the stable 1.9.x branch.  2.0 is in a holding pattern until documentation is ready, but that work has been started recently, so I expect 2.0 to go GM in late January or February.

**Comment by knopp** [comment] 2015-12-30 12:03
@appleguy, this doesn't seem easily reproducible. Possible reason is that I have quite a lot of items, so the collection view is loaded progressively. But I think this is what's happening:

1. `reloadDataWithCompletion` is called
2. First collection view items are created, displayed and set to visible (`[ASRangeController _updateVisibleNodeIndexPath]`)
3. `ASDataController` adds more items, causing `_rangeIsValid` set to `NO` in `ASRangeController` (in `[ASRangeController dataController:didInsertNodes:atIndexPaths:withAnimationOptions:]`
4. `reloadDataWithCompletion` finally calls the completion block, which triggers scrolling

now because of (3), `_rangeIsValid` is set to `NO`, and `ASRangeController _updateVisibleNodeIndexPaths` will not do anything about `removedIndexPaths', due to the line below
```objectivec
NSMutableSet *removedIndexPaths = _rangeIsValid ? [_rangeTypeIndexPaths[rangeKey] mutableCopy] : [NSMutableSet set];
```

The important part here is that some items already need to be visible, while data controller is adding more items.

**Comment by appleguy** [comment] 2015-12-31 00:00
@knopp ok, that's very helpful context.  Questions then:

- What index paths are you scrolling to?  The batch size is roughly 10 items, so I assume you are scrolling to an index path greater than 10 at a minimum?
- I can take a pass at fixing this, but without a way to reproduce and confirm the fix, I wouldn't be comfortable including it in 1.9.4 - since any change to this code is fairly risky, I want to be certain that it does indeed address a known issue and then would feel the risk is appropriate.

I'm writing up the release notes now for 1.9.4 and want to start the ASRangeController rewrite tonight (for a later release).  Let me know if you happen across a way to reproduce, even if it doesn't happen 100% of the time, say by making a test project have 1000 items and scrolling to item 900 or something.

**Comment by knopp** [comment] 2015-12-31 00:55
@appleguy, it is probably around a hundred, so it is done in multiple batches. 

I completely agree that this shouldn't go into 1.9.4 without proper test case. The behavior is very consistent in my project, but it is not easily extractable. Is there any point in actually trying to build a test case for this if you're going to rewrite ASRangeController anyway? I'm currently a bit behind schedule with the project, however if there are similar issues after the rewrite I'll do my best to provide a test case to reproduce this. Knowing which nodes exactly are visible is very important for our usecase, since visible nodes trigger/schedule expensive server side processing (and when nodes get hidden the processing is stopped/cancelled)

**Comment by appleguy** [comment] 2015-12-31 01:45
@knopp ok, thanks for your input - I really appreciate it!  Knowing that the visibility notifications are key for your use case is very motivating for me to get this working for you, so thanks for sharing those details about your project :).  I am quite excited to ensure that the ASDK architecture makes it easier for your app + backend implementation to have sophisticated, optimized runtime behaviors.

Regarding the test case, I do think it would be quite valuable to have a reproduction because that code would then belong in the unit test suite for ASRangeController and/or components based on it (helping validate the new implementation too).

Do you have a workaround for this?  If so, don't concern yourself with the test case in the near term, and good luck focusing on your key milestones!  After a couple weeks, if you get time to put together a test that fails for 1.9.4 but (hopefully passes) for current master at that time, that would be a really fantastic contribution.

**Comment by knopp** [comment] 2015-12-31 02:18
@appleguy, sorry, should have mentioned this - these two commits from my fork fix the issue for me, so I'm good for now (at least until you rewrite `ASRangeController`)
https://github.com/knopp/AsyncDisplayKit/commit/0e2a45eb4dda3bfd80799d2792447deef20f3131
https://github.com/knopp/AsyncDisplayKit/commit/79640f2d5a267d008fb5df4963f87d260705e544

**Closed** 2015-12-31 08:24 UTC
Labels: API improvement, bug, community debugging
