### ISSUE TITLE
Rare Deadlock on _propertyLock of a Subnode/Supernode Pair 

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#900] opened 2015-12-01 06:27 UTC
You may get a deadlock if a parent loads its view on the main thread while one of its subnodes calls `__rasterizedContainerNode` inside of `ASDisplayNodeRespectThreadAffinityOfNode` on a different thread.

This may happen if you set the `attributedString` property of an `ASTextNode` whose node isn't loaded on a background thread while you load the view of its supernode on the main thread. 

bg: textNode locks its properties for `ASDisplayNodeRespectThreadAffinityOfNode`
main: supernode locks its properties for `_loadViewOrLayerIsLayerBacked:`
bg: textNode waits to lock supernode in `__rasterizedContainerNode`
main: supernode waits to lock textNode in `_addSubnodeSubviewOrSublayer`

Deadlock. Screenshots attached. `SyncProgressNode` is the container of the text node. I really can't wait to dive into getting rid of thread affinity. The reason the subnode locks its properties is so that the main thread can't load its view during the `ASDisplayNodeRespectThreadAffinityOfNode` block which is a little scary.

<img width="2493" alt="screen shot 2015-11-30 at 10 15 06 pm" src="https://cloud.githubusercontent.com/assets/2466893/11493819/6ce56ff4-97b1-11e5-998c-d6feb3cd53a0.png">
<img width="2493" alt="screen shot 2015-11-30 at 10 15 36 pm" src="https://cloud.githubusercontent.com/assets/2466893/11493823/6d0be670-97b1-11e5-892e-61a3526392a6.png">
<img width="2493" alt="screen shot 2015-11-30 at 10 15 13 pm" src="https://cloud.githubusercontent.com/assets/2466893/11493821/6d08058c-97b1-11e5-90f2-79c5e070ac35.png">
<img width="2493" alt="screen shot 2015-11-30 at 10 15 19 pm" src="https://cloud.githubusercontent.com/assets/2466893/11493824/6d0c2d92-97b1-11e5-8430-693e45a608d6.png">
<img width="2493" alt="screen shot 2015-11-30 at 10 15 23 pm" src="https://cloud.githubusercontent.com/assets/2466893/11493820/6d07b8a2-97b1-11e5-9144-bf6399a1cce1.png">
<img width="2493" alt="screen shot 2015-11-30 at 10 15 29 pm" src="https://cloud.githubusercontent.com/assets/2466893/11493822/6d0ac966-97b1-11e5-9874-50c59e68d5f0.png">

**Comment by Adlai-Holler** [comment] 2015-12-01 06:30
NOTE: This isn't blocking work for me. It's super rare and by loading the text node's layer before loading the container's works around this.

**Comment by Adlai-Holler** [comment] 2015-12-01 22:32
I've reduced it to this toy app https://github.com/Adlai-Holler/ASDKNodeHierarchyDeadlock . I'm 10 for 10 on getting the deadlock to trigger.

**Comment by zintus** [comment] 2015-12-03 15:27
Happens for me too. App deadlocks in 1/10 startup attempts. In my case background thread is doing batch layout for table view, while main thread changes `backgroundColor` property on a cell subnode.

Do you need crashlog from me?

**Comment by Adlai-Holler** [comment] 2015-12-03 16:43
To clarify, none of the nodes in my example have `shouldRasterizeDescendants = true`. The text node is just reading `_rasterizedContainerNode` to check it.

**Comment by appleguy** [comment] 2015-12-03 19:16
@Adlai-Holler thanks for the details!  I had actually run into this during development of my working window removal diff - if you look, you can see the debug logs I'd added.  However, I had reason to suspect it was specific to that change, as it had never occurred before and would go away when stashing the change.  It looks like it just changed timing or access patterns in a way that made it more common.

This is a nasty issue, so I will try to find the right fix today.

**Comment by appleguy** [comment] 2015-12-04 03:56
@zintus it would be great if you have a full thread backtrace (symbolicated crashlog would do the trick).  I want to look at any and all instances of this terrible issue.

@Adlai-Holler I have been able to reproduce reliably with your test project.  Thanks for developing it — it will really accelerate debugging, because previously I relied on a flow in the Pinterest app (with a large number of nodes onscreen, and other processes going on in the background).

Merging in / tracking https://github.com/facebook/AsyncDisplayKit/issues/902 in this task as I'm nearly certain they will be addressed by the same fix.

**Comment by appleguy** [comment] 2015-12-04 06:05
@Adlai-Holler what a nasty bug.  I completely agree regarding the property system.  It is the largest essential refactor I see in the project right now.

Another underlying factor is the extremely coarse granularity of _propertyLock; it is used for essentially everything.  I think it may be possible to break this cycle by splitting out a _loadLock or similar.

If closer analysis reveals the lock split will not quite avoid a different point of dependency occurring, I believe we can break the chain at the __rasterizedContainerNode level. Passing that state from above whenever a node enables or disables rasterization would also optimize certain calls in a way that could be net-beneficial for performance.

**Comment by Adlai-Holler** [comment] 2015-12-04 06:21
Cool, I completely agree about `_propertyLock`, I was honestly surprised it worked as I first dug into `ASDisplayNode.mm`. Good thinking about propagating rasterized container state downward. I'm still learning best practices for locking but it makes sense that it'd be safer to never look up the tree if possible. Godspeed!

**Comment by zintus** [comment] 2015-12-04 08:34
Well, it's happening all the time in simulator, so i've captured related thread stacks with lldb.
[asdk-deadlock.txt](https://github.com/facebook/AsyncDisplayKit/files/51787/asdk-deadlock.txt)

**Comment by appleguy** [comment] 2015-12-06 01:28
@zintus thanks for the backtrace!  Fortunately, the key cause is identical for the deadlock you're seeing, and I think my change will address it.

**Comment by appleguy** [comment] 2015-12-07 03:33
@zintus @Adlai-Holler fixed with https://github.com/facebook/AsyncDisplayKit/pull/915

Thanks a lot for all the detail you provided on this.  I'm quite happy with the fix, as it notably improves the architecture / elegance of a couple core mechanics of the framework - and is a platform that will allow further refactoring improvements in the near future.

Please test it out, either on master now or 1.9.3 shortly, and file a new issue for any problem you encounter.  I'm pretty confident it won't be a deadlock, though :)

**Closed by appleguy** 2015-12-07 03:33 UTC
Labels: bug, fix landed
