### ISSUE TITLE
[ASLayoutSpec] Automatic up & down propagation of ASLayoutable properties for single-child specs.

### ISSUE THREAD

**Issue by eanagel** [facebook/AsyncDisplayKit#1396] opened 2016-03-18 18:59 UTC
I'm really enjoying using ASLayout but I've gotten stuck here. I need the the text node with the ellipsis below to wrap and somehow it's not working. Note that the other text node you see here is wrapping fine. (The red outlines show the borders of each node - a debugging feature I've implemented.)

![image](https://cloud.githubusercontent.com/assets/842898/13888631/ab9379b4-ecff-11e5-9463-0a4dc7286fdf.png)

I'm using 1.9.7 which as of right now == master (commit c8cbd2ec4aeb48c5e3b1a2c6bddbf882d1535cca)

In my constructor:

    _activityTextNode = [[ASTextNode alloc] init];
    _activityTextNode.placeholderEnabled = NO;
    _activityTextNode.layerBacked = YES;

`maximumNumberOfLines` defaults to 0 and `truncationMode` defaults to `NSLineBreakByWordWrapping` Which seems like exactly what I want.

A very simplified `layoutSpecThatFits:` that still reproduces the problem (icon is excluded)

    ASInsetLayoutSpec *inset = [ASInsetLayoutSpec insetLayoutSpecWithInsets:TEXT_INSET child:_activityTextNode];
    return inset;

Here I've experimented with `flexGrow` and `flexShrink` settings for `inset` but that didn't seem to make any difference.

**Update:** I saw some discussions about explicitly setting a truncation string fixing some kind of similar issues so I added ` _activityTextNode.truncationAttributedString = [NSAttributedString stringWithString:@"XXX" attributes:nil];` to my constructor. Interestingly this has NO effect, the string is still truncated with an ellipsis instead of the "XXX" I was expecting. Seems like a clue.

I have two questions:

1. What do I need to change to make this work, and
2. How can I debug issues like this. Right now I'm trying different values and re-running to see what changed. I really can't tell which ASLayoutable is causing the issue so it's very hit and (mostly) miss.

**Comment by eanagel** [comment] 2016-03-18 19:19
@appleguy Not sure who our resident ASLayout expert is, but I could use a hand here.

**Comment by appleguy** [comment] 2016-03-19 06:49
@eanagel I'm pretty sure that this will work if you set flexShrink on the text node, which I assume is what must have been the case on the message bubble beneath. Setting it on the inset unfortunately does not have a propagating effect to its children, although for that particular kind of spec, it probably should.

For layout specs with multiple children, such as a stack, setting flexShrink on the layout spec itself of course has a very different meaning than on one of the children.

@nguyenhuy @levi @maicki @hannahmbanana Does this answer sound correct to you, and how might we improve the API with automatic propagation of ASLayoutable / ASStackLayoutable properties? Would it be possible to do this automatically for all ASLayoutSpecs with a child count of 1?

**Comment by eanagel** [comment] 2016-03-19 07:41
I've tried different combinations of `flexShrink` and `flexGrow` with no success. Here is my most aggressive use of `flexShrink`:

    _activityTextNode.flexShrink = YES;
    ASInsetLayoutSpec *inset = [ASInsetLayoutSpec insetLayoutSpecWithInsets:TEXT_INSET child:_activityTextNode];
    inset.flexShrink = YES;
    return inset;

Doesn't seem to make a difference. What am I missing???

**Comment by nguyenhuy** [comment] 2016-03-20 04:45
@eanagel Happy to help you debug the layout. Is that inset spec a direct child of the horizontal stack? What is the constrained size passed to the outermost horizontal stack?

I usually find it useful to print out the ASCII representation of the whole layout hierarchy (`asciiArtString`) and the constrained size passed to the root object. Even better if you could put up a sample project.

**Comment by eanagel** [comment] 2016-03-21 21:06
@nguyenhuy @appleguy Ok I figured this out and it was a problem in the NSAttributedString we were passing. Somehow we were passing in a paragraph style of NSLineBreakModeTruncateTail which was overriding the property on the node.

**Comment by nguyenhuy** [comment] 2016-03-21 21:07
@eanagel Glad to know. Thanks!

**Comment by appleguy** [comment] 2016-04-01 06:33
@eanagel - a new internal capability called ASEnvironment has landed and one of its functions is to propagate the ASLayoutable properties up the tree. This should eliminate the need to set something like flexShrink on an insetSpec if it contains a textNode that already has flexShrink set. 

It would be really valuable if you could test this out and see if it allows you to simplify any of your layout code as well as if it causes any unexpected issues. There is some possibility that this could cause regressions, but because the framework has not gone to 2.0 yet, this would be acceptable if the resulting layout code, after fixing the issue, is simpler than before.

**Comment by appleguy** [comment] 2016-06-06 06:21
@hannahmbanana: could you add this to our 2.0 release upgraded documentation to-do list?

**Closed by appleguy** 2016-06-06 06:21 UTC
Labels: close if no reply, discussion, documentation
