### ISSUE TITLE
[ASTableView] Calling reloadData causing animated flickers

### ISSUE THREAD

**Issue by lxcid** [facebook/AsyncDisplayKit#292] opened 2015-02-05 17:52 UTC
I realize that calling `reloadData` causes animation flickers though. I had this from my app and was able to repro on Kittens sample, attached is a screen capture GIF to illustrate the issue.

![2015-02-06 01_49_38](https://cloud.githubusercontent.com/assets/297156/6065756/be04bc9a-ada2-11e4-856d-3124b937a268.gif)

**Comment by tanliboy** [comment] 2015-02-05 18:09
Thanks for reporting this issue. It is caused by the multi-step animations while reloading data.
I will think about a way to work around.

**Comment by lxcid** [comment] 2015-02-06 10:27
Cool! Thanks man!

**Comment by secretiverhyme** [comment] 2015-02-12 00:29
Fixed in #295.

**Comment by lxcid** [comment] 2015-02-17 22:17
Unfortunately, it still happens. I'm on cd3a859f8ccf59897236e3ed99ff7f5a6e923fb1.

If you call `reloadData` more than once, you see the animation flicker still. :(

**Comment by secretiverhyme** [comment] 2015-02-17 22:36
@tanliboy, want to take a look?

**Comment by tanliboy** [comment] 2015-02-18 03:54
@lxcid , could you try to wrap the `reloadData` with `beginUpdate` and `endUpdate` ? 
In the initialization of ASTableView, the `reloadData` will be invoked. To shorten the initialization cost, we make `reloadData` to use batch update by default. Also, you could always group some operations (even not in single runloop) using `beginUpdate` and `endUpdate`.

**Comment by lxcid** [comment] 2015-02-18 11:44
Thanks! Wrapping them between `beginUpdates` and `endUpdates` does help solve the issue.

Should it be documented in the readme for future reference? :)

:+1:

**Comment by tanliboy** [comment] 2015-02-18 17:53
Yeah, it sounds a good idea. I will think about a way to avoid the wrapping firstly. If impossible, I will add it into doc or code comments.

**Comment by lxcid** [comment] 2015-02-26 22:15
On the latest master (9477114c868b658aed39b887766ce6557e25da60), I realise that this issue is back again even with begin/end updates.

Below is a screen capture I done to illustrate the issue on kittens. I make sure that kitten always generate the same data set.

https://www.dropbox.com/s/vmlr18lki7ll1mc/asdk_reload_issue.mp4?dl=0

**Comment by weibel** [comment] 2015-03-25 13:08
This happens to me when the datasource is async. When it is sync everything is good.

**Comment by yiqin** [comment] 2015-05-11 05:47
I have the same issue. How to resolve it?

**Comment by appleguy** [comment] 2015-05-17 09:07
@weibel & @yiqin, sorry for the delayed response here.  As you can see in the PR that references this issue, it should now be resolved.  I have not tested it with asyncDataFetching, but be aware that this feature is known to have some rough edges particularly with code that does a lot of data editing (e.g. multiple edits per runloop, edits during extensive user interaction, etc).  We are investigating these problems, but they are technically separate.

Please do open a new task or PR if you experience any further issues, either this specific pattern or problems with asyncDataFetching.  Any test cases you can provide would be helpful.  Thanks a lot!

**Closed by appleguy** 2015-05-17 09:07 UTC
