### ISSUE TITLE
[ASTextNode] italic text clipping bug

### ISSUE THREAD

**Issue by Yue-Wang-Google** [facebook/AsyncDisplayKit#1999] opened 2016-07-27 23:29 UTC
ASDK render graphic context (which text kit draws on) into a uiimage, and that may cause text to be clipped if it's outside of view's bounds.

For instance, the left side is clipped in the following italic text
<img width="365" alt="screen shot 2016-07-27 at 4 26 31 pm" src="https://cloud.githubusercontent.com/assets/20689178/17196100/fca6eaec-5416-11e6-8534-ed456b0cb30f.png">

**Comment by maicki** [comment] 2016-07-28 17:36
@Yue-Wang-Google On what version are you on? Is it master?

**Comment by Yue-Wang-Google** [comment] 2016-07-28 18:03
The problem appears on all versions. it's on 1.9.8, and on an internal cut dated back from March. 
You can use any word start with italic "j" to reproduce the problem.

It's not a textnode specific problem. It's how ASDK render things internally --- The graphic context will be convert to a UIImage with the same size of the node, from which process it got clipped.

**Comment by garrettmoon** [comment] 2016-08-10 20:40
@Yue-Wang-Google I built a reproduction case and it appears that the UIImage that ASDK generates is the same size (rounded to pixels up) as the size returned by `usedRectForTextContainer:` (called on NSLayoutManager). This is still obviously an issue, just trying to confirm that I'm working on the same bug you're reporting :)

**Comment by garrettmoon** [comment] 2016-08-10 20:41
Specifically, NSLayoutManager is reporting an incorrect size for italicized text.

**Comment by Yue-Wang-Google** [comment] 2016-08-10 20:57
yes. that's the bug I was reporting. 

usedRectForTextContainer: does not do glyph generation. So I assume it can't be used to calculate image bounds, which is different from typographic bounds.

**Comment by garrettmoon** [comment] 2016-08-10 23:27
Got it, thank you. We'll need to figure out another way to generate the image bounds.

**Comment by garrettmoon** [comment] 2016-08-11 17:32
@Yue-Wang-Google the plot thickens: this is the exact same behavior of a UILabel even *with* clipsToBounds set to NO.

![simulator screen shot aug 11 2016 10 30 07 am](https://cloud.githubusercontent.com/assets/90045/17598313/bbb40710-5fae-11e6-91a0-4f7882e9e0bd.png)

Other's appear to attempt to workaround the issue in UILabel: http://stackoverflow.com/questions/20985085/uilabel-clipping-italic-oblique-text-at-left-and-right-edges-of-content-ios

**Comment by nlutsenko** [comment] 2016-08-11 19:06
I bet this is a bug in NSLayoutManager, since this is drawing happening inside of it.
Another one - is the height ascender/descender underestimation where NSLayoutManager actually returns the incorrect height (usually cutoff by half a point), as observable in 637

**Comment by garrettmoon** [comment] 2016-08-11 19:35
This makes me think this #2000 may be necessary. I'll look into that to see if it can address the issue.

**Comment by garrettmoon** [comment] 2016-08-11 19:40
@nlutsenko I'm not sure they perceive it as a bug – I think it's meant to return the sizing of a view for layout and alignment. The actual rendering may exceed its bounds.

**Comment by Adlai-Holler** [comment] 2016-08-16 18:51
Resolved via #2062

**Closed by Adlai-Holler** 2016-08-16 18:51 UTC
Labels: ASTextNode, bug (P2)
