### ISSUE TITLE
[ASTextNode] rectsForTextRange: does not respect textTruncation

### ISSUE THREAD

**Issue by munch1324** [facebook/AsyncDisplayKit#1547] opened 2016-04-18 18:29 UTC
I'm not sure if this is by design (it seems counter-intuitive if that is the case), but the:

- (NSArray<NSValue *> *)rectsForTextRange:(NSRange)textRange;

Does not take truncation into account. I made a toy app that uses the string "testing astextnode" repeated many times with the maximumNumberOfLines = 4. When I scan backwards through the string's range for the first non-zero rect, the result is a string that has been truncated, and is not displayed.

In this case, the range in the string corresponds to 'ode', and I drew a gray rectangle for reference. Ideally, 'ing' should be the first visible range corresponding to the last visible 'testing'

Please let me know if you need any clarfication.

![image](https://cloud.githubusercontent.com/assets/2763971/14614878/fe95a914-0557-11e6-89c0-12f3123fbc63.png)

Toy code (in viewdidload):

```
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  self.view.backgroundColor = [UIColor whiteColor];

  UIView *testView = [UIView new];
  testView.frame = CGRectMake(100, 100, 100, 100);
  testView.backgroundColor = [UIColor lightGrayColor];
  [self.view addSubview:testView];

  NSString *longContentString =
      @"testing astextnode testing astextnode testing astextnode testing astextnode testing "
      @"astextnode testing astextnode testing astextnode testing astextnode testing astextnode "
      @"testing astextnode testing astextnode testing astextnode testing astextnode testing "
      @"astextnode testing astextnode testing astextnode testing astextnode testing astextnode "
      @"testing astextnode testing astextnode";

  ASTextNode *textNode = [ASTextNode new];
  textNode.frame = CGRectMake(200, 200, 100, 100);
  textNode.maximumNumberOfLines = 4;
  textNode.attributedString = [[NSAttributedString alloc] initWithString:longContentString];
  textNode.delegate = self;

  NSUInteger startIndex = longContentString.length - 3;
  while (startIndex > 0) {
    NSRange searchRange = NSMakeRange(startIndex, 3);
    NSArray<NSValue *> *rects = [textNode rectsForTextRange:searchRange];
    CGRect textContents = [[rects firstObject] CGRectValue];
    if (CGRectEqualToRect(textContents, CGRectZero)) {
      startIndex -= 3;
      continue;
    }
    NSLog(@"%@", [longContentString substringWithRange:searchRange]);

    NSLog(@"%@", NSStringFromCGRect(textContents));
    textContents.origin.x += textNode.frame.origin.x;
    textContents.origin.y += textNode.frame.origin.y;
    testView.frame = textContents;
    break;
  }

  [self.view addSubview:textNode.view];
}
```

**Comment by hannahmbanana** [comment] 2016-05-07 08:52
@munch1324: would it be possible to provide a quick sample project?

**Comment by maicki** [comment] 2016-07-18 22:06
@munch1324 I looked into this issue this morning and this actually behaves by design this way. At the time as you try to layout the `testView` and ask for `rectsForTextRange:` the ASTextNode is not visible on screen and layout did not properly happen yet. By moving all of this to `viewDidAppear:` it will give you the result that you expected:

```Objc
@interface ViewController ()
@property (nonatomic, strong) UIView *testView;
@property (nonatomic, strong) ASTextNode *textNode;
@property (nonatomic, copy) NSString *bigContentString;
@end

@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    // Do any additional setup after loading the view, typically from a nib.
    self.view.backgroundColor = [UIColor whiteColor];

    UIView *testView = [UIView new];
    testView.frame = CGRectMake(100, 100, 100, 100);
    testView.backgroundColor = [UIColor lightGrayColor];
    [self.view addSubview:testView];
    _testView = testView;

    _bigContentString =
      @"testing astextnode testing astextnode testing astextnode testing astextnode testing "
      @"astextnode testing astextnode testing astextnode testing astextnode testing astextnode "
      @"testing astextnode testing astextnode testing astextnode testing astextnode testing "
      @"astextnode testing astextnode testing astextnode testing astextnode testing astextnode "
      @"testing astextnode testing astextnode";

    ASTextNode *textNode = [ASTextNode new];
    textNode.maximumNumberOfLines = 4;
    textNode.attributedString = [[NSAttributedString alloc] initWithString:self.bigContentString];
    textNode.frame = CGRectMake(200, 200, 100, 100);
    _textNode = textNode;

    [self.view addSubview:textNode.view];
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    
    NSUInteger startIndex = self.bigContentString.length - 3;
    while (startIndex > 0) {
        NSRange searchRange = NSMakeRange(startIndex, 3);
        NSArray<NSValue *> *rects = [self.textNode rectsForTextRange:searchRange];
        CGRect textContents = [rects.firstObject CGRectValue];
        if (CGRectEqualToRect(textContents, CGRectZero)) {
            startIndex -= 3;
            continue;
        }
        
        NSLog(@"%@", [self.bigContentString substringWithRange:searchRange]);
        
        NSLog(@"%@", NSStringFromCGRect(textContents));
        textContents.origin.x += _textNode.frame.origin.x;
        textContents.origin.y += _textNode.frame.origin.y;
        self.testView.frame = textContents;
        break;
    }

}

@end
```

<img width="204" alt="screen shot 2016-07-18 at 3 04 40 pm" src="https://cloud.githubusercontent.com/assets/25288/16932090/228a666e-4cf9-11e6-9441-824c1edb2a3a.png">

Closing this issue for now please reopen if not fixed.

**Closed by maicki** 2016-07-18 22:06 UTC
Labels: ASTextNode
