### ISSUE TITLE
uitableview crash ?

### ISSUE THREAD

**Issue by MrReN** [facebook/AsyncDisplayKit#192] opened 2014-12-27 07:16 UTC
Cell no reuse, you are not afraid of memory overflow?

**Comment by MrReN** [comment] 2015-01-06 07:45
I'll try tonight, maybe tomorrow can tell you

**Comment by yufenglv** [comment] 2015-01-06 07:50
@rnystrom Hi, I have run into memory issue when using ASTableView.
 [ASImageNode displayWithParameters:]  The memory will continue increase when scrolling the tableview, event just scroll back.

And also, I implement a custom TMTextNode by CoreText. The memory also continues increase. I release the TMTextNodeRenderer when displayDidFinish and  reclaimMemory in TMTextNode. And the TMTextNodeRenderer object is released indeed but the memory still increase.

![2015-01-06 3 36 08](https://cloud.githubusercontent.com/assets/1837609/5625675/6668e5b0-95ba-11e4-811d-7c1c20ccdf0f.png)

![2015-01-06 3 36 24](https://cloud.githubusercontent.com/assets/1837609/5625669/5d50e81a-95ba-11e4-8a8d-23f8c72e5e9a.png)

![2015-01-06 3 36 48](https://cloud.githubusercontent.com/assets/1837609/5625736/8e3307f0-95bb-11e4-8efb-f0dfa473738e.png)

**Comment by MrReN** [comment] 2015-01-07 05:17
@yufenglv If you load a lot of pictures, use ASNetworkImageNode is not very smooth, and slide back and forth, memory has been increased

**Comment by MrReN** [comment] 2015-01-07 06:23
I wrote a similar twitter procedures, if you use ASNetworkImageNode, it causes the sliding is not smooth, I think is the reason occupies a main thread. if you have a lot of pictures and you use the 300 data, then will receive memory warning. What do you think?

**Comment by secretiverhyme** [comment] 2015-01-07 23:05
> if you use ASNetworkImageNode, it causes the sliding is not smooth

Yes — this bug happens with ASBasicImageDownloader because NSURLSession blocks enqueueing network requests on disk I/O, and ASNetworkImageNode enqueues network requests on the main thread (#148).  We'll fix this soon.

> In total 120M,Pictureture only 30M，The rest is cell node

This sounds like a bug that we're not tracking.  Can you upload a sample project that reproduces this excessive memory usage?  Note that memory usage is meant to be bounded by the size of your working range — four screenfuls, by default — so if your content is particularly expensive, you need to shrink your working range on older devices.

**Comment by yufenglv** [comment] 2015-01-08 05:09
Thanks for your answer. 

 And I tried  to use the AsyncDisplayKit on iOS6, I see ASDealloc2MainObject is used to release the object. Does ASDealloc2MainObject work on iOS6 ? 

I write the test code, it works fine on iOS7, but on iOS6,  the TestNode cannot be released. How can I fix this? 
	
	@interface TestNode : ASDisplayNode
	@end
	
	@implementation TestNode
	- (void)dealloc{
	}
	@end

	
	@interface MyStreetCell : UITableViewCell
	{
	    TestNode * _testNode;
	}
	@end
	@implementation TestCell
	
	- (void)configWithData:(TestCard *)data withQueue:(NSOperationQueue *)operationQueue{
	    _testNode = [[TestNode alloc]init];
	    _testNode.frame = self.contentView.frame;
	    _testNode.backgroundColor = [UIColor redColor];
	}
	
	- (void)prepareForReuse{
	    [super prepareForReuse];
	    [_testNode setDisplaySuspended:YES];
	    [_testNode.view removeFromSuperview];
	    _testNode = nil;
	}
	@end

**Comment by MrReN** [comment] 2015-01-08 10:47
I think, if a large number of cell loading, when the sliding a certain position, whether can release before cell, such as 300 cell, when the slide to the 100cell position, the release of 50 cell off before, when the display time reload。Thanks @secretiverhyme  and @rnystrom ，you're greate ,Thanks

**Comment by yufenglv** [comment] 2015-01-08 14:31
Thanks @MrReN @secretiverhyme @rnystrom !
And I try to use ASDisplayKit on iOS6， now I block by a problem. On iOS6, the node will not be released once its view has been loaded. It seems this line - `_view.asyncdisplaykit_node = self;` in `ASDisplayNode.mm` is the reason, how can I fix that? Is there any difference when release the node on iOS6 and iOS7? Thanks a lot!

**Comment by MrReN** [comment] 2015-01-08 16:34
I am a Chinese developers, I wrote a Demo, hope you can connect Chinese network, and test. A memory leak is very serious, I don't know Is it right? Maybe I'm understanding of the Async error, cause or some other reason.exmample:https://github.com/MrReN/_FaceBookTest

**Comment by MrReN** [comment] 2015-01-12 01:18
I solved it，thanks everybody

**Closed** 2015-01-12 01:19 UTC
Labels: discussion

**Comment by rnystrom** [comment] 2015-01-12 03:35
That's awesome @MrReN! Can you let us know what you ended up doing to fix it?

**Comment by Jaiyo** [comment] 2015-01-30 04:38
I have found that in Xcode 6.1.1 iOS 8.1 when running a debug build in the simulator or on a device that in ASBasicImageDownloader -> downloadImageWithURL -> downloadTaskWithURL will never release memory. I've found random posts here and there talking about this. If running a release build this doesn't happen.
