### ISSUE TITLE
Assertion failure in -[ASTableView dataControllerLockDataSource]

### ISSUE THREAD

**Issue by robmontesinos** [facebook/AsyncDisplayKit#772] opened 2015-10-26 00:59 UTC
I'm working on an ASTableView connected to Core Data entities and it has been working great. After adding an attribute to a Core Data entry, I had to delete the app from the Simulator because the Data Object Model had changed - this is normal and expected behavior. What was not expected was an assertion failure - crash - when rebuilding the data model and updating the tableView afterwards with reloadData. If I run the app immediately after crash it works fine, i.e. no assertion failure:
```ObjectiveC
  ASDisplayNodeAssert(!self.asyncDataSourceLocked, @"The data source has already been locked");
```

Essentially what is happening with Core Data is some data i loaded from a pList and then subsequent data is added to the entities from the internet and the tables are reloaded.

It's not clear to me how to accommodate this kind of network operation to reload the ASTableViews, i.e. how to unlock and lock the dataSource. thanks again in advance

**Comment by appleguy** [comment] 2015-10-26 02:51
@robmontesinos if you are calling the lock / unlock methods, try removing those calls.

.asyncDataFetching is currently disabled (even if you pass YES for the parameter).  I would be surprised if this assertion triggers in any case other than imbalanced lock / unlock calls (you should audit your code that calls them to check if you are curious what the root cause is), but deleting them entirely should resolve it.

Please come update the task & close it when you can confirm.  Thanks!

**Comment by robmontesinos** [comment] 2015-10-26 04:26
I'm not  calling lock and unlock. The crash only happens when I delete the app from the simulator, i.e. first build, when the Core Data entities are being built. The method causing the assertion failure is [ASTableViewName reloadData] which happens after the data is downloaded, the entity attributes are updated and then reloadData is called to show the new values from Core Data on the table.

```ObjectiveC
- (void)reloadTableViews {
    _dataList = nil;
    
    [self.tableView reloadData];
}


```

**Comment by appleguy** [comment] 2015-10-26 04:45
@robmontesinos can you share more information, such as at least the full stack trace when the assertion fires?

Are you certain you are not calling the reloadData on a background context owned by Core Data?  How about calling any table view methods from a network callback that may also not be on the main thread?

**Comment by appleguy** [comment] 2015-10-26 04:45
(I ask because we have never seen a report like this, but multithreading issues could certainly cause it)

**Comment by robmontesinos** [comment] 2015-10-26 18:47
Thanks @appleguy !!

2015-10-26 11:39:37.076 APPNAME[2116:28093] *** Assertion failure in -[MyASTableView dataControllerLockDataSource], /Users/xxxxxxxxxxxxxx/Pods/AsyncDisplayKit/AsyncDisplayKit/ASTableView.mm:837
2015-10-26 11:39:37.160 APPNAME[2116:28093] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The data source has already been locked'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a6c4c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010a35dbb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010a6c4aca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010789e98f -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   APPNAME                          0x0000000105921a41 -[ASTableView dataControllerLockDataSource] + 273
	5   APPNAME                          0x000000010588b0ea -[ASDataController accessDataSourceWithBlock:] + 426
	6   APPNAME                          0x000000010588a227 __62-[ASDataController reloadDataWithAnimationOptions:completion:]_block_invoke + 615
	7   APPNAME                          0x000000010588c6fd -[ASDataController performEditCommandWithBlock:] + 77
	8   APPNAME                          0x0000000105889f39 -[ASDataController reloadDataWithAnimationOptions:completion:] + 201
	9   APPNAME                          0x000000010591a37d -[ASTableView reloadDataWithCompletion:] + 621
	10  APPNAME                          0x000000010591a4cf -[ASTableView reloadData] + 47
	11  APPNAME                          0x00000001057820fc -[MainPagingViewController reloadTableViews] + 172
	12  APPNAME                          0x000000010578242a -[MainPagingViewController didUpdateUsers] + 234
	13  CoreFoundation                      0x000000010a69454c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	14  CoreFoundation                      0x000000010a592a04 _CFXNotificationPost + 2484
	15  Foundation                          0x00000001077e0968 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	16  APPNAME                          0x000000010581008d +[CoreDataHelper saveUsersThenNotify] + 125
	17  APPNAME                          0x000000010574c1aa __45-[UserClient loadUser:forLastUser:]_block_invoke + 2106
	18  libdispatch.dylib                   0x000000010b2a1186 _dispatch_call_block_and_release + 12
	19  libdispatch.dylib                   0x000000010b2c0614 _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x000000010b2a8a1c _dispatch_main_queue_callback_4CF + 1664
	21  CoreFoundation                      0x000000010a62c1f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	22  CoreFoundation                      0x000000010a5eddcb __CFRunLoopRun + 2043
	23  CoreFoundation                      0x000000010a5ed366 CFRunLoopRunSpecific + 470
	24  GraphicsServices                    0x000000010b777a3e GSEventRunModal + 161
	25  UIKit                               0x00000001088768c0 UIApplicationMain + 1282
	26  DeezTweetz                          0x000000010581447f main + 111
	27  libdyld.dylib                       0x000000010b2f4145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by appleguy** [comment] 2015-10-27 05:09
@levi, @nguyenhuy, @eanagel - hate to bug you guys, but this looks like code that may have changed recently in ASDataController; can you take a quick look and comment if you recognize a possible fault here?

I vaguely recall seeing some code that did call lock on the datasource added recently.  I let it go through review because it would be nice to continue supporting asyncDataFetching even though it's currently disabled, because I plan to re-enable it soon after a round of refactoring.  However, I may not get to this right away, so I would be supportive if anyone wants to entirely remove data source locking.

Indeed, the time to remove it would be before 2.0, as we can make breaking API changes.  We can always re-add it later.

**Comment by levi** [comment] 2015-10-27 15:50
I'll check this out today, Scott. Moreover, what are the current issues with asyncDataFetching that prevent it from being enabled within the framework?

**Comment by levi** [comment] 2015-10-27 16:41
@robmontesinos I'm having a hard time locating an inconstancy in ASDataController or ASTableView that could be causing this issue. `asyncDataSourceLocked` is set internally in ASTableView on initial lock, so it looks like you call to `reloadData` is not the original. Could you set a breakpoint on ASTableView's `dataControllerLockDataSource` and see what's initially setting it? Putting up an example project would be even better!

**Comment by robmontesinos** [comment] 2015-10-27 18:56
@levi Thanks for looking into this. I will get on it tonight and see what I can do. Salud!

**Comment by robmontesinos** [comment] 2015-10-28 01:50
@levi I reset the Simulator so that the Core Data Object Model would have to be rebuilt - I set a breakpoint on dataControllerLockDataSource and ran it.

On initial load:
[tableView reloadData] call finds self.asyncDataSourceLocked = NO;

After the user logs in, data is received from server, Core Data Entity is updated and table is refreshed via another [tableView reloadData] from a completion block where self.asyncDataSourceLocked = YES;

We get *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The data source has already been locked'

I'm going to try calling reloadData on main thread from completion block to see what happens

**Comment by levi** [comment] 2015-10-28 01:58
Roberto, sounds like that is might be coming from the fact the first reloadData hasn't completed by the time the second one is called. You should check if the first call does indeed lock the data source after it is complete. If not, that is most likely you're issue.

**Comment by robmontesinos** [comment] 2015-10-28 02:05
@levi In my case, the first reloadData is definitely completed by the time the second one is called because the second one doesn't get called until there has been a successful login on Twitter. The second reloadData is being called to refresh the entities with account specific stuff like images and follower count. Is it possible that unlock data source is not being called? Lock data source is certainly being called.

I have these methods on the View Controller that I just copied in from Kittens - could they be the culprits?

```ObjectiveC
#pragma mark - ASTableView

- (void)tableViewLockDataSource:(ASTableView *)tableView {
    self.dataSourceLocked = YES;
}

- (void)tableViewUnlockDataSource:(ASTableView *)tableView {
    self.dataSourceLocked = NO;
}

**Comment by robmontesinos** [comment] 2015-10-28 02:06
Is it possible to leave the dataSource unlocked? I'm not sure what the benefit is of locking and unlocking.

**Comment by robmontesinos** [comment] 2015-10-28 02:49
I tried this with no luck:

```ObjectiveC
        [tableView.asyncDataSource tableViewUnlockDataSource:tableView];
        [tableView reloadData];
        [tableView.asyncDataSource tableViewLockDataSource:tableView];

**Comment by robmontesinos** [comment] 2015-10-28 03:10
This did the trick but it has me a little worried - ASTableView.mm

```ObjectiveC
- (void)dataControllerLockDataSource
{
//  ASDisplayNodeAssert(!self.asyncDataSourceLocked, @"The data source has already been locked");

  self.asyncDataSourceLocked = YES;

  if ([_asyncDataSource respondsToSelector:@selector(tableViewLockDataSource:)]) {
    [_asyncDataSource tableViewLockDataSource:self];
  }
}

- (void)dataControllerUnlockDataSource
{
//  ASDisplayNodeAssert(self.asyncDataSourceLocked, @"The data source has already been unlocked");

  self.asyncDataSourceLocked = NO;

  if ([_asyncDataSource respondsToSelector:@selector(tableViewUnlockDataSource:)]) {
    [_asyncDataSource tableViewUnlockDataSource:self];
  }
}

**Comment by appleguy** [comment] 2015-11-08 05:04
@robmontesinos sorry for the late reply.  To your earlier comment about if it is possible to leave the data source unlocked — yes, absolutely, it should not require locking in normal use cases.  I think I mentioned this before.  Please reopen this task if you can provide a reproduction case for where the framework is actually crashing here, without a single call in the app to lock / unlock the data source.

**Closed by appleguy** 2015-11-08 05:04 UTC

**Comment by robmontesinos** [comment] 2015-11-08 19:17
@appleguy Thank you sir!
