### ISSUE TITLE
[Issue in 1.9]ASCellNode content will disappear if one of the cells height is larger than table frame height

### ISSUE THREAD

**Issue by yxztj** [facebook/AsyncDisplayKit#815] opened 2015-11-04 08:53 UTC
Hi,

Repro steps:
1. Create an ASTableView with some data.
2. Insert rows at top. One of the row size is larger than the tableview frame
3. Scroll to bottom.
Some of the cell's content would go away one by one.

I've created a repo for this issue(https://github.com/yxztj/ASDK2CellIssue):
1. Run the test app. You would see some test data.
2. Tap on any cell. The table would insert 3 rows of test data at top.
3. Scroll to bottom, cell data disappears one by one.
But if I call tableView.reloadData other than insertRowsAtIndexPaths, everything is fine.

The issue appeared after I upgraded ASDK from 1.2.3 to 1.9.

**Comment by vitalybaev** [comment] 2015-11-04 11:40
Maybe simillar with #686

**Comment by nguyenhuy** [comment] 2015-11-04 14:28
Thanks for reporting this, @yxztj and @vitalybaev.

I believe this issue is caused by #642. Reverting the commit in that PR fixes the problem. cc @appleguy 

@vitalybaev Sorry for not answering your issue. Could you please try to confirm that #642 is to be blamed?

**Comment by vitalybaev** [comment] 2015-11-04 14:59
@nguyenhuy I don't remember, which version exactly was at that time. It's a :git :master in ```Podfile``` for a long time. Now I can't set old commit to check it, cause a lot of new APIs now in my project.

I can test @yxztj 's sample project.

**Comment by vitalybaev** [comment] 2015-11-04 15:05
@nguyenhuy yep, you are right! reverting #642 fixes the problem

**Comment by nguyenhuy** [comment] 2015-11-04 15:08
@vitalybaev Thanks for the heads up. #642 was merged 2 weeks before your issue reported. I tested @yxztj's project with and without #642. Waiting for @appleguy since I'm not really familiar with the render  range handler and its working window.

**Comment by vitalybaev** [comment] 2015-11-04 15:11
@nguyenhuy You're welcome! 
It's great that you are take a look at this issue, cause I'm confronted with it again today in my project.
Thanks!

**Comment by yxztj** [comment] 2015-11-05 05:12
@vitalybaev @nguyenhuy Thanks for the investigation.
Hope the issue would be resolved soon since our users are losing their tableView cells. :(

**Comment by appleguy** [comment] 2015-11-05 06:59
Thanks a lot for the reproduction case!  That should speed the fix.

Unfortunately I have an absolutely packed workday Thursday and Friday, but in the event that I can't get through my email and on to ASDK fixes in the evening of one of the days, I will definitely investigate on Saturday and should have a fix before the weekend is out.  I'll roll a 1.9.1 for this issue.

Any other nominations for 1.9.1 issues?

**Comment by vitalybaev** [comment] 2015-11-05 17:22
@appleguy yep, today I realized that my PR #745 witch provides selected/highlighted properties to ASCellNode not working.

setHighlighted never YES and #807 looks strange too.

Tomorrow I'll take look deeper into it.

**Comment by yxztj** [comment] 2015-11-06 01:48
@appleguy Thanks so much!

**Comment by appleguy** [comment] 2015-11-07 00:07
@vitalybaev let me know what you find regarding setSelected / setHighlighted.  It does seem like that behavior is not working correctly in this test app and I would like to include a fix in this weekend's 1.9.1 release.

**Comment by appleguy** [comment] 2015-11-07 07:18
@yxztj I was able to reproduce and am working on the problem.  My first approach is the most complex and would actually entirely eliminate the workingWindow, which would be a big optimization I have wanted to do for over a year but haven't had time.  Wish me luck, as if I don't make enough progress tomorrow then I'll switch to looking for q more targeted fix.

**Comment by appleguy** [comment] 2015-11-08 07:13
@yxztj I have a fix up here: https://github.com/facebook/AsyncDisplayKit/pull/826  I would not have been able to fix this without your test app, so thank you - really - for taking the time to provide one.

I'll plan to release a 1.9.1 later tomorrow, or if some other important fixes come up, on Wednesday this coming week.  Feel free to point your project at master in the meantime to benefit from the fix (or apply it locally, since it is very small).

**Closed** 2015-11-08 07:13 UTC
Labels: bug

**Comment by yxztj** [comment] 2015-11-09 03:13
@appleguy Thanks so much for the quick fix! I'll point to master to get it.
Now we could freely benefit all the great stuff of ASDK2.0. :)

**Comment by appleguy** [comment] 2015-11-09 03:51
@yxztj so glad!  looking forward to more feedback from you — both questions and suggestions!  I'm going to try to launch 1.9.1 tonight from current master, so that might help.
