### ISSUE TITLE
[ASRangeController] Support "setNeedsDataFetch" or similar to enable efficiently reloading images.

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#844] opened 2015-11-13 03:24 UTC
Still loving this framework! Sorry I haven't been contributing lately, I'm drowning in work after our first release. I have been lurking though!

So I'm using `ASCellNode` in kind of a weird way. I've got really complex content, so I create the entire collection of nodes upfront, and then keep them up-to-date with my model by listening for `NSManagedObjectContextObjectsDidChangeNotification` on a background context. If I added or removed nodes, I inform the table view.

Trouble is, when I update `ASMultiplexImageNode.imageIdentifiers`, nothing happens until someone next calls `fetchData`. This is normally the range controller. But if the cell node is already in the loading range, then `fetchData` won't get called again. If I call `fetchData` every time I set `imageIdentifiers`, though, I may end up loading images for cells that are far out of the working range.

Any advice?

**Comment by appleguy** [comment] 2015-11-14 01:41
@Adlai-Holler I'm halfway glad you ran into this issue, because I am planning a fix for this very weekend.  This is a somewhat tough problem, but my plan is to ensure that each node has a query-able state that indicates its presence or absence from the Network range, Render range, and the brand new Visible range.  Later, I'm going to add an Allocation + Measurement range (long story on why they have to be the same range), but that's a far bigger change for a few reasons.

This is in part associated with my focus on eliminating the "working window".  Anyway, we'll probably need some new API like "setNeedsDataFetch", which if called when outside the network range, simply queues for the next time it's entered - or is handled immediately if inside the range currently.

Any other challenges you're running into?  The API design considerations around this are unfortunately maddening, and I have decided that in order to be able to make progress I'm first going to build some of this stuff as internal-only as it may evolve once other interdependent parts are fleshed out.  But anyway, it would be no problem at all for ASMultiplexImageNode to have framework-internal knowledge of this state and be able to automatically issue new fetches as appropriate.

Lastly though I'd mention you may consider just destroying the node(s) and recreating them, relying on a good image cache to work correctly.  I think after a couple more months, we will have really good support for very-long-lived nodes (those that change a lot as they're interacted with, etc), with features like animating between ASLayoutSpecs, but today it is a little inconvenient to achieve some of those implementations (almost anything is possible with today's ASDK, as long as you're willing to get manual enough...so that's what I'm aiming to fix).

Would love to meet up with you soon in the city if you're interested.  Your feedback on this stuff would be really valuable to shaping the direction of the project.  Looking towards December and early next year, Pinterest contributions will slowly (at first) start going up and we should be at a pretty good clip by February to continue the really structural improvements.

**Comment by Adlai-Holler** [comment] 2015-11-14 04:16
@appleguy Excellent! I'm really glad you were looking at this feature already.

Other issues I'm facing: 
- Node thread affinity is the biggest one for my oddball use case, since I keep my nodes alive a while. I made a client-side version of `ASDisplayNodeRespectThreadAffinityOfNode` but since I can't lock the properties, sometimes the node gets loaded mid-block and now it's crash time. Maybe publicize that function as a stop-gap until the new threading model is in?
- Better support for animated scrolling. I've got a table view with a bunch of content, and sometimes we want to scroll the user down to a certain spot. But that range may not be loaded and there's currently no way to request it. In our case it's particularly bad, since we have a screen-sized `tableHeaderView` that acts like a cover for the feed, and so literally 0 nodes are loaded since `tableView:willDisplayNode:` hasn't been called yet.
- It doesn't make toast. Big problem!

Destroying & recreating nodes: I'm worried about the performance implications here. Nodes are cheap, but right now I'm using a functional-style data source where I recompute all my data, using a find-or-create system for nodes. Then I diff the resulting hierarchy and report the row inserts/deletes to the table view. In order to have this much freedom while keeping the table view involvement minimal _and_ not reusing nodes, I'll need to remember which nodes can stay and which have to be thrown out. 

Meet up: Yeah, let's! Email sent.

**Comment by appleguy** [comment] 2015-11-14 05:05
@Adlai-Holler I'm happy to merge in some custom facilities for you, especially if they are out of the way in a more buried header (we might create an ASDisplayNode+Experimental.h or similar).  Go wild!  I would like to better understand your use case that is hitting thread affinity so that I can confirm or deny if my current plan to address that will be both sufficient and elegant.  Your instinct to workaround is correct, though, as I am running behind due to a combination of work / family factors.  So it could take a couple more months for my current plan to address affinity to be landed, although it is actually not a difficult change and could probably be done in less than a single day.

I can understand the fear of costs, but would be happy to share my blend of iOS performance intuition and measurement from past projects.  I'm pretty confident we can solve even the most aggressively challenging performance problems (iPhone 4) without node recreation being the main issue.  In fact, enabling usage of layer-backing or shouldRasterizeDescendents would be even more impactful by far, because you eventually have to create a node's view otherwise - which even if you're reusing it, is costly.  Even if you can't currently use those features because you depend on views' event handling, there are workarounds to this by delivering basic events through the node hierarchy.

The range current state stuff is related to the need / desire for big refactors to ASRangeController, and I want those to enable 1) virtualization of data so that the AS classes don't /have/ to perform layout / measurement on everything in the asyncDataSource, AKA the allocation + measurement range; 2) simultaneously, would be trivial to support "block until measured" for something like "scroll to indexPath" - then finishing up the measurement to that point, update the underlying UIKit component, and issue the command.

2) in fact would be fairly easy to do today, with some careful changes to ASDataController, but if you have some other workaround to this then it's probably reasonable.  You could definitely use a synchronous reloadDataImmediately, which waits on the concurrent completion of all measurement, and would thus provide better performance than UITableView while still ensuring all rows are available to animate to from the start.  If you also enable neverShowPlaceholders on the ASCellNodes, you can trade framerate for full content display.

**Comment by appleguy** [comment] 2015-11-16 06:57
@Adlai-Holler ok, I did make really important progress on this over the weekend, but a mid-level family emergency has come up and prevented me from finishing.  No worries, I will not get my priorities wrong in this case - family is always first.

Basically I have a new API designed, ASInterfaceState, which is an NS_OPTIONS bitfield type and will be provided on at least ASDisplayNode as well as ASViewController.  I have a slew of integrations / improvements planned as well.  The upshot is that even after the first diff before the followups, it should be trivial for the implementation of the network / multiplex node to check whether its _interfaceState includes "ASInterfaceStateFetchData", and it will trigger a download if so.  In the short term I'm going to keep the -fetchData and -clearFetchedData methods, but they will now be called as part of setInterfaceState: rather than directly from the range handler - and a savvy implementer could override setInterfaceState: to do custom logic, as long as super is called.

Let me know if you have any specific ideas or other things the project can do to enable your current product to succeed.  Enthusiastically rooting for your success!

**Closed** 2016-01-28 04:06 UTC
Labels: discussion, feature — core
