### ISSUE TITLE
ASCollectionView reloadRowsAtIndexPaths version 1.2.2 has problem

### ISSUE THREAD

**Issue by tuantavan** [facebook/AsyncDisplayKit#574] opened 2015-07-17 12:18 UTC
Hello,
 I'm using AsyncDisplayKit Lib version 1.2.2 for my chatting application. There have a problem as detail: 
    + Step1: When a user sends a message (photo or text), I will add this message into ASCollectionView as temporary, and scrollToBottom (so that user can see what did he send at the bottom of the ASCollectionView).
    + Step2: When I received a response status (succeeded / failed) from server and I need to reload this message to update status (hide loading / show error icon...). I used [reloadRowsAtIndexPaths] method to reload. However, my collection was scrolled down (I didn't see my last message), a new message was inserted(but I must scroll up to see it). --> It's not good. In version 1.2, this behaviour DOESN'T happen.

Could you suggest a solution to fix this? (I wan't to keep as version 1.2), please?
Thanks a lot!

**Comment by appleguy** [comment] 2015-07-18 21:15
@tuantavan thanks for reporting this.  I read your report a few times, but am not completely certain the scenario / symptoms you are describing.  Would you be able to try describing it again, perhaps including 2 or 3 screenshots (or much better yet — a screen capture video, which QuickTime X can do for free with the simulator)?

We are currently working on this area, as you can see with the open pull request from @eanagel there is some work to build in better support for adjusting scroll position when changing the data source.  You may need to use the endUpdatesAnimated:completion: method he added.  The completion is necessary for your case, because even after you do an insert or a reload, there is a short asynchronous delay before you can do the scrolling command; otherwise the cell will not have been asynchronously sized and added to the table.  This is very likely at the root of your issue.

I'll work hard to make sure that what you would like to do is as easy as possible, if you're able to provide more descriptive detail.  Of course, a test case that allows reproducing the problem in isolation is the best way to get this fixed quickly.

One side tip: messaging apps often find it useful to flip the table / collection view upside down (transform the entire thing), and then flip each of the cells upside down (also transform them) so the content still shows right-side-up.  What this accomplishes is more efficient loading and an easier time staying at the "bottom" / most current messages (assuming they get added at the bottom as new messages come in, and you usually want the focus to stay there).  I'm not totally sure, but I think this is how @nguyenhuy 's project (AsyncMessagesViewController — ASDK based messaging) is implemented.

**Comment by AgeOfMobile** [comment] 2015-07-20 00:36
@appleguy The issue is ASCollectionView won't keep its scroll position after calling reloadItemsAtIndexPaths to reload the last item (no layout changed). It will scroll back to the item before the last one.

**Comment by tuantavan** [comment] 2015-07-20 04:21
@appleguy : Thanks for your helping. I recorded a short video of my current app. Please visit the video:
+ AsyncDisplayKit 1.2.2 : https://www.youtube.com/watch?v=S3LmPKHYmKo

Thanks a lot for your helping!

**Comment by nguyenhuy** [comment] 2015-07-20 14:28
@appleguy Thanks for mentioning my library :+1: Flipping the entire table/collection view is a very interesting and helpful tip! In my current chat apps, I do have hard time writing UI code to accomplish a (relatively) well-behaved messages list (and so does [JSQMessagesViewController](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/JSQMessagesViewController/Controllers/JSQMessagesViewController.m#L359)). Although I took a hint about this trick from [SlackTextViewController](https://github.com/slackhq/SlackTextViewController#inverted-mode) (and I reckon Slack apps use it internally), I didn't realize its potential and thus, didn't employ it in AsyncMessagesViewController. Will definitely implement it when time permits :)

@tuantavan in my library, I use a completion block that will scroll the collection view to the bottom whenever a new message is inserted. I would do the same for reloads.

@AgeOfMobile I think the current approach to reload is fine, in the sense that a "reload" implies that the old node itself is invalid and should be replaced by a totally new node. If only the node's layout is invalid, what you need is a "relayout", and we are working on this feature :)

**Comment by AgeOfMobile** [comment] 2015-07-21 05:55
@nguyenhuy Thanks for your comments. For now, we fixed the problem by applying #564 fix of @eanagel, then manually maintain the contentOffset of ASCollectionView. 

Hope that @eanagel fixes (#575) pass all test cases and merged to the next release.

**Comment by tuantavan** [comment] 2015-07-21 07:23
Finally, we fixed this problem by applying #564 , #575 .
@appleguy, @nguyenhuy , @eanagel , @AgeOfMobile : Thanks a lot for your helping!

**Comment by appleguy** [comment] 2015-07-25 20:52
@tuantavan greatly appreciate you filing the issue, /and/ following up by testing the fixes!  This one was a little tricky, but we're finally getting to a really great place in the framework with these complex components.  Soon we will be moving on to even more advanced functionality.

Look for 1.2.3 to come out in the next couple days with these fixes.

**Closed by appleguy** 2015-07-25 20:52 UTC
