### ISSUE TITLE
[Apple Bug] TextKit's calculatedSize is not matching NSAttributedString for CJK languages.

### ISSUE THREAD

**Issue by binchensjtu** [facebook/AsyncDisplayKit#1013] opened 2015-12-29 14:37 UTC
I found that the height of calculatedSize in ASTextNode is incorrect for Chinese and Japanese.
The test code snippet as below:

``` objective-c
NSString *text = @"你好";//Some Chinese characters
NSDictionary *attributes = @{NSFontAttributeName: [UIFont systemFontOfSize:17.0]};
ASTextNode *textNode = [[ASTextNode alloc] init];
textNode.attributedString = [[NSAttributedString alloc] initWithString:text attributes:attributes];

CGSize textSize1 = [textNode measure:constrainedSize];
CGSize textSize2 = [text sizeWithAttributes:attributes];

NSLog(@"textSize1: %@", NSStringFromCGSize(textSize1));
NSLog(@"textSize2: %@", NSStringFromCGSize(textSize2));
```

The output is:

```
textSize1: {34, 17}
textSize2: {34, 20.287109375}
```

Pure Chinese characters will lead to the issue. The bounds of text node is tight. The mix of Chinese and alphabets is correct.
The same problem to pure Japanese characters. Haven't test more languages.

The screenshot of pure Chinese character text node and mix character text node.

<img width="192" alt="textnode" src="https://cloud.githubusercontent.com/assets/2069820/12035960/8bba223a-ae7c-11e5-9d49-6aec4b79d437.png">

**Comment by appleguy** [comment] 2015-12-29 22:02
@binchensjtu Thank you for reporting this!  Support for the languages of the world has been a top motivator for me since the first prototypes of AsyncDisplayKit, because many languages take more computational effort to perform layout as well as rasterization than the English-biased developers frequently building iOS frameworks.  A few questions:

- Have you replicated this test with UILabel, UITextField, or UITextView?  How about the older NSString-based sizing methods that pass in a font directly?
- Have you tried using CoreText or TextKit directly, which are what ASTextNode is built on?
- Do you have a set of recommendations or test cases for how I could verify what behavior is correct / expected?  Do you feel that the sizing behavior of NSAttributedString itself is consistently correct?

@ocrickard - I promise not to invoke you on every text issue we run across (you may be surprised that I've fixed several recently and am becoming increasingly comfortable with the rendering code that was previously opaque to me).  However, I have to ask: has anything like this (let's say CJK languages in general) been studied, or issues reported, with ComponentKit?

@rcancro, @nguyenhuy - I know you guys have at least some additional expertise here beyond my own, and you may know native CJK speakers who have used TextKit / Core Text in detail and could help us audit the behavior.  Let me know.

**Comment by ocrickard** [comment] 2015-12-29 22:15
Hmm, clipping is always an issue sadly. We created a size estimation method for ASDK that I brought over to ComponentKit and I don't think I touched it in the refactor, so it would be interesting to know if this reproed before the refactor was ported. 

There will be differences between NSStringDrawing categories and TextKit. NSStringDrawing internally still uses an RTF engine that I believe is fairly different from TextKit, and is *substantially* slower for complex strings. If we can try TextKit directly as you're suggesting that would be great.

**Comment by ocrickard** [comment] 2015-12-29 22:17
As for if we've had issues reported, I think I saw one fly by recently, so we likely have the same woes. We marked it up to an apple bug until we saw evidence to the contrary.

**Comment by binchensjtu** [comment] 2015-12-30 04:50
@appleguy Thanks for fast reply in your holiday! I never notice this problem when using basic apple text widget. I test it today. Including CoreText.
```objective-c
  NSString *text = @"你好";
  UIFont *font = [UIFont systemFontOfSize:17.0];
  NSDictionary *attributes = @{NSFontAttributeName: font };
  
  NSAttributedString *attributedString = [[NSAttributedString alloc] initWithString:text attributes:attributes];

  _label = [[UILabel alloc] init];
  _label.font = font;
  _label.text = text;
  NSLog(@"label plain text size %@", NSStringFromCGSize([_label sizeThatFits:CGSizeMake(FLT_MAX, FLT_MAX)]));

  _textView = [[UITextView alloc] init];
  _textView.font = font;
  _textView.text = text;
  _textView.textContainer.lineFragmentPadding = 0;
  _textView.textContainerInset = UIEdgeInsetsZero;
  NSLog(@"text view plain text size %@", NSStringFromCGSize([_textView sizeThatFits:CGSizeMake(FLT_MAX, FLT_MAX)]));

  _textField = [[UITextField alloc] init];
  _textField.font = font;
  _textField.text = text;
  NSLog(@"text field plain text size %@", NSStringFromCGSize([_textField sizeThatFits:CGSizeMake(FLT_MAX, FLT_MAX)]));
  
  CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)attributedString);
  CGSize coreTextSize = CTFramesetterSuggestFrameSizeWithConstraints(framesetter, CFRangeMake(0,0), nil, CGSizeMake(CGFLOAT_MAX, CGFLOAT_MAX), nil);
  NSLog(@"core text size %@", NSStringFromCGSize(coreTextSize));
```

output is
```
label plain text size {34, 20.5}
text view plain text size {34, 20.5}
text field plain text size {38, 21}
core text size {34, 17}
```

I believe some padding in text filed so the width is larger. You're right. The CoreText result is the same as ASTextNode. I didn't deep dive in basic text widgets. Do you know the calculation detail of these basic widgets?

Actually I would like to have stable calculation result while using pure CJK and English-CJK-Mix. Because these two situation are common in non-English-language market. The stable height make UI designer happy :smiley: . What I want is the sizing behavior of NSAttributedString. Do you guys have any idea to workaround this or "fix" this?

**Comment by ocrickard** [comment] 2015-12-30 05:13
Yeah, this is a long-standing problem. I believe that Apple's text sizing methods in NSStringDrawing categories use RTF string drawing engine I mentioned and/or add padding. It may be possible to come up with a more stable fix for this if someone sat down for a couple days and messed with the sizing routines we have... We built those from trial and error over about two weeks in the development of Paper and we didn't revisit them much since.

**Comment by ocrickard** [comment] 2015-12-30 05:14
Alternatively a "fix" for you could be to add padding to your nodes to avoid the clip until we can get this fixed.

**Comment by binchensjtu** [comment] 2015-12-30 05:22
Thanks @ocrickard 
I believe this problem is some kind of relative to font. Since iOS9, the system default font for Chinese is PingFang. I explicit use ```[UIFont fontWithName:@"Helvetica" size:17.0]```. The calculation of pure CJK and English-CJK-Mix are the same using ASTextNode and CoreText in iOS9.2. Even though it is still different from apple's NSStringDrawing categories.

**Comment by ocrickard** [comment] 2015-12-30 05:33
Oh yeah definitely there's a mismatch somewhere between the font glyph tables and the TextKit/CoreText drawing engine, we've seen this in different manifestations for a long time. Here's where we calculate the size of the context, it uses pure TextKit sizing methods, feel free to play with it and see if you can improve it:

https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/TextKit/ASTextKitRenderer.mm#L95

**Comment by ocrickard** [comment] 2015-12-30 05:34
I believe @bcunning recently dealt with clipping in ASTextNode for arabic recently. Do you have any insights or suggestions?

**Comment by ocrickard** [comment] 2015-12-30 05:37
Also @appleguy btw while I'm looking at some of this code https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTextNode.mm#L418 is incorrect. @bcunning and I recently ran into it. It should just be filling the clipping bounds of the CGContext. So:
```
CGContextFillRect(context, CGContextGetClipBoundingBox(context));
```

**Comment by appleguy** [comment] 2015-12-31 09:49
@ocrickard thanks for bringing in the know-how! :-D  I'll fix that rect fill issue.

@binchensjtu Have you tried AsyncDisplayKit's behavior on 1.9.2 as well as the more recent versions?  I'm just curious if any of the changes to the text rendering engine that landed in 1.9.3 would affect this, but it does look like the story may end more sadly...if the bug is ultimately Apple's, it will be harder for us to work around in a way that doesn't cause problems if they fix the bug.  However, I'm very interested in considering any ideas for a workaround, such as comparing sizes to known-correct ones before adding padding.  We'd need to be able to very efficiently detect the cases that need adjustment, though, and I fear that might be impossible.

**Comment by binchensjtu** [comment] 2016-01-01 06:48
@appleguy Yes. I use ASDK since 1.2.*. I check out back to 1.2.3 and try CJK again. The same behavior as 1.9.3. The TextKit rendering engine has no effect on this issue. 

Yes. Sadly. Now it is hard for us to work around this problem. I event don't know what is known-correct rules of glyphs for CJK. Maybe I had to just consider the work around for my case. Thanks for all of you guys!

**Comment by Wang-Yue** [comment] 2016-01-07 00:20
To me it's not a bug at all. That's an expected behavior. 
you are mixing CJK (height=17) with a larger height English char (height = 20). 
So whenever he's using CJK only, height should be 17
when you are mixing both language characters, height should be 20 in order to fit english text
So to me both AsyncDisplayKit and Apple are doing the right thing.

you can try "你好p" and you'll find the descent of p is lower than CJK chars. That's the 3px more height are for.

**Comment by Wang-Yue** [comment] 2016-01-07 01:15
I think this is the expect result if you are using CTFramesetterSuggestFrameSizeWithConstraints. For your case, you may need to iterate over the lines, and use CTLineGetTypographicBounds. Then you can always get consistent bounding boxes.

**Comment by garrettmoon** [comment] 2016-11-14 21:23
I don't think we're going to be able to get this one in for 2.0, moving to 2.1

**Comment by yxztj** [comment] 2017-01-13 02:01
@appleguy @garrettmoon @hannahmbanana #2894 could be related, and I found a quick fix for that.

**Comment by yxztj** [comment] 2017-02-16 01:56
@hannahmbanana #3026 should be fixing this issue(which should be the same as #2894)

**Comment by garrettmoon** [comment] 2017-02-16 19:04
@yxztj Thank you so much!

**Closed by garrettmoon** 2017-02-16 19:04 UTC
Labels: Blocked on Apple
