### ISSUE TITLE
(Question) Retrieve node from Collection View

### ISSUE THREAD

**Issue by blessingLopes** [facebook/AsyncDisplayKit#297] opened 2015-02-08 18:28 UTC
Hi guys! Sorry for the newbie question.
Been trying to set up an ASCollectionView  in swift. So far all's good, but I can't seem to find away to get a Node from the collection view.
With a regular collectionView I could use something like:
let cellTapped = collectionView.cellForItemAtIndexPath( cellPath! ) as? MyCell

I get an error if I use:
 let cellTapped = collectionView.nodeForItemAtIndexPath( cellPath! ) 
error: "ASCollectionView does not have a member named nodeForItemAtIndexPath "

Please, What am I doing wrong??

**Comment by kylehickinson** [comment] 2015-02-08 18:56
The method you're looking for was added in [this commit](https://github.com/facebook/AsyncDisplayKit/commit/94cd7858700584dd6a4e1e307df9c2ed65a0ab44) 13 days ago, but the latest pod release ([1.1.1](https://github.com/facebook/AsyncDisplayKit/releases/tag/1.1.1)) was 25 days ago.  So you can either wait until the next release or update your podfile to pull from HEAD and always work with the latest updates :)

**Comment by blessingLopes** [comment] 2015-02-08 19:02
@kylehickinson  Oh! thank you so much! I'll give the update a try.

**Comment by secretiverhyme** [comment] 2015-02-08 20:50
Bingo.  This method will be included in the upcoming 1.2 release, probably in a week or so.  =]

**Comment by blessingLopes** [comment] 2015-02-08 22:11
@secretiverhyme @kylehickinson 
You guys are the best!  Thanks!  I pulled in the latest update and it's working like a charm! 
Been testing it on an iPhone 5 and its really impressive how smooth the scrolling is now, was even able to apply a transform on each ASCeelNode for a custom animation when the device rotates. :dancer: 
I was feeling lucky so i tried a collectionView with 30000 images. It took 50s to load the app. Any tips on an elegant way around this kind of issue ?

**Comment by kylehickinson** [comment] 2015-02-08 22:56
Are you attempting to load the image to display when the cell is allocated? If you are you should consider moving that to `willEnterHierarchy` and dump the image at `didExitHierarchy` (or use the `willDisplayNodeForRowAtIndexPath`/`didEndDisplayingNodeForRowAtIndexPath`)

This is of course assuming that the layout of the given cell isn't dependent on the image or you have a way to determine the image size before loading the image.

**Comment by blessingLopes** [comment] 2015-02-09 00:24
@kylehickinson  Right now  my root UIviewController is holding this very simple ASCollectionView. The images are attatched to the ASCellNode class in collectionView(collectionView: ASCollectionView!, nodeForItemAtIndexPath indexPath: NSIndexPath!) with a constant size. The layout doesn't depended on the image in any way.
When the app loads, the nodes are sized and rendered asynchronously on a background thread (right?), but then the images are only displayed on screen after that process is done for all the cells. For a couple thousand  images this is actually pretty fast, only a few seconds, but it gets really bad beyond that.
I was thinking I could use the node's **displaysAsynchronously** flag to disable the async magic and perhaps force the images to display before the all the content is  fully-rendered and ready to go, but i haven't tried it yet.

**Comment by kylehickinson** [comment] 2015-02-09 03:13
@blessingLopes: @tanliboy might be better suited to answer this but i'll give it a shot:

When `ASCollectionView` begins to load your cells, it loads many `ASCellNode` objects at once and sizes them (I don't believe the process of allocating each is asynchronous, but the layout and rendering is, someone can correct me on this!).  This means you'll see your `nodeForItemAtIndexPath` called consecutively until it reaches the end (does it still do this post-batch updating merge @tanliboy or is it only working range cells that get allocated now?).  Meaning if you're doing any image decoding (e.g. calling `UIImage(named: dataSource[indexPath.item])`)  in this call or in your `ASCellNode` subclass `init` method then it must wait to decode said images until it can continue and begin showing your table.  

Not only that, since `ASCellNode` is not reused, if you give the cell a strong reference to an image, it will live in memory until that cell is destroyed for some reason (like from a `reloadData` call).  This can bring a lot of memory pressure quick and In my experience caused an out-of-memory crash at some point once it begins to render many many images.

By moving your image decoding to a on-screen basis (and making sure to dump it from memory in either the exit hierarchy call or in an overridden `reclaimMemory` method) you cut all of that processing required to allocate and size each cell, so it can get to the whole showing your table part faster.

Maybe's there's an even better solution to all of this, but I haven't had too much time to experiment other then using the `willEnter/didExitHierarchy` methods.  Perhaps `didLoad` could work also?

**Comment by tanliboy** [comment] 2015-02-09 04:03
Thanks @kylehickinson for the detailed illustration on the mechanism !
@blessingLopes, we do the cellNode allocation synchronically for keeping data consistent, which may take long initialization time when you try to initialize the ASCollectionView with a lot cells (like 30000 cells in your case). We are aware of this issue, but don't have a general solution yet. However, here is some suggestions that may could directly optimize the performance from the application code, FYI.
1) For memory usage: Try use ASLazyImageNode instead of UIImage view to achieve memory management and loading performance.
2) For ASCollectionView performance: Initialize the table with few cells (maybe 100 in your case, and you may only need to change the return value of "numberOfItemsInSection"), and then call the "insertItemsAtIndexPaths" from background thread. In this case, we will do the allocation from the background thread although we still need to allocate all cells.

**Comment by secretiverhyme** [comment] 2015-02-09 04:06
In general, if you're using ASNetworkImageNode or ASMultiplexImageNode, everything should Just Work(tm).  You're probably seeing slowdown on app launch because of #288.

Unfortunately, in order to support edit/update methods on ASTableView and ASCollectionView, we had to make data loading thread-affined:  if you call `-insertSections:` on a background queue, nodes will be processed on that queue, but when UIKit initially renders ASTV and ASCV, it processes nodes on the main thread.  For now, you need to start out with an empty data source and then add all content (e.g., using `-insertSections:`) on a background queue to avoid blocking with large data sets.  This is clearly not great, but improving it is possible now that editing support has stabilised.  =]

@kylehickinson, here's a bit of context on `-willEnterHierarchy`/`-didExitHierarchy` and friends (cc @rnystrom, who's working on the changes described here in #285):

We originally built AsyncDisplayKit as a necessary first step before building [Paper](http://facebook.com/paper).  The Paper story strip isn't a UICollectionView and its working range isn't powered by ASRangeController.  Since it isn't a UIKit component and isn't based on view reuse, its working range directly corresponds to "everything in the view hierarchy" — Paper keeps many card nodes offscreen, and uses `-removeFromSuperview` to keep memory usage in check.  `-didExitHierarchy` was therefore the logical place to free up memory (images, text rendering objects, and the like).

Of course, this design doesn't work in apps that use standard UIKit components and navigation!  Even scrolling through an ASTableView or ASCollectionView is enough to trigger many `-willEnterHierarchy` and `-didExitHierarchy` calls as the cells are reused (NB: ASCellNodes are not reused, but their containing cells are).  So, we replaced `-willEnterHierarchy` with `-displayWillStart` and introduced `-reclaimMemory` in lieu of `-didExitHierarchy` (79e65342b1b1273130392d75867ded5d793a7074).

This works for nodes that implement custom drawing, as ASTextNode and ASImageNode do, but it's only a first step.  For the ASDK 1.2 release, we're changing these subclass hooks to something like this (method names not final):

**rendering range** — formerly "working range", most people won't need to use these:
* `-displayWillStart` — called as nodes enter the working range and first start rendering
* `-clearRendering` — called as nodes exit the rendering range and should clear their backing stores

**network range:**
* `-fetchRemoteContent` — the appropriate place for custom nodes to load data, e.g., downloading images from the network
* `-clearFetchedContent` — called as nodes exit the network range and should clear their fetched content

This should hopefully be clearer and offer more flexibility.  It'll be possible to tune the rendering and network ranges, and they'll differ by default.  This will let you, for example, keep a small number of fully-rendered decompressed JPEGs around (`layer.contents`) but store a larger number of downloaded compressed JPEGs (`.image`).

**Comment by secretiverhyme** [comment] 2015-02-09 04:12
> When the app loads, the nodes are sized and rendered asynchronously on a background thread (right?), but then the images are only displayed on screen after that process is done for all the cells.

All nodes are immediately sized when the app loads, but rendering is limited to the contents of the [working range](http://asyncdisplaykit.org/guide/3/).  The system is designed to prioritise responsiveness and only render what's onscreen or will be onscreen soon — if you're seeing laggy image rendering with ASNetworkImageNode or ASMultiplexImageNode, that's a bug we'd love to fix.  =]

@blessingLopes, would you mind uploading a sample project we could take a look at?

**Comment by kylehickinson** [comment] 2015-02-09 04:45
Thanks you guys! Great information that i'll be taking advantage of when I get the chance :)

**Comment by blessingLopes** [comment] 2015-02-09 06:11
@secretiverhyme I'll be uploading my sample project soon, no problem :)

**Comment by blessingLopes** [comment] 2015-02-09 14:30
@kylehickinson @secretiverhyme 
Just added my sample ASCollectionView online. Hope I did it right :/  It's my 1st time using gitHub.
A Big thank you for your patience and suggestions!! :)

**Comment by secretiverhyme** [comment] 2015-02-09 22:12
@blessingLopes, awesome, thanks for uploading!  It does look like you're using image nodes correctly.  The problem is here:

```swift
func collectionView( collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int{
    // 3000 photos - 9.5 seconds from app launch to images on screen!!
    return 3000
}
```

This is the issue from #288 — with AsyncDisplayKit 1.1, anything in your collection or table view when it initially comes onscreen will block the main thread.  If you change this method to initially return 0, and then insert 3,000 items from a background queue, you should see the right behaviour.  (We're hoping to make this better for ASDK 1.2 or 1.3, but for now this is a necessary evil.)

**Comment by blessingLopes** [comment] 2015-02-10 01:47
@secretiverhyme 
Hi Nadine! i'm so happy you took a look at my code :) It means a world of help to get this kind of insight.
I'll definitely use your suggestion. Again, a big thank you.

**Comment by secretiverhyme** [comment] 2015-02-10 01:49
@blessingLopes — sure, happy to help.  Let me know if you have any other questions!  =]

**Comment by blessingLopes** [comment] 2015-02-10 01:54
@secretiverhyme  -  will do  :) Good night.

**Closed** 2015-02-10 04:47 UTC
Labels: discussion
