### ISSUE TITLE
[ASTextNode] If maxLines is the first height constraint on a string ending with line break, truncation string not shown.

### ISSUE THREAD

**Issue by yxztj** [facebook/AsyncDisplayKit#1295] opened 2016-03-01 03:31 UTC
Repro steps:

1. Set attributed text: "1\n2\n3\n4\n5"
2. Set maximumNumberOfLines to be 3
3. UILabel displays the expected text, the ellipsis should be displayed at last. ASTextNode doesn't.

I noticed #923 could be a related issue, so I checked ASDK 1.9.3, which has the expected ellipsis shown. But after that, the issue appeared till now(also tested 1.9.7)

Sample: https://github.com/yxztj/ASTextNodeTruncationIssue
The left uses UILabel, the right uses ASTextNode
<img width="733" alt="screen shot 2016-03-01 at 11 25 14 am" src="https://cloud.githubusercontent.com/assets/3334458/13416813/58a551a8-dfa0-11e5-8991-f182f696d083.png">

**Comment by appleguy** [comment] 2016-03-01 07:02
@yxztj thank you for reporting this. In your example, why is the font size different between the label and the node?

**Comment by yxztj** [comment] 2016-03-02 01:58
@appleguy Thanks for the quick reply.
I was trying to repro the issue using fewer lines, so I didn't set any font attributes for the label and text node. Guess it's the default behavior?

**Comment by yxztj** [comment] 2016-03-02 02:00
The code is quite simple, so I'd just paste it here.
```Swift
        let testString = "1\n2\n3\n4\n5"
        let attributedString = NSAttributedString(string: testString)
        let maxLines = 3
        
        testLabel.text = testString
        testLabel.backgroundColor = UIColor.lightGrayColor()
        testLabel.numberOfLines = maxLines
        testLabel.frame = CGRect(x: 20, y: 60, width: 40, height: 100)
        testLabel.attributedText = attributedString
        self.view.addSubview(testLabel)
        
        let textNode = ASTextNode()
        textNode.maximumNumberOfLines = UInt(maxLines)
        textNode.backgroundColor = UIColor.lightGrayColor()
        textNode.attributedString = attributedString
        self.view.addSubnode(textNode)
        textNode.frame = CGRect(x: 70, y: 60, width: 40, height: 100)
```

**Comment by appleguy** [comment] 2016-03-02 07:09
@yxztj have you tried setting a truncationAttributedString on the ASTextNode?  I would expect it to use ... by default, but would be interested to know if even that is insufficient.  I suspect this is caused only by truncations triggered by maximum line cap, rather than a size constraint.

Since we are in the final 2 week push for the Pinterest app rewrite, and then have stabilization work after that, it'll be tough for me to test around with this for a while.  If you have the time, the other thing to try is removing the numberOfLines max - and just provide a constrained height that is short enough to cause it.  Then, the ... will probably occur automatically?

**Comment by yxztj** [comment] 2016-03-02 08:14
@appleguy Setting the truncationAttributedString would resolve the issue. Didn't try that because it's value should be default to "..." as the comment says? :) 
Since we have a workaround, I think it's low priority now.

**Comment by aaronschubert0** [comment] 2016-03-09 15:14
@yxztj If you can try out my PR #1347 to see if this fixes this issue also, that'd be great.

**Comment by hannahmbanana** [comment] 2016-03-17 07:16
@yxztj - were you able to try out master? I am sure the community would love to hear if the fix for this did not address your case, as well as close out your task if it is taken care of. Thanks for the detailed report! :)

**Comment by yxztj** [comment] 2016-03-17 07:51
@aaronschubert0 @hannahmbanana Sorry for the delayed response.
It seems getting worse after the PR. Now the truncation string doesn't show up no matter truncationAttributedString is set or not. :( If revert to 1.9.6 the truncationAttributedString would take effect.

**Comment by appleguy** [comment] 2016-03-27 00:11
@yxztj I have your test case running. It is not clear to me yet that there is actually a bug…

For one thing, you are creating and attributed string without a font or font size. This appears to result in a difference in default size, and is allowing the ASDK string to fit in the box without any truncation. Have you tried any other examples where you specify all of the details of the attributed string?

Is the bug you were observing only caused by extra newlines after text, if those new lines have no visible characters on them? It is possible that these are being filtered out at some stage, and we can investigate why that is the case if true

**Comment by appleguy** [comment] 2016-03-27 00:56
@yxztj I have found to separate resolutions to the issue:

1. if you call measure: on the node before it is able to display, which is normally the case when a node is used in real real application as part of a layout spec or a correct implementation of the 1.x calculateSize...: method, AND provide a constrainedSize that matches the number of lines that it is expected to display, it will truncate properly even if the frame provided is larger. That is to say, it looks like if measure is not called or is called with a value greater than the equivalent number of max lines, it the layout calculation triggered at display-time may be using the taller value of the frame and not trigger creation of the truncation string until a later stage applies the maximum number of lines -- which may be too late

2. if you reduce the height of the frame by half, then even without the measure call, truncation is shown correctly.

So the bug appears to be specific to 1) using a maximum number of lines and that being the reason that a string truncates rather than the available height, 2) not calling measure or calling measure with a size that is greater than the true desired maximum height by exceeding the height of the maximum number of lines, and 3) also providing a frame that is taller than the maximum number of lines.

The good news is that it is undesirable to create this situation in a real application, because it results in a larger Display backing store which uses more memory and create additional compositing cost. This is equally true for UILabel - Apps should always minimize the size of their views.

Although this is a fairly extreme edge case, it is definitely a bug and deserves to be fixed. However, I hope you're able to employ one of these workarounds and continue using the latest version of the framework, because the degree of improvement in the overall framework achieved since the last version quite remarkable… I believe there are over 700 commits, and incredible performance improvements from the new ASRunloopQueue.

Thanks again for helping Report and communicate the details of this issue. I really appreciate it, as it would have been hard to discover otherwise, and it definitely does contribute to the community building one of the most advanced text engines on the platform.

**Comment by appleguy** [comment] 2016-03-27 00:57
Interestingly, if you do not set the maximum number of lines on the UILabel and provided the extra height in its frame, it also does not show the truncation string?

![simulator screen shot mar 26 2016 5 57 20 pm](https://cloud.githubusercontent.com/assets/565251/14063222/370665f6-f37c-11e5-8830-782faf3d301b.png)
![screen shot 2016-03-26 at 5 57 38 pm](https://cloud.githubusercontent.com/assets/565251/14063225/43270282-f37c-11e5-8dc4-53ea3641fa84.png)

**Comment by appleguy** [comment] 2016-03-27 01:24
@yxztj despite the relatively low priority, this one was bothering me, and so I investigated further and came up with what I am confident is the correct fix.

https://github.com/facebook/AsyncDisplayKit/pull/1440

Please try it out, and definitely continue to report any issues of this nature. Even if an extreme edge case, I really do want to make sure that every scenario works. I would highly recommend however that you start using ASViewController with a containing node, or a table / Collection with ASCellNodes.  You can either use the layout spec that fits method, or calculate size that fits, but this framework does expect that Measure is called on nodes before they are displayed.

If you use layout specs, Measure is called completely automatically. If you use calculate size that fits, the API contract is that you called measure on each of your subnodes, because providing the argument a constrained size is something that the framework is not able to do unless it has information about the desired layout.

**Closed** 2016-03-27 01:24 UTC
Labels: ASTextNode, bug (P3), fix landed

**Comment by yxztj** [comment] 2016-03-28 01:55
@appleguy Thanks for the detailed investigation! I just tried the latest master branch and the issue is gone.
Yes definitely would report any issue we encountered after narrowing down as much as we can. We'd be happy to contribute, but due to complexity of the framework, we haven't been able to read the code through and dig deep of what's behind the scene, so sometimes we could just to create a demo for repro issues without getting closer to root cause. There are some tutorials about how to use ASDK(and basic principles of how "async" is playing its role here), but not much how it works step by step. Hope we can get more articles/documents to help understand the framework. :)
