### ISSUE TITLE
[ASBatchContext] Batch fetch call won't occur for content smaller than bounds, unless user scrolls.

### ISSUE THREAD

**Issue by lxcid** [facebook/AsyncDisplayKit#341] opened 2015-02-27 14:16 UTC
I am excited about c657411a2e99e3a2195a03b1382c40815ff986a2 but after I tried it out it doesn't seems to work yet.

For example, if you set `kLitterSize` to 1 and/or `kLitterBatchSize` to 1 to simulate small dataset, after the first batch is loaded, the content size at this moment is smaller than the viewport but it doesn't call `handleBatchFetchScrollingToOffset:` which will trigger the small batch size logic. The `scrollViewWillEndDragging:withVelocity:targetContentOffset:` doesn't get trigger when you add/remove rows though. :(

Another thing I noticed is that

```
  // target offset will always be 0 if the content size is smaller than the viewport
  BOOL hasSmallContent = offset == 0.0 && contentLength < viewLength;
```

For the following code, target offset might not be zero if the content inset of the scroll view is being modified, which is often the case as view controller automatically adjust it post iOS 7 unless you opt out (Such bad API, I know)...

**Comment by secretiverhyme** [comment] 2015-03-02 20:45
@rnystrom, while we're at it, can we revisit the `-[ASBatchContext completeBatchFetching:]` API?  Passing `NO` is a no-op, and the presence of `-[ASBatchContext cancelBatchFetching]` makes the argument seem superfluous.

**Comment by appleguy** [comment] 2016-02-07 03:35
@lxcid I just confirmed that this is still happening. Disappointed that it took a year to fix this bug, but at least I can say with confidence that the framework development has been focused on some really big things in the meantime. It is now absolutely time to clean up and improve the batch fetching APIs though. This will be fixed in the next release.

@maicki, this change reproduces the issue. If the user initiates a drag, even though it will rubber band back into place, that will trigger the load. I think that is why this issue has not been widely reported. Probably the right thing to do is to use a new Hook from the ranch controller to check whether a batch fetch needs to be triggered, because the range controller runs its update pass in a variety of situations including edit operations and the appearance or disappearance of cells.

-static const NSInteger kLitterSize = 20;            // intial number of kitten cells in ASTableView
+static const NSInteger kLitterSize = 1;            // intial number of kitten cells in ASTableView

**Comment by appleguy** [comment] 2016-04-20 02:51
@maicki: thanks for fixing this long standing issue. @lxcid - Sorry this took so long to get around too. I hope you are still using ASDK. Let us know if we can help you out with any more issues.

**Closed by appleguy** 2016-04-20 02:51 UTC
Labels: bug (P1)

**Comment by lxcid** [comment] 2016-04-22 00:43
@appleguy sorry for such late reply. I no longer have access to the codebase that integrate ASDK so it probably a little hard to verify them. Sorry!

We were still able to get it working great with minimal issue and a little bit of work around when I was there. Thanks for the great work from you and the team at Facebook/Pinterest!
