### ISSUE TITLE
[PINRemoteImage] ASNetworkingImageNode may cache an incomplete image if the network is slow.

### ISSUE THREAD

**Issue by boreys** [facebook/AsyncDisplayKit#2574] opened 2016-11-08 06:53 UTC
In a country where mobile internet connection is unreliable and slow, ASNetworkingImageNode failed to download the whole image sometime and cache it; late on this broken image is shown to users:
![broken image](https://cloud.githubusercontent.com/assets/8430251/20089574/6f17725a-a5ba-11e6-8fb5-7b423beb36ab.jpg)

**Comment by appleguy** [comment] 2016-11-08 07:53
@garrettmoon - this could be related to / the same as the PINRemoteImage issue, https://github.com/pinterest/PINRemoteImage/issues/260?

@boreys thank you for reporting this!  If you believe this issue is most likely related to PINRemoteImage internal behavior, rather than the way AsyncDisplayKit drives it, let's move the discussion to that project.  Does it sound like the same issue to you?  If you could read back on the thread, we'd be grateful for any similar details on the case you discovered.

This is the most important image-related issue we're tracking right now, as we just heard about it a few days ago.  We'll prioritize getting it fixed as soon as we have a lead on what might be causing it, and ideally we can force it to reproduce by using network link conditioner, manually crash app while saving, etc.

**Comment by boreys** [comment] 2016-11-08 10:41
Yes, i think this issue is related to the one reported on PINRemoteImage issue. Two conditions that cause this issues 1- slow and interrupted network, 2- multiple concurrent images download, my app is downloading around 60 images (100 K each) per screen view.

**Comment by garrettmoon** [comment] 2016-11-15 00:52
@boreys thanks for the info! I'm going to close this issue as this is definitely caused by PINRemoteImage. Feel free to follow along there!

**Closed by garrettmoon** 2016-11-15 00:52 UTC
Labels: Bug

**Comment by garrettmoon** [comment] 2016-12-06 23:55
FYI for anyone following this thread, this was fixed in PINRemoteImage (`3.0.0-beta.7`) & ASDK (`2.0-rc.2`) Please give it a try and if you hit this again mention it here: https://github.com/pinterest/PINRemoteImage/issues/260
