### ISSUE TITLE
[ASTextNode] App freezes when calling trailingRect

### ISSUE THREAD

**Issue by ChrisSchneider** [facebook/AsyncDisplayKit#1334] opened 2016-03-07 10:29 UTC
Hey there,

in AsyncDisplayKit 1.9.6 or master calling trailingRect on a ASTextNode freezes the app.
The same Code works with ADK 1.9.2

Thanks a lot for your help!

Sample Code:
```
final class TestNode: ASDisplayNode {
    
    let textNode: ASTextNode = {
        let node = ASTextNode()
        node.attributedString = NSAttributedString(string: "Foooo")
        return node
    }()
    
    override func layout() {
        super.layout()
        
        addSubnode(textNode)
        textNode.frame = bounds
        
        print("IN")
        print(textNode.trailingRect())
        print("OUT")
    }
    
}
```

Backtrace:
```
* thread #1: tid = 0x21cf9e, 0x0000000105bbeee2 libsystem_kernel.dylib`__psynch_mutexwait + 10, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x0000000105bbeee2 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x0000000105b86a49 libsystem_pthread.dylib`_pthread_mutex_lock_wait + 89
    frame #2: 0x0000000101b1c09f libc++.1.dylib`std::__1::mutex::lock() + 9
    frame #3: 0x000000010186aacc TextNodeBugTest`-[ASTextKitContext performBlockWithLockedTextKitComponents:] [inlined] std::__1::lock_guard<std::__1::mutex>::lock_guard(this=0x00007fff5e4a8580, __m=0x00007ff648e14348) + 11 at __mutex_base:83
    frame #4: 0x000000010186aac1 TextNodeBugTest`-[ASTextKitContext performBlockWithLockedTextKitComponents:] [inlined] std::__1::lock_guard<std::__1::mutex>::lock_guard(this=0x00007fff5e4a8580, __m=0x00007ff648e14348) + 12 at __mutex_base:83
    frame #5: 0x000000010186aab5 TextNodeBugTest`-[ASTextKitContext performBlockWithLockedTextKitComponents:](self=0x00007ff648e14340, _cmd="performBlockWithLockedTextKitComponents:", block=(TextNodeBugTest`__63-[ASTextKitRenderer(Tracking) rectsForTextRange:measureOption:]_block_invoke at ASTextKitRenderer+Positioning.mm:29)) + 69 at ASTextKitContext.mm:76
    frame #6: 0x000000010187029b TextNodeBugTest`-[ASTextKitRenderer(self=0x00007ff648e14b20, _cmd="rectsForTextRange:measureOption:", textRange=location=5, length=1, measureOption=ASTextKitRendererMeasureOptionLineHeight) rectsForTextRange:measureOption:] + 395 at ASTextKitRenderer+Positioning.mm:29
    frame #7: 0x0000000101875321 TextNodeBugTest`__43-[ASTextKitRenderer(.block_descriptor=0x00007fff5e4a8a30, layoutManager=0x00007ff648e217d0, textStorage=0x00007ff648e15ec0, textContainer=0x00007ff648e2f650) trailingRect]_block_invoke + 577 at ASTextKitRenderer+Positioning.mm:345
    frame #8: 0x000000010186ab10 TextNodeBugTest`-[ASTextKitContext performBlockWithLockedTextKitComponents:](self=0x00007ff648e14340, _cmd="performBlockWithLockedTextKitComponents:", block=(TextNodeBugTest`__43-[ASTextKitRenderer(Tracking) trailingRect]_block_invoke at ASTextKitRenderer+Positioning.mm:336)) + 160 at ASTextKitContext.mm:77
    frame #9: 0x0000000101874fe8 TextNodeBugTest`-[ASTextKitRenderer(self=0x00007ff648e14b20, _cmd="trailingRect") trailingRect] + 344 at ASTextKitRenderer+Positioning.mm:336
    frame #10: 0x00000001018862c2 TextNodeBugTest`-[ASTextNode trailingRect](self=0x00007ff649805a00, _cmd="trailingRect") + 130 at ASTextNode.mm:755
    frame #11: 0x00000001017567f6 TextNodeBugTest`TextNodeBugTest.TestNode.layout (self=0x00007ff648c1e420)() -> () + 742 at TestNode.swift:19
    frame #12: 0x0000000101756a92 TextNodeBugTest`@objc TextNodeBugTest.TestNode.layout (TextNodeBugTest.TestNode)() -> () + 34 at TestNode.swift:0
    frame #13: 0x00000001017e3e10 TextNodeBugTest`-[ASDisplayNode __layout](self=0x00007ff648c1e420, _cmd="__layout") + 1024 at ASDisplayNode.mm:1118
    frame #14: 0x000000010176af88 TextNodeBugTest`-[_ASDisplayLayer layoutSublayers](self=0x00007ff648c23260, _cmd="layoutSublayers") + 136 at _ASDisplayLayer.mm:107
    frame #15: 0x0000000104bd7e70 QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 366
    frame #16: 0x0000000104bd7cee QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
    frame #17: 0x0000000104bcc475 QuartzCore`CA::Context::commit_transaction(CA::Transaction*) + 277
    frame #18: 0x0000000104bf9c0a QuartzCore`CA::Transaction::commit() + 486
    frame #19: 0x0000000104bfa37c QuartzCore`CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
    frame #20: 0x00000001040f5367 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #21: 0x00000001040f52d7 CoreFoundation`__CFRunLoopDoObservers + 391
    frame #22: 0x00000001040ea84c CoreFoundation`CFRunLoopRunSpecific + 524
    frame #23: 0x00000001024567cd UIKit`-[UIApplication _run] + 402
    frame #24: 0x000000010245b610 UIKit`UIApplicationMain + 171
    frame #25: 0x00000001017597ad TextNodeBugTest`main + 109 at AppDelegate.swift:12
    frame #26: 0x000000010587f92d libdyld.dylib`start + 1
    frame #27: 0x000000010587f92d libdyld.dylib`start + 1

  thread #2: tid = 0x21d1a7, 0x0000000105bbffde libsystem_kernel.dylib`kevent64 + 10, queue = 'com.apple.libdispatch-manager'
    frame #0: 0x0000000105bbffde libsystem_kernel.dylib`kevent64 + 10
    frame #1: 0x000000010583a4c8 libdispatch.dylib`_dispatch_mgr_invoke + 260
    frame #2: 0x000000010583a262 libdispatch.dylib`_dispatch_mgr_thread + 54

  thread #3: tid = 0x21d1ab, 0x0000000105bbf6de libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x0000000105bbf6de libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x0000000105b83729 libsystem_pthread.dylib`_pthread_wqthread + 1283
    frame #2: 0x0000000105b81365 libsystem_pthread.dylib`start_wqthread + 13

  thread #4: tid = 0x21d1ac, 0x0000000105bbf6de libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x0000000105bbf6de libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x0000000105b83729 libsystem_pthread.dylib`_pthread_wqthread + 1283
    frame #2: 0x0000000105b81365 libsystem_pthread.dylib`start_wqthread + 13

  thread #5: tid = 0x21d1b5, 0x0000000105bbf6de libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #0: 0x0000000105bbf6de libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x0000000105b83729 libsystem_pthread.dylib`_pthread_wqthread + 1283
    frame #2: 0x0000000105b81365 libsystem_pthread.dylib`start_wqthread + 13

```

**Comment by appleguy** [comment] 2016-03-09 10:56
@ChrisSchneider thank you for the report!  I had certainly not heard of this before, although it is probably an easy fix because it is so egregious.  It reproduces every time, correct?

Does the backtrace you provided here include every thread? What I am a bit confused about is there is no other thread waiting on a lock, so it should be fairly difficult for the code to get in a deadlock with itself :).  Definitely possible, probably some very obvious mistake.

**Comment by ChrisSchneider** [comment] 2016-03-09 17:23
@appleguy: Thanks for your help in resolving this issue.

Yes, it reproduces every time and I used "bt all" to generate the backtrace.

I attached a sample project to reproduce the bug:
[TextNodeBug.zip](https://github.com/facebook/AsyncDisplayKit/files/165693/TextNodeBug.zip)

**Comment by levi** [comment] 2016-05-09 21:50
@appleguy looks like this is resolved with #1527

**Comment by appleguy** [comment] 2016-05-11 02:06
@ChrisSchneider: Thanks for contributing to the AsyncDisplayKit community by pointing out this bug! If you are able to, could you confirm that this fix resolves your issue? If you are still having troubles, feel please re-open the issue.

**Closed by appleguy** 2016-05-11 02:06 UTC
Labels: ASTextNode, bug (P2)

**Comment by ChrisSchneider** [comment] 2016-05-17 12:26
@appleguy: Thank you for your great work with AsyncDisplayKit! This fix solves our issue.
