### ISSUE TITLE
ASTableView & ASCollectionView shouldn't block the main thread by default

### ISSUE THREAD

**Issue by phatmann** [facebook/AsyncDisplayKit#288] opened 2015-02-04 19:45 UTC
I have an ASTableView with 1000 nodes. When the table is reloaded, there are several distinct visible phases:

1. No cells showing
1. Cells showing but CPU churning and UI not responsive
1. Cell subnodes showing placeholders while they load
1. Cells fully loaded and visible

I would like to hide the table until phases 1 and 2 are complete because it is not in a genuinely useful state until then. In fact, if I try to remove a cell (via a close button) during phase 2, I often run into bad access errors.

Browsing through the ASTableView code, I did not see any easy and obvious way to see what state the table is in. If anyone can point me in the right direction, I would be happy to put together a PR. My naive approach would be to dig into the node loading code in ASDataController and see what hooks I can add.

I would either add additional methods for ASTableView subclasses to hook into, or add methods to the table delegate. Suggestions welcome.

Being able to detect when phase 3 is done would be nice but is not necessary.

Worth noting: this is not much of a problem on fast modern devices, but could be an issue on older, slower devices. If you run your app in the pokey iOS Simulator you will see what I mean :-(

**Comment by tanliboy** [comment] 2015-02-04 22:10
Do you have sample code to reproduce the issues you described ? 
The ASDataController will fetch the nodes through "nodeAtIndexPath:" in the calling thread, and then dispatched to background thread in batch for layout. After the layout, the nodes will show up.
With pre-allocation on the nodes in background thread may could remove the stuck in stages 1) or 2). 
It would be great if you have the sample code so that we could dig into and optimize it.

**Comment by phatmann** [comment] 2015-02-05 16:18
@tanliboy, if you want sample code that shows the loading slowdown, just modify the Kittens sample to load a 1000 nodes instead of 20 and run in the simulator.

Do you want sample code to that illustrates the bad access error? Could be trickier since the problem is sporadic.

**Comment by tanliboy** [comment] 2015-02-05 18:31
Thanks for reply !
I will update the Kitten project to make the cell allocated in background thread, and try with a demo to illustrate the editing. The inserting/deleting need to go through the ASTableView API, because the we do the layout in async mode and the index path in the UITableView may does not match the index path in the ASTableView.

**Comment by phatmann** [comment] 2015-02-06 20:26
When you say that deleting needs to go through the ASTableView API, what do you mean? Since ASTableView overrides `deleteRowsAtIndexPaths`, isn't this automatic?

**Comment by tanliboy** [comment] 2015-02-06 22:10
Yes, it is right API. But the indexPath need to be retrieved from you data model rather than from the UITableView. How do you find index path of the cell while clicking the close button ?

**Comment by phatmann** [comment] 2015-02-06 22:41
I look up the index in the data model, based on the object associated with the cell. I do not use `indexPathForCell`.

**Comment by tanliboy** [comment] 2015-02-10 01:49
Send https://github.com/facebook/AsyncDisplayKit/pull/303 to enable async data fetching to address this issue.

**Comment by secretiverhyme** [comment] 2015-02-12 00:32
Closing — discussion is happening on #303.

**Closed by secretiverhyme** 2015-02-12 00:32 UTC
Labels: bug, core architecture
