### ISSUE TITLE
[ASViewController] Should update interfaceState, at least Visible, with VC transitions.

### ISSUE THREAD

**Issue by smyrgl** [facebook/AsyncDisplayKit#1285] opened 2016-02-28 15:25 UTC
I'm not sure if this is intentional or not but `interfaceStateDidChange:` is not being called on nodes during VC transitions in `1.9.7`.  I can provide sample code if needed but I figure that it is pretty obvious what is going on.  Is this an intentional thing so as to not muddle VC transitions?

**Comment by appleguy** [comment] 2016-02-29 07:16
@smyrgl just checking, this is not a change in behavior from previous versions correct?  1.9.7 is so vastly improved over 1.9.6 that I'm hesitant to hold the release any longer, despite the importance of this.

We are actively working on a fix for this, it may not make the next release assuming it is not a regression, that it should be available in master within the next week. This is a tough call, because this is a very important issue to fix, but there are subtleties in doing this correctly (e.g. so that content doesn't flash when returning, and ideally supporting UIViewController rather than just AS*).

cc @levi, @maicki, @nguyenhuy

**Comment by smyrgl** [comment] 2016-02-29 18:28
@appleguy Actually I had never used this hook in this context before but I doubt very much this is a regression.  This just came up as part of the validation you asked for on 1.9.7.

I tend to agree that this is not a blocker at all but it's probably a very good thing to resolve since visibility hooks on nodes are incredibly useful in table/collection views.

**Comment by smyrgl** [comment] 2016-02-29 18:29
Plus I'm almost always pulling directly from master anyway so the fact that it won't make the 1.9.7 tag is of little importance to me personally. :)

**Comment by appleguy** [comment] 2016-02-29 22:55
@smyrgl agreed, we may in fact get this fixed for 1.9.7 as it is a critical issue for Pinterest too.  Thanks a lot for filing it!

**Comment by appleguy** [comment] 2016-03-01 07:00
Implementation for this is landed. We will continue to refine this behavior, but closing out this task for now. Please reopen if you detect any critical issues, @smyrgl

**Closed by appleguy** 2016-03-01 07:00 UTC
Labels: API improvement, bug (P2)
