### ISSUE TITLE
Memory leak and Memory cost too high in ASTableView or ASCollectionView

### ISSUE THREAD

**Issue by TernTuring** [facebook/AsyncDisplayKit#754] opened 2015-10-20 07:47 UTC
I have met some problems while using  ASDK. I had push a viewcontroller with ASTableView, and memory increasing when scrolling the table, but not release the memory when pop view. I'm sure the viewcontroller dealloc function was invoked.
![memory2](https://cloud.githubusercontent.com/assets/10182423/10601058/7680fa3c-7741-11e5-8f0c-b9149b083204.png)
![memory3](https://cloud.githubusercontent.com/assets/10182423/10601059/76e3c87e-7741-11e5-8fef-db525a4d2e63.png)

**Comment by appleguy** [comment] 2015-10-20 20:26
@TernTuring Thanks for reporting this!  I haven't seen this problem before, but if we can reproduce it, clearly it is very important to fix.

Would you be able to create a sample project, or modify one of the existing examples/ directory projects (like the Kittens app) to reproduce it?  It seems like you'd mainly need to add a UINavigationController, and push another table view onto it, then do the Instruments checking to make sure it has the issue.

A simple way to do this would be to hack the Kittens app so that the button in the navigation bar (set on the navItem) simply pushes a second copy / new instance of the Kittens view controller.

**Comment by TernTuring** [comment] 2015-10-20 23:59
@appleguy .Thank you. How can I send a sample project to you? Due to the sample project inheritance product code, and I don't share the project on github.My email is recordhistory@gmail.com, Please send a mail to me, and I will send sample project to you by mail.

**Comment by appleguy** [comment] 2015-10-21 00:06
Thanks!  Sent you an email (you can delete it from your post if you want to make sure email-crawling systems don't send you spam, not sure how often that actually happens).

**Comment by TernTuring** [comment] 2015-10-21 03:07
@appleguy , I had send a sample project to your mailbox. Thanks for your help!

**Comment by appleguy** [comment] 2015-10-22 01:38
@TernTuring it's great to be in touch with you via email.  I have a lead, which suggests there may be a capture of a "self" object in a block being given to the networking system of the app (or similar).

Although there is very possibly a lesson from this that can help improve ASDK — we should try to see if there is a way to break the cycle by changing something about the API / making it harder to create this type of cycle — I think the most direct fix will be in your app code.  Because this doesn't affect other clients of ASDK directly, I'm going to close this task (but will continue actively working with you until the issue is solved).

Please feel welcome to open more tasks for any other issues you encounter.

**Closed by appleguy** 2015-10-22 01:38 UTC
