### ISSUE TITLE
Assertion failure in -[ASCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.4/UICollectionView.m:3994

### ISSUE THREAD

**Issue by tettoffensive** [facebook/AsyncDisplayKit#654] opened 2015-09-15 21:37 UTC
I am often getting this exception thrown with my ASCollectionView when reloadData is called. I have seen this pop up pretty regularly, but not all the time. Seems to happen more often when I have a breakpoint set in Xcode.

```
- (void)rangeController:(ASRangeController *)rangeController didDeleteSectionsAtIndexSet:(NSIndexSet *)indexSet withAnimationOptions:(ASDataControllerAnimationOptions)animationOptions
{
  ASDisplayNodeAssertMainThread();

  if (!self.asyncDataSource) {
    return; // if the asyncDataSource has become invalid while we are processing, ignore this request to avoid crashes
  }

  if (_performingBatchUpdates) {
    [_batchUpdateBlocks addObject:^{
      [super deleteSections:indexSet];
    }];
  } else {
    [UIView performWithoutAnimation:^{
      [super deleteSections:indexSet]; // !!!!! <NSMutableIndexSet: 0x1355b4310>[number of indexes: 1 (in 1 ranges), indexes: (0)]
    }];
  }
}
```

**Comment by appleguy** [comment] 2015-09-15 21:53
Thanks for the report--lets get it fixed.

What version of ASDK are you running?  Please try it against Master and report back. I'm cutting the 2.0 Beta branch (which is actually quite stable) in the next 24-48hrs.

**Comment by tettoffensive** [comment] 2015-09-15 21:54
I'm using the default for Cocoapods - looks like Using AsyncDisplayKit (1.2.3)

**Comment by appleguy** [comment] 2015-09-15 22:18
OK, makes sense.  Crashes are never justified, so I’d love to help get this resolved as soon as possible.

I’ve been working on 2.0 for a number of months now, and it includes a vast array of improvements.  In about 36hrs I’m giving the first talk on it (at NSSpain), and so until then and when I get back to the US, I’ll be busier than usual.

Definitely let me know what your test against master yields.  I think it’s likely that it will fix it, but it will be a high priority bug if not.

Cheers,

		— Scott

**Comment by tettoffensive** [comment] 2015-09-15 22:40
```
pod 'AsyncDisplayKit' , :git => 'https://github.com/facebook/AsyncDisplayKit.git' , :branch => 'master'
```

Changed my Podfile to get the master branch, but started getting all these errors on compile. Trying to figure out what's going on.

Type name requires a specifier or qualifier

```
ASDN::RecursiveMutex _layoutOptionsLock;
```

**Comment by appleguy** [comment] 2015-09-15 22:42
Hmm, that’s odd.  That type of lock is used elsewhere, but that code is very new indeed.  Just landed last week.  Ricky — can you take a quick look?

Stuart, if you could provide a complete copy of the last ~100 lines or so of the log / compiler output, that could potentially help.  Does it compile for you using the example/ apps in the ASDK directory?

		— Scott

**Comment by tettoffensive** [comment] 2015-09-15 23:05
Scott, Just downloaded the zip and tried one of the examples and it worked there.

I am using `use_frameworks!` in my cocoapods

```
While building module 'AsyncDisplayKit' imported from /Users/Stuart/Channels/Channels/Channels/ListChannelsViewController.m:10:
In file included from <module-includes>:1:
In file included from /Users/Stuart/Library/Developer/Xcode/DerivedData/Channels-gtqfdtofjptjyddzlcsmzkppvsqf/Build/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Headers/AsyncDisplayKit-umbrella.h:65:
/Users/Stuart/Library/Developer/Xcode/DerivedData/Channels-gtqfdtofjptjyddzlcsmzkppvsqf/Build/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Headers/ASLayoutOptionsPrivate.h:21:3: error: type name requires a specifier or qualifier
  ASDN::RecursiveMutex _layoutOptionsLock;
  ^
/Users/Stuart/Library/Developer/Xcode/DerivedData/Channels-gtqfdtofjptjyddzlcsmzkppvsqf/Build/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Headers/ASLayoutOptionsPrivate.h:21:8: error: expected expression
  ASDN::RecursiveMutex _layoutOptionsLock;
       ^
/Users/Stuart/Library/Developer/Xcode/DerivedData/Channels-gtqfdtofjptjyddzlcsmzkppvsqf/Build/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Headers/ASLayoutOptionsPrivate.h:31:3: error: type name requires a specifier or qualifier
  ASDN::RecursiveMutex _layoutOptionsLock;
  ^
/Users/Stuart/Library/Developer/Xcode/DerivedData/Channels-gtqfdtofjptjyddzlcsmzkppvsqf/Build/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Headers/ASLayoutOptionsPrivate.h:31:8: error: expected expression
  ASDN::RecursiveMutex _layoutOptionsLock;
       ^
4 errors generated.
/Users/Stuart/Channels/Channels/Channels/ListChannelsViewController.m:10:9: fatal error: could not build module 'AsyncDisplayKit'
@import AsyncDisplayKit;
 ~~~~~~~^~~~~~~~~~~~~~~
5 errors generated.
```

Does this help? It's the same thing if I use: `#import <AsyncDisplayKit/AsyncDisplayKit.h>`

I tried cleaning my derived data and clean build and even `pod cache clean AsyncDisplayKit` with no luck

**Comment by rcancro** [comment] 2015-09-15 23:21
These look like Objective-C++ errors.  I would get errors like that when a file wasn't named .mm but I was using the `ASDN::RecurisveMutex`.  What is in `AsyncDisplayKit-umbrella.h` that you are including?

**Comment by tettoffensive** [comment] 2015-09-15 23:36
I definitely see that it changes the umbrella file when I update to use master. These are the lines added:

```
#import "ASCollectionNode.h"

#import "ASBackgroundLayoutSpec.h"
#import "ASCenterLayoutSpec.h"
#import "ASDimension.h"
#import "ASInsetLayoutSpec.h"
#import "ASLayout.h"
#import "ASLayoutable.h"
#import "ASLayoutablePrivate.h"
#import "ASLayoutOptions.h"
#import "ASLayoutOptionsPrivate.h"
#import "ASLayoutSpec.h"
#import "ASOverlayLayoutSpec.h"
#import "ASRatioLayoutSpec.h"
#import "ASRelativeSize.h"
#import "ASStackLayoutable.h"
#import "ASStackLayoutDefines.h"
#import "ASStackLayoutSpec.h"
#import "ASStaticLayoutable.h"
#import "ASStaticLayoutSpec.h"
```

**Comment by rcancro** [comment] 2015-09-15 23:49
Oh, I see the problem. ASLayoutOptionsPrivate.h uses Objective-C++. Anything that imports it needs to use Objective-C++.  

This is a mistake on my part, I didn't mean to force the world into using C++. Let me try to get a PR up so if nothing else you can get building again.  Sorry about this!

**Comment by tettoffensive** [comment] 2015-09-16 00:02
Awesome, thanks Ricky!

**Comment by rcancro** [comment] 2015-09-16 00:15
The problem is that `ASLayoutOptionsPrivate.h` should not be a public header file -- shocking given its name :). I moved it from the `layout` folder to the `private` folder in the project and filesystem. I also changed its target membership from public to private.

Did removing it manually from the umbrella file work for a temporary fix?

**Comment by tettoffensive** [comment] 2015-09-16 01:31
It throws a warning. but yea. it seems to work. I wonder if `#import "ASLayoutablePrivate.h"` should be in there even given it's name? (Doesn't cause any issues for me though)

**Comment by tettoffensive** [comment] 2015-09-16 01:33
@appleguy Still seeing the same issue though

```
2015-09-15 18:33:01.292 Channels[1042:508594] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete section 0, but there are only 0 sections before the update'
*** First throw call stack:
(0x1853b1a94 0x199d0bf80 0x1853b1964 0x1862a009c 0x18b07ec14 0x18b07dab8 0x1008e9384 0x18a8d110c 0x1008e915c 0x100957614 0x1009120e4 0x100957508 0x1008f0ee4 0x1009121f4 0x101135e0c 0x101135dcc 0x10113b7fc 0x185368d90 0x185366bf8 0x1852958a0 0x1902f0088 0x18a92a0d4 0x1000b1d7c 0x19a55a8b8)

libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by appleguy** [comment] 2015-09-16 11:31
@tettoffensive alright, the build fix is merged.  Thanks for letting us know about that.  You might have been the only way we would have caught that particular bug before launching the 2.0 Beta tomorrow, ha!

A few questions / escalation steps to reach a resolution:
- Were there any changes after updating to master, either in the specifics of the stack trace, or frequency of the crash?
- Describe a bit more about what types of edit operations your app does.  Does it use batch updating at all, or never?  Have you found a way to reproduce this 100%?  Assuming not, have you noticed any patterns that make it more likely?  (fast scrolling, running on a device rather than simulator, using scroll-to-top, leaving and revisiting the view, suspending / resuming the app, etc)
- Share more of your implementation so we can understand the calls going into the framework and can look for causes.  This may not be feasible for you, but one option would be taking the relevant files and hacking out the majority of them, leaving empty cell nodes that you are pushing around.
- Create a test project, either via the above mechanism or from modifying one of the ASCollectionView example projects.  This would allow us to fix the issue most quickly by far, as we can both live debug and validate the fix (it may actually not be possible to figure out the issue without doing this)

Sorry you're experiencing trouble here.  Looking forward to finding the problem :).

**Comment by eanagel** [comment] 2015-09-16 16:31
Thanks for helping us get to the bottom of this, @tettoffensive! These are the kind of problems that we only find in the wild and are so valuable to run down. In addition to @appleguy's questions above, could you could include the actual message from the failed assertion? That, coupled with the actual stack trace (bt in the console) would be really helpful.

**Comment by tettoffensive** [comment] 2015-09-16 17:59
Hopefully, I'll have some time later today to setup a test project. Busy workload right now.

But I can tell you it happens most often when I have breakpoints set in xcode and I'm stepping through.

I do have a KVOController setup and it is calling reloadData on the collection view when that block is called.

And the only other thing I can think of is that when the data source is set it is nil. And then once the data is downloaded from the server, that is when reloadData is called to refresh everything and that is when the crash happens. This is pretty much right after the app starts up.

**Comment by tettoffensive** [comment] 2015-09-16 19:04
```
2015-09-16 12:03:54.627 Channels[1375:677242] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (2) must be equal to the number of sections contained in the collection view before the update (2), plus or minus the number of sections inserted or deleted (2 inserted, 0 deleted).'
*** First throw call stack:
(0x1853b1a94 0x199d0bf80 0x1853b1964 0x1862a009c 0x18b080a54 0x18b07dab8 0x1008ae93c 0x18a8d110c 0x1008ae714 0x10090ba18 0x1008d5718 0x10090b484 0x1008b6714 0x1008d5828 0x1010a1e0c 0x1010a1dcc 0x1010a77fc 0x185368d90 0x185366bf8 0x1852958a0 0x1902f0088 0x18a92a0d4 0x100069528 0x19a55a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) bt
* thread #1: tid = 0xa557a, 0x000000019a6771e0 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x000000019a6771e0 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000019a740f0c libsystem_pthread.dylib`pthread_kill + 112
    frame #2: 0x000000019a5eab78 libsystem_c.dylib`abort + 140
    frame #3: 0x000000019939d3f4 libc++abi.dylib`abort_message + 132
    frame #4: 0x00000001993b9e98 libc++abi.dylib`default_terminate_handler() + 304
    frame #5: 0x0000000199d0c248 libobjc.A.dylib`_objc_terminate() + 124
    frame #6: 0x00000001993b6f44 libc++abi.dylib`std::__terminate(void (*)()) + 16
    frame #7: 0x00000001993b685c libc++abi.dylib`__cxa_throw + 136
    frame #8: 0x0000000199d0c094 libobjc.A.dylib`objc_exception_throw + 332
    frame #9: 0x00000001853b1964 CoreFoundation`+[NSException raise:format:arguments:] + 108
    frame #10: 0x00000001862a009c Foundation`-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
    frame #11: 0x000000018b080a54 UIKit`-[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:] + 11524
    frame #12: 0x000000018b07dab8 UIKit`-[UICollectionView _updateSections:updateAction:] + 424
  * frame #13: 0x00000001008ae93c AsyncDisplayKit`__85-[ASCollectionView rangeController:didInsertSectionsAtIndexSet:withAnimationOptions:]_block_invoke254(.block_descriptor=<unavailable>) + 76 at ASCollectionView.mm:668
    frame #14: 0x000000018a8d110c UIKit`+[UIView(Animation) performWithoutAnimation:] + 80
    frame #15: 0x00000001008ae714 AsyncDisplayKit`-[ASCollectionView rangeController:didInsertSectionsAtIndexSet:withAnimationOptions:](self=0x000000014f811800, _cmd="rangeController:didInsertSectionsAtIndexSet:withAnimationOptions:", rangeController=0x0000000150850dc0, indexSet=2 indexes, animationOptions=5) + 1044 at ASCollectionView.mm:667
    frame #16: 0x000000010090ba18 AsyncDisplayKit`__86-[ASRangeController dataController:didInsertSections:atIndexSet:withAnimationOptions:]_block_invoke147(.block_descriptor=<unavailable>) + 104 at ASRangeController.mm:227
    frame #17: 0x00000001008d5718 AsyncDisplayKit`ASDisplayNodePerformBlockOnMainThread(block=(AsyncDisplayKit`__86-[ASRangeController dataController:didInsertSections:atIndexSet:withAnimationOptions:]_block_invoke147 at ASRangeController.mm:225)) block_pointer) + 104 at ASDisplayNode.mm:76
    frame #18: 0x000000010090b484 AsyncDisplayKit`-[ASRangeController dataController:didInsertSections:atIndexSet:withAnimationOptions:](self=0x0000000150850dc0, _cmd="dataController:didInsertSections:atIndexSet:withAnimationOptions:", dataController=0x00000001508552c0, sections=@"2 objects", indexSet=2 indexes, animationOptions=5) + 828 at ASRangeController.mm:225
    frame #19: 0x00000001008b6714 AsyncDisplayKit`__68-[ASDataController _insertSections:atIndexSet:withAnimationOptions:]_block_invoke(.block_descriptor=<unavailable>) + 188 at ASDataController.mm:193
    frame #20: 0x00000001008d5828 AsyncDisplayKit`___Z37ASDisplayNodePerformBlockOnMainThreadU13block_pointerFvvE_block_invoke(.block_descriptor=<unavailable>) + 40 at ASDisplayNode.mm:79
    frame #21: 0x00000001010a1e0c libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #22: 0x00000001010a1dcc libdispatch.dylib`_dispatch_client_callout + 16
    frame #23: 0x00000001010a77fc libdispatch.dylib`_dispatch_main_queue_callback_4CF + 2096
    frame #24: 0x0000000185368d90 CoreFoundation`__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
    frame #25: 0x0000000185366bf8 CoreFoundation`__CFRunLoopRun + 1628
    frame #26: 0x00000001852958a0 CoreFoundation`CFRunLoopRunSpecific + 384
    frame #27: 0x00000001902f0088 GraphicsServices`GSEventRunModal + 180
    frame #28: 0x000000018a92a0d4 UIKit`UIApplicationMain + 204
    frame #29: 0x0000000100069528 Channels`main(argc=1, argv=0x000000016fdb3a78) + 124 at main.m:14
    frame #30: 0x000000019a55a8b8 libdyld.dylib`start + 4
```

**Comment by tettoffensive** [comment] 2015-09-17 18:53
I created a test project here: https://github.com/tettoffensive/ASCollectionViewTest/tree/master

And this one seems to be crashing all the time. It's possible I made a mistake when making this, but it is producing the same exception so I think it'll help

**Comment by appleguy** [comment] 2015-09-19 19:21
Thanks again @tettoffensive — not exaggerating, because the main ASDK maintainers also have day-jobs it is so tremendously helpful to have this level of detail from the most competent and thoughtful users of the framework.

I'll be back in California early this coming week, and will work with @eanagel to figure this out pronto.  I've saved your sample locally and will take a first look at it on the plane.

Let us know if you run into any other interesting clues / behaviors / workarounds, but I think you've provided enough for us to fix the issue.  Also let me know if you have a specific deadline and this is jeopardizing your engineering strategy.  Feel free to email me at asyncdisplaykit@gmail.com with general questions on ASDK, too. :)

**Comment by adly-holler** [comment] 2015-09-19 20:48
@tettoffensive Could you give that PR a try?

**Closed** 2015-09-20 09:21 UTC

**Comment by appleguy** [comment] 2015-09-20 09:25
Hmm, interesting that merging the PR automatically closed this issue (I don't recall that normally happening, even for linked issues).

@tettoffensive, let us know how your main app looks; test app is running OK by my trials, where it did reproduce before.  Thanks a lot to @adly-holler for the fix!

**Comment by tettoffensive** [comment] 2015-09-21 17:19
Hey guys, just got back from a weekend in Portland. Just tested both my test project (which was failing every time) and it worked! I tested my main project as well (which wasn't failing every time, but often enough). So far no issues.

Thanks @appleguy @adly-holler @rcancro @eanagel for the quick response!
