### ISSUE TITLE
[Layout Transitions] animateLayoutTransition in 1.9.91 vs 2.0 / master.

### ISSUE THREAD

**Issue by IvanChan** [facebook/AsyncDisplayKit#2491] opened 2016-10-27 10:04 UTC
- (void)transitionLayoutWithAnimation:(BOOL)animated
                 shouldMeasureAsync:(BOOL)shouldMeasureAsync
              measurementCompletion:(nullable void(^)())completion;

Does it available in 1.9.91 ?

I call this in my code , but the api below is not getting called.
- (void)animateLayoutTransition:(id<ASContextTransitioning>)context;

**Comment by IvanChan** [comment] 2016-10-27 12:18
I found that I write it like below, **animateLayoutTransition** won't get call

```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    if (self.state == layout1)
    {
        return [self layout1:constrainedSize];
    }
    else if (self.state == layout2)
    {
        return [self layout2:constrainedSize];
    }
    else
    {
        return [self layout3:constrainedSize];
    }
}
```

**Comment by Adlai-Holler** [comment] 2016-10-27 23:37
Hi! We'd like to help – would you be willing to post a sample project with your node that isn't receiving the `animateLayoutTransition` call?

**Comment by IvanChan** [comment] 2016-10-28 02:32
like below, is it enough?

```
- (ASLayoutSpec *)layoutSpecThatFits:(ASSizeRange)constrainedSize
{
    if (self.state == StateMini)
    {
        return [self miniLayoutSpecThatFits:constrainedSize];
    }
    else if (self.state == StateDetail)
    {
        return [self detailLayoutSpecThatFits:constrainedSize];
    }
    else
    {
        return [self defaultLayoutSpecThatFits:constrainedSize];
    }
}

- (ASLayoutSpec *)defaultLayoutSpecThatFits:(ASSizeRange)constrainedSize
{
    self.avatarNode.preferredFrameSize = CGSizeMake(60, 60);
    self.backButtonNode.preferredFrameSize = CGSizeMake(40, 32);
    self.moreButtonNode.preferredFrameSize = CGSizeMake(100, 26);
    
    ASLayoutSpec *spacer = [[ASLayoutSpec alloc] init];
    spacer.flexGrow      = YES;
    
    ASCenterLayoutSpec *moreButtonCenterSpec = [ASCenterLayoutSpec centerLayoutSpecWithCenteringOptions:ASCenterLayoutSpecCenteringX
                                                                                          sizingOptions:ASCenterLayoutSpecSizingOptionMinimumXY
                                                                                                  child:self.moreButtonNode];
    
    ASCenterLayoutSpec *avatarCenterSpec = [ASCenterLayoutSpec centerLayoutSpecWithCenteringOptions:ASCenterLayoutSpecCenteringX
                                                                                      sizingOptions:ASCenterLayoutSpecSizingOptionMinimumXY
                                                                                              child:self.avatarNode];
    
    ASStackLayoutSpec *headSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                                                          spacing:0
                                                                   justifyContent:ASStackLayoutJustifyContentCenter
                                                                       alignItems:ASStackLayoutAlignItemsStart
                                                                         children:@[self.backButtonNode, spacer, self.followButtonNode]];
    headSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    headSpec.flexGrow = YES;
    
    ASOverlayLayoutSpec *overlaySpec = [ASOverlayLayoutSpec overlayLayoutSpecWithChild:avatarCenterSpec
                                                                               overlay:headSpec];
    overlaySpec.alignSelf = ASStackLayoutAlignSelfStretch;
    overlaySpec.flexGrow = YES;
    
    overlaySpec.spacingAfter = 15;
    self.nameNode.spacingAfter = 13;
    self.introNode.spacingAfter = 0;
    ASStackLayoutSpec *contentTextSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                 spacing:0
                                                                          justifyContent:ASStackLayoutJustifyContentCenter
                                                                              alignItems:ASStackLayoutAlignItemsCenter
                                                                                children:@[overlaySpec, self.nameNode, self.introNode, moreButtonCenterSpec]];
    contentTextSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    contentTextSpec.flexGrow = YES;
    
    ASInsetLayoutSpec *insetSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(35, 10, 0, 10)
                                                                          child:contentTextSpec];
    insetSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    insetSpec.flexGrow = YES;
    
    return insetSpec;
}

- (ASLayoutSpec *)detailLayoutSpecThatFits:(ASSizeRange)constrainedSize
{
    self.avatarNode.preferredFrameSize = CGSizeMake(24, 24);
    self.backButtonNode.preferredFrameSize = CGSizeMake(40, 32);
    self.moreButtonNode.preferredFrameSize = CGSizeMake(100, 26);
    
    ASLayoutSpec *spacer = [[ASLayoutSpec alloc] init];
    spacer.flexGrow      = YES;
    
    ASStackLayoutSpec *headSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                                                          spacing:8
                                                                   justifyContent:ASStackLayoutJustifyContentCenter
                                                                       alignItems:ASStackLayoutAlignItemsCenter
                                                                         children:@[self.backButtonNode, spacer, self.avatarNode, self.nameNode, spacer, self.followButtonNode]];
    headSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    headSpec.flexGrow = YES;
    
    self.addrNode.spacingAfter = 0;
    ASStackLayoutSpec *contentTextSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionVertical
                                                                                 spacing:16
                                                                          justifyContent:ASStackLayoutJustifyContentCenter
                                                                              alignItems:ASStackLayoutAlignItemsCenter
                                                                                children:@[headSpec, self.telNode, self.addrNode, self.moreButtonNode]];
    contentTextSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    contentTextSpec.flexGrow = YES;
    
    ASInsetLayoutSpec *insetSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(35, 10, 26, 10)
                                                                          child:contentTextSpec];
    insetSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    insetSpec.flexGrow = YES;
    
    return insetSpec;
}

- (ASLayoutSpec *)miniLayoutSpecThatFits:(ASSizeRange)constrainedSize
{
    self.avatarNode.preferredFrameSize = CGSizeMake(60, 60);
    self.backButtonNode.preferredFrameSize = CGSizeMake(40, 32);
    
    ASLayoutSpec *spacer = [[ASLayoutSpec alloc] init];
    spacer.flexGrow      = YES;
    
    ASCenterLayoutSpec *avatarCenterSpec = [ASCenterLayoutSpec centerLayoutSpecWithCenteringOptions:ASCenterLayoutSpecCenteringX
                                                                                      sizingOptions:ASCenterLayoutSpecSizingOptionMinimumXY
                                                                                              child:self.avatarNode];
    
    ASStackLayoutSpec *headSpec = [ASStackLayoutSpec stackLayoutSpecWithDirection:ASStackLayoutDirectionHorizontal
                                                                          spacing:0
                                                                   justifyContent:ASStackLayoutJustifyContentCenter
                                                                       alignItems:ASStackLayoutAlignItemsCenter
                                                                         children:@[self.backButtonNode, spacer, self.followButtonNode]];
    headSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    headSpec.flexGrow = YES;
    
    ASInsetLayoutSpec *insetSpec = [ASInsetLayoutSpec insetLayoutSpecWithInsets:UIEdgeInsetsMake(35, 10, 15, 10)
                                                                          child:headSpec];
    insetSpec.alignSelf = ASStackLayoutAlignSelfStretch;
    insetSpec.flexGrow = YES;
    
    return insetSpec;
}

- (void)animateLayoutTransition:(id<ASContextTransitioning>)context
{
    [UIView animateWithDuration:0.4
                     animations:^{
                         
                         self.introNode.alpha = (self.state == WMHomeHeaderStateDetail) ? 0 : 1;
                         self.telNode.alpha = (self.state == WMHomeHeaderStateDetail) ? 1 : 0;
                         self.addrNode.alpha = (self.state == WMHomeHeaderStateDetail) ? 1 : 0;
                         
                     } completion:^(BOOL finished) {
                         [context completeTransition:finished];
                     }];
}
```

**Comment by IvanChan** [comment] 2016-10-28 02:33
I debug a little bit, reason is **_transitionID != transitionID**

but why?

```
- (BOOL)_shouldAbortTransitionWithID:(int32_t)transitionID
{
  ASDN::MutexLocker l(__instanceLock__);
  return (!_transitionInProgress || _transitionID != transitionID);
}
```

**Comment by appleguy** [comment] 2016-10-31 22:47
@IvanChan Thanks for asking!  The answer is that this API was very new (and I believe is in a Beta header) in 1.9.91, and there are major changes to the implementation in master / 2.0.

Could you try using master (or our current stable branch, releases/p6.14) and see if you have any issues with this API?  Its implementation was completely rewritten due to issues similar to what you're describing, and I believe it should be resolved.

Our friends at Buffer are building their app straight off of master, just as Pinterest does.  So, in general it is more stable and full featured, and I'd suggest you jump onto it if you're interested!  (https://overflow.buffer.com/2016/10/04/implementing-asyncdisplaykit-within-buffer-ios/)

Also, please feel welcome to join our Slack room and ping any of our maintainers (such as htroisi) in the rooms there.  http://asyncdisplaykit.org/slack.html

**Comment by IvanChan** [comment] 2016-11-02 06:18
in 2.0 support interactive animation?

 just like UIViewControllerInteractiveTransitioning

**Comment by maicki** [comment] 2016-11-08 17:00
@IvanChan Hey, unfortunately 2.0 will not support interactive animations, but it's on our radar for 2.0+.  

In terms of the other problem you ran into, could you provide a sample project that would help us hugely to reproduce the issue and look into it a bit deeper.

**Comment by garrettmoon** [comment] 2016-11-14 21:40
Hey @IvanChan I'm going to close this for now, if you don't mind putting up a sample project we can re-open.

**Closed by garrettmoon** 2016-11-14 21:40 UTC
Labels: Close if no Reply, community debugging, discussion, Layout
