### ISSUE TITLE
[ASNetworkImageNode] Issue with NOT animated GIF

### ISSUE THREAD

**Issue by gonzo-oin** [facebook/AsyncDisplayKit#1763] opened 2016-06-17 14:36 UTC
I'm using an ASTableView and I've encountered some issues with **not animated** gif images. 
For example, if the node with a not animated gif is displayed at first position, it will not show it until I "re-display" the node in the ASTableView by scrolling down and up.   

Does anyone have this issue ?

**Comment by hannahmbanana** [comment] 2016-06-17 17:01
@gonzo-oin: Thanks for reporting this! 

Would you be willing to create a sample project for me? Command + D on the project folder and strip out anything not important. I'll be able to help out much more quickly this way.

**Comment by hannahmbanana** [comment] 2016-06-23 03:32
@gonzo-oin: Was this issue 100% reproducible?

**Comment by hannahmbanana** [comment] 2016-08-03 07:16
@gonzo-oin: Due to the length of time since this thread has been active, I'm going to close this. Feel free to reopen it and I can help debug this for you.

**Closed by hannahmbanana** 2016-08-03 07:16 UTC
Labels: close if no reply, community debugging
