### ISSUE TITLE
ASTableView crashes with assertion "Node should always be marked invisible before deallocating" depending on header height.

### ISSUE THREAD

**Issue by mikhailmulyar** [facebook/AsyncDisplayKit#2203] opened 2016-09-06 21:58 UTC
Hi. I have simple ASTableNode showing sectioned list. There is a really strange behaviour. App stops with assertion "Node should always be marked invisible before deallocating" in a second after table content shows when reallocing my custom ASCellNode. There is nothing happening at the moment, no updates or reloads.
Most strange thing is that crash depends on tableView header height. If i return 15 in tableView(tableView: UITableView, viewForHeaderInSection section: Int) app runs ok. If i return 18 it crashes. So i guess it is something related to how cells positioned in the view.
Here is the screen at crash state. There is searchBar - 44 height, headers are 18, and cell nodes are 41.
I'm using latest master version.
![simulator screen shot 07 sep 2016 00 55 34](https://cloud.githubusercontent.com/assets/2234720/18292442/340d30de-749e-11e6-9215-30219a418a4a.png)

**Comment by hannahmbanana** [comment] 2016-09-07 18:38
@mikhailmulyar: Thanks for reporting this! This issue looks similar to #2205, which @Adlai-Holler is planning on investigating soon.

**Comment by Adlai-Holler** [comment] 2016-09-14 05:49
Hi @mikhailmulyar I'm investigating this for you. I've got a couple quick questions:

- Are any of your nodes set with `shouldRasterizeDescendants=YES`? Any of them `layerBacked=YES`?
- How are your section headers working? Are you implementing `viewForHeaderInSection` and returning `cellNode.view`?
- Which node is hitting the assertion failure? A node for a row, a node for a section, or one of the subnodes?

I know those assertion failures can be extremely irritating so I'll do my best to get this fixed the right way!

**Comment by mikhailmulyar** [comment] 2016-09-14 07:37
Hi @Adlai-Holler. 
1) I've used shouldRasterizeDescendants in ASCellNode. However when i received bug, i'm pretty sure i've tried to turn it off, and it did not change anything
2) Yes. I'm returning cellNode.view and storing them in array. However it does not matter, since i've completely commented viewForHeaderInSection and only returned height in heightForHeaderInSection. The screenshot is made in that state, as you can see headers are empty, there is nothing at all.
3) Custom subclass of ASCellNode for row.

**Comment by Adlai-Holler** [comment] 2016-11-18 01:26
@mikhailmulyar Hi! We've been super busy preparing for the 2.0 launch but this is still an important issue for us. 

Curious if there has been any change in behavior from the framework, or have you found a workaround that unblocks you on this issue?

**Comment by mikhailmulyar** [comment] 2016-11-18 21:24
Hi @Adlai-Holler. At the moment this issue is not happens with exactly same style. But i have not tested it with exactly same nodes and headers count. I have now a bit different count of elements in sections.
However it still happens in another case. So i have pretty same screen with same height of elements, but with different amount of elements in section. I have 14 elements in total, and 2 last of them out of screen(not visible). Element 13 is like 15-20 pixels away from edge of the screen. When i enter text in search bar, it displays found elements and currently simply does reloadData() when data source updated. So here are the steps to reproduce after table initially loaded
1) Input anything in search for table to reload.
2) Delete search text, so table will reload again and show all elements
3) Input text again, after table reloads again all nodes deallocs and assertion happens for node 13.

If before step 3) ill scroll down to make element visible and then scroll back up, and search, assertion does not happen. Node correctly marked was invisible.
So it seems at reload some of close to edge, but not visible nodes somehow marked as visible, but do not marked back as invisible after that

**Comment by mikhailmulyar** [comment] 2016-11-18 21:36
I've checked when didEnterVisibleState called for this node. It has zero frame in that moment.
<MessengerApp.ContactNode: 0x7fe820e306a0; frame = (0 0; 0 0); interfaceState = { MeasureLayout | Preload | Display | Visible }>

**Comment by garrettmoon** [comment] 2016-12-12 18:25
@Adlai-Holler can you investigate to see if this needs further work? Punt out of 2.0.1 if necessary.

**Comment by Adlai-Holler** [comment] 2016-12-14 19:14
@mikhailmulyar Could you try the latest version of ASDK? I believe this issue was resolved in #2731

**Comment by ryanfitz** [comment] 2016-12-15 14:36
I upgraded to 2.0 and am now running into this issue on an `ASTableNode`. In my case, reloadData is called when users take a specific action. It crashes probably at least 25% of the time when reloadData is called.

**Comment by Adlai-Holler** [comment] 2016-12-19 15:11
Hi folks, just a heads up that over at #2436 we've got a test case that reproduces this issue and hopefully we'all get it fixed soon! It's one of our highest priorities given how frustrating and elusive it is.

**Comment by garrettmoon** [comment] 2016-12-19 19:01
Looks like we're closer to fixing this but it won't make it for 2.0.1, moving to 2.0.2

**Comment by Adlai-Holler** [comment] 2016-12-19 22:40
@ryanfitz @mikhailmulyar Could you guys give `master` a try post-2805? The issue should reliably be resolved!

**Comment by ryanfitz** [comment] 2016-12-20 12:56
@Adlai-Holler I tried latest master and have had mixed results. On iPhone its worked perfect and I have not been able to recreate this issue. However, on iPad it crashes immediately on first attempt at reloading data.

**Comment by ryanfitz** [comment] 2016-12-21 01:10
To update this, I tried the recent 2.0.1 branch and this crash is happening on both iPhone & iPad

**Comment by Adlai-Holler** [comment] 2017-01-03 23:02
Closing this and moving all discussion over to #2711

**Closed by Adlai-Holler** 2017-01-03 23:02 UTC
Labels: Bug, P2
