### ISSUE TITLE
Guidance on how to use ASViewControllers in UITabBarController  

### ISSUE THREAD

**Issue by nelson-pinto** [facebook/AsyncDisplayKit#1551] opened 2016-04-19 02:11 UTC
Hi,

I've using AsyncDisplayKit for a while. It's really a awesome framework. Thank you all for that.
I'm having trouble using ASViewControllers as UITabBarController root view controllers. Everything works fine, if i don't put the App in background. If i navigate inside all the tabs, the ASViewControllers nodes are correctly resized and after that, the App doesn't crash. But, if i leave one of the tabs unvisited, the corresponding ASViewController ASDisplayNode ins't measured and the App crashes when i send it to background. I tried to solve it by myself, but i'm struggling.
I'm having this error:
```
Assertion failure in ASSizeRange ASSizeRangeMake(CGSize, CGSize)(), .../Pods/AsyncDisplayKit/AsyncDisplayKit/Layout/ASDimension.mm:71
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Range max width must be infinite or a real positive integer.'
```

Any ideas on how i can fix this?
Thanks in advance.

**Comment by appleguy** [comment] 2016-04-19 03:50
@nelson-pinto thanks for the report! This is a bit of a surprising issue, as we use a Taber controller in this fashion with Pinterest, but I can definitely make sure it is fixed quickly.

I do need additional information from you. Can you please provide the full backtrace for the exception? You may need to add an exception breakpoint. If you're able to reproduce this issue in a small test project, perhaps by creating a diff against any one of the examples/ directory apps, that would be really great.

It would be awesome if you want to join the community discussions going on in Slack, where we could help out with this problem in a more live manner. Feel free to send me an email and I can give you an invite!  asyncdisplaykit@gmail.com

**Comment by nelson-pinto** [comment] 2016-04-19 23:24
@appleguy thank you very much for the feedback. No exception is thrown. The program stops on this last assert:

```
ASSizeRange ASSizeRangeMake(CGSize min, CGSize max)
{
  ASDisplayNodeCAssertPositiveReal(@"Range min width", min.width);
  ASDisplayNodeCAssertPositiveReal(@"Range min height", min.height);
  ASDisplayNodeCAssertInfOrPositiveReal(@"Range max width", max.width);
```
After some digging, if found out that this delegate ( and the other belonging to the same protocol)

`- (ASCellNode *)collectionView:(ASCollectionView *)collectionView nodeForItemAtIndexPath:(NSIndexPath *)indexPath;`

gets called when i send my app to background. This all happens on an unvisited tab bar ASViewController ASDisplayNode. The ASCollectionView is added as a ASDisplayNode subnode.
Is this the expected behavior?
I was setting the ASCollectionView delegates on ASDisplayNode init method. Meanwhile, I moved this initialization to `- (void)didLoad`.

Thank you once again.

Great! I'll send you an email to get access to discussions on Slack.

**Comment by appleguy** [comment] 2016-04-22 05:23
Very interesting.  I can think of a possible cause here -- memory saving code that runs at suspend may be triggering a layout on something that isn't positioned yet and cause some kind of invalid layout.

This would be quick to test and fix if we could get a small example project demonstrating it.  If you have an hour to put one together - perhaps just do a Command-D to duplicate any project in examples/ and then completely change it - that would be fantastic!

If you can't, more details such as the full back trace (copying the LLDB output for "bt all") would be helpful.

**Comment by hannahmbanana** [comment] 2016-05-11 08:17
@nelson-pinto: Were you able to figure this issue out? If not, I'd be happy to help debug.

**Comment by appleguy** [comment] 2016-06-06 06:30
@nelson-pinto: Were we able to help you out on Slack? I can't remember if I saw this discussion on #general or not. Let me know if you still need help and I'd be happy to take a look.

**Comment by appleguy** [comment] 2016-06-18 03:18
@nelson-pinto: Given the length of time that has passed since this thread was active, I'm going to close this issue. If you are able to provide us a sample project, we'd be happy to help you debug this!

**Closed by appleguy** 2016-06-18 03:18 UTC
Labels: close if no reply, community debugging, discussion

**Comment by appleguy** [comment] 2016-06-20 01:01
@nelson-pinto Note that ASTabBarController is now available!
