### ISSUE TITLE
[ASCollectionNode] Move Items Animation

### ISSUE THREAD

**Issue by leotumwattana** [facebook/AsyncDisplayKit#2845] opened 2016-12-30 05:14 UTC
We've been rebuilding parts of our app as a feasibility test for using ASDK. So far ASDK has been awesome and we've resolved most of the issues except for one thing. The `moveItem:` animation for ASCollectionNode.

I've done a little reading through past issues (most notable #698) and noticed that right now, `moveItem:` is done as a `delete + insert`. However, in our app, the `moveItem:` animation is actually quite critical to help inform our users to changes. A simple fade-out-fade-in animation provides a lot less visual cue to the eyes. 

I understand #698 is marked for 2.1. Anxiously waiting to see this enhancement so we can start using ASDK in our app. Thanks very much in advance!

**Comment by garrettmoon** [comment] 2017-01-03 18:55
@leotumwattana it sounds like this is a duplicate of #698 so I'm going to close this.

**Closed** 2017-01-03 18:57 UTC

**Comment by garrettmoon** [comment] 2017-01-03 19:00
@leotumwattana sorry if that sounded callous, we really appreciate the enthusiasm! However having one issue makes it easier to track and get stuff done :)

**Comment by leotumwattana** [comment] 2017-01-03 19:04
@garrettmoon: No worries. Let's go with #698.
