### ISSUE TITLE
Xcode warns about duplicate files in the Pods project

### ISSUE THREAD

**Issue by ide** [facebook/AsyncDisplayKit#313] opened 2015-02-14 05:25 UTC
When installing ASDK with CocoaPods 0.35, Xcode pops up a warning about the Pods projects saying something about duplicate files in ASDK. Looking at the error details it has to do with ASDealloc2MainObject and _AS-objc-internal. I believe the "ASDealloc2MainObject" subspec is including those files, and the main spec (which includes all source files) implicitly includes the subspec so the MRR files are included twice.

![screenshot 2015-02-13 23 15 42](https://cloud.githubusercontent.com/assets/379606/6198922/52c99e0c-b3d6-11e4-9641-07170ded1583.png)

**Comment by ide** [comment] 2015-02-14 07:16
![screenshot 2015-02-13 23 15 42](https://cloud.githubusercontent.com/assets/379606/6198920/4e2627ee-b3d6-11e4-8b04-545b30436eac.png)

**Comment by rnystrom** [comment] 2015-02-17 19:49
Hmm, I'm not getting this issue, but I'm using Cocoapods 0.36 beta 1. Might be something that is being fixed on the Cocoapods end?

**Comment by ide** [comment] 2015-02-17 20:05
I tested with 0.36 beta 2 and got the same issue. Repro steps:
- Make an iOS project with Xcode 6.1.1. Just a single page application is OK.
- Add a Podfile. I used:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AsyncDisplayKit', '~> 1.1'
```
- pod install (tested with 0.36.0-beta.2)
- Open the generated Xcode workspace and look at the warnings in the Issue Navigator

**Comment by ide** [comment] 2015-02-18 03:08
It might have something to do with Facebook's Xcode configuration or mine. Here is a zip file with an Xcode workspace and project file that shows the warning for me. http://www.speedyshare.com/V8jqW/Example.zip

**Comment by rnystrom** [comment] 2015-02-18 04:10
Hmm ya even that sample project doesn't show any warnings for me. I even tried another `pod install` on the project and nothing. I'll try to pass this around and see if someone else can reproduce the issue.

**Comment by macistador** [comment] 2015-02-28 23:17
I also have the same issue with Xcode 6.2, CocoaPods 0.36 beta 2 and ASDK 1.1.1 (master), can't explain why but possibily because cocoapods beta doesn't fully support framework integration yet ?

**Comment by appleguy** [comment] 2016-02-07 02:21
Hey, sorry we never got an official answer here, but I haven't noticed this issue myself. Please do reopen this task if you are seeing it with no latest version of Xcode, cocoapods, and The framework but I think it is likely that it has gone away with time :)  cc @ide @macistador

**Closed by appleguy** 2016-02-07 02:21 UTC
Labels: bug (P1)

**Comment by macistador** [comment] 2016-02-08 09:44
Ok no problemo @appleguy I will open it if I reproduce
