### ISSUE TITLE
[Build] Unit test failure in recent master: -[ASTableViewTests testRelayoutVisibleRowsWhenEditingModeIsChanged]

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#3162] opened 2017-03-10 19:24 UTC
I'm not sure, but this could be caused by some recent changes to ASTableView.

![image](https://cloud.githubusercontent.com/assets/565251/23809799/e45ac656-0583-11e7-88f6-fd5291232422.png)

**Comment by maicki** [comment] 2017-03-11 15:29
@appleguy Did you have a change to re-test that. I couldn't reproduce that within terminal, Xcode or on CI ...

**Comment by maicki** [comment] 2017-03-22 16:30
@appleguy I will close this issue for now as we cannot reproduce it. If it comes up again please reopen. Thanks!

**Closed by maicki** 2017-03-22 16:30 UTC
