### ISSUE TITLE
[Framework Target] Need to ensure the appropriate build configuration is up to date.

### ISSUE THREAD

**Issue by kielgillard** [facebook/AsyncDisplayKit#1065] opened 2016-01-15 05:37 UTC
Building AsyncDisplayKit (at revision df10f8f19a416cd367e8761783538ae1dfe460f6) as a framework into my app. I am unable to run my XCUITests on my Mac because the AsyncDisplayKit target fails to make a debug build.

Here is the errors and warnings in my build log.

```
Build target AsyncDisplayKit-iOS of project AsyncDisplayKit with configuration Debug

ProcessInfoPlistFile /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Info.plist AsyncDisplayKit-iOS/Info.plist
    cd /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-infoPlistUtility /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit-iOS/Info.plist -expandbuildsettings -format binary -platform iphonesimulator -o /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator/AsyncDisplayKit.framework/Info.plist

CompileC /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransaction.o AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang AsyncDisplayKit -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -fprofile-arcs -ftest-coverage -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -fprofile-instr-generate -fcoverage-mapping -iquote /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-generated-files.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-own-target-headers.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-all-non-framework-target-headers.hmap -ivfsoverlay /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/all-product-headers.yaml -iquote /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-project-headers.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator/include -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/DerivedSources/i386 -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/DerivedSources -F/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransaction.d --serialize-diagnostics /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransaction.dia -c /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransaction.m -o /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransaction.o

CompileC /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransactionGroup.o AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionGroup.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang AsyncDisplayKit -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -fprofile-arcs -ftest-coverage -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -fprofile-instr-generate -fcoverage-mapping -iquote /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-generated-files.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-own-target-headers.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-all-non-framework-target-headers.hmap -ivfsoverlay /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/all-product-headers.yaml -iquote /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-project-headers.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator/include -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/DerivedSources/i386 -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/DerivedSources -F/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransactionGroup.d --serialize-diagnostics /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransactionGroup.dia -c /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/Transactions/_ASAsyncTransactionGroup.m -o /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/_ASAsyncTransactionGroup.o

CompileC /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/ASCollectionViewFlowLayoutInspector.o AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang AsyncDisplayKit -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk -fasm-blocks -fstrict-aliasing -fprofile-arcs -ftest-coverage -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -fprofile-instr-generate -fcoverage-mapping -iquote /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-generated-files.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-own-target-headers.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-all-non-framework-target-headers.hmap -ivfsoverlay /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/all-product-headers.yaml -iquote /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/AsyncDisplayKit-project-headers.hmap -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator/include -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/DerivedSources/i386 -I/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/DerivedSources -F/Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/ASCollectionViewFlowLayoutInspector.d --serialize-diagnostics /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/ASCollectionViewFlowLayoutInspector.dia -c /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m -o /Users/kiel.gillard/Library/Developer/Xcode/DerivedData/Alfred-elqpjeogvesgbpfqlazseekvpbli/Build/Intermediates/CodeCoverage/AFR/Intermediates/AsyncDisplayKit.build/Debug-iphonesimulator/AsyncDisplayKit-iOS.build/Objects-normal/i386/ASCollectionViewFlowLayoutInspector.o

/Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m:32:43: warning: sending 'id<ASCollectionViewDelegate> _Nullable' to parameter of incompatible type 'id<ASCollectionDelegate>'
    [self didChangeCollectionViewDelegate:collectionView.asyncDelegate];
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m:11:
/Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.h:45:67: note: passing argument to parameter 'delegate' here
- (void)didChangeCollectionViewDelegate:(id<ASCollectionDelegate>)delegate;
                                                                  ^
/Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m:44:59: error: no known instance method for selector 'respondsToSelector:'
    _delegateImplementsReferenceSizeForHeader = [delegate respondsToSelector:@selector(collectionView:layout:referenceSizeForHeaderInSection:)];
                                                          ^~~~~~~~~~~~~~~~~~
/Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m:44:47: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
    _delegateImplementsReferenceSizeForHeader = [delegate respondsToSelector:@selector(collectionView:layout:referenceSizeForHeaderInSection:)];
                                              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m:45:59: error: no known instance method for selector 'respondsToSelector:'
    _delegateImplementsReferenceSizeForFooter = [delegate respondsToSelector:@selector(collectionView:layout:referenceSizeForFooterInSection:)];
                                                          ^~~~~~~~~~~~~~~~~~
/Users/kiel.gillard/work/undoiterationone/Libraries/AsyncDisplayKit/AsyncDisplayKit/Details/ASCollectionViewFlowLayoutInspector.m:45:47: warning: incompatible pointer to integer conversion assigning to 'BOOL' (aka 'signed char') from 'id' [-Wint-conversion]
    _delegateImplementsReferenceSizeForFooter = [delegate respondsToSelector:@selector(collectionView:layout:referenceSizeForFooterInSection:)];
                                              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 2 errors generated.
```

**Comment by appleguy** [comment] 2016-01-19 04:21
@kielgillard thank you for reporting this.  I think this might be caused by https://github.com/facebook/AsyncDisplayKit/issues/1062

@Adlai-Holler, does that sound right to you?  Sorry for the short reply, I'm on a tight timeline for the next ~36 hours, but should be able to work on this on Wednesday afternoon!

@nguyenhuy, since you're one of the few Swift gurus at Pinterest, maybe you could take a look at this tomorrow?

**Comment by Adlai-Holler** [comment] 2016-01-19 06:23
I'm not 100% on this, got a lot on my plate here too, but I don't think this is related to #1062 . If anything, I suspect this is related to how `ASCollectionViewDelegate` is actually a `#define` in the current version since we don't want dos support it. Swift only imports `#defines` very selectively and I've had issues with this particular one in the past.

The compiler for me (for build+run schemes) considered it an undefined symbol which isn't quite the same as a protocol with `no known instance method for selector #blah` but perhaps related. Maybe doing a global replace for `ASCollectionViewDelegate` to `ASCollectionDelegate` would help the compiler see the light.

**Comment by maicki** [comment] 2016-07-14 14:17
@kielgillard Is this sill an issue? Please close if not or let us know what the current status is. Thanks!

**Comment by garrettmoon** [comment] 2016-11-14 21:18
Closing this for now, please re-open if it's still an issue!

**Closed by garrettmoon** 2016-11-14 21:18 UTC
Labels: Operations, Swift
