### ISSUE TITLE
[ASDisplayNode] Lock entanglement can occur due to -didEnterVisibleState activity.

### ISSUE THREAD

**Issue by appleguy** [facebook/AsyncDisplayKit#2605] opened 2016-11-14 07:10 UTC
This looks likely to be caused by the new locking around the ASLayoutElementStyle property.  It's important to note that the previous layout properties did not have locks, as entanglement issues similar to this were observed.

We need to investigate this for 2.0 to assess how common it is and whether it can be worked around.  Moving to more atomic scalar values for the layout configuration would help, and we may be able to find an alternate synchronization option for style — e.g. perhaps disallow writing the property itself externally for 2.0, since this use case is currently rare.

https://fabric.io/pinterest6/ios/apps/pinterest/issues/57dbb2df0aeb16625b51df2c/sessions/ecd258e4b7d74712884ee3d6fa794631_9c4482a0a27d4b29972e29526f069c01_0_v1?

@maicki would know this area well - however, he is sprinting on some awesome changes in the layout engine currently.  @nguyenhuy, do you have cycles to investigate this in the next week?  A first look, even without a fix, could be a valuable next step.

**Comment by appleguy** [comment] 2016-11-14 07:14
# URL: https://fabric.io/pinterest6/ios/apps/pinterest/issues/57dbb2df0aeb16625b51df2c/sessions/ecd258e4b7d74712884ee3d6fa794631_9c4482a0a27d4b29972e29526f069c01_0_v1?
# Version: 6.14.1 (0)
# Issue #: 117632
# Date: 2017-01-14T19:28:52Z
# OS Version: 9.3.5 (13G36)
# Device: iPad Mini
# RAM Free: 7.8%
# Disk Free: 3.1%

Fatal Exception: Deadlock Detected on Thread 0
...
12 libobjc.A.dylib                0x2188eeeb objc_exception_throw + 250
13 Pinterest                      0x13c675 -[PIDeadlockDetector detectorThread] (PIDeadlockDetector.m:21)
14 libsystem_platform.dylib       0x21e2206f _sigtramp + 34
15 libsystem_pthread.dylib        0x21e29877 _pthread_mutex_lock_wait + 74
16 libsystem_pthread.dylib        0x21e299ff _pthread_mutex_lock_slow + 230
17 Pinterest                      0x64935d ASDN::Mutex::lock() (ASThread.h:183)
18 Pinterest                      0x8244ed -[ASDisplayNode supernode] (ASDisplayNode.mm:2177)
19 Pinterest                      0x65529f -[ASDisplayNode(PIContextLoggingAdditions) nextContextProvider] (ASDisplayNode+PIContextLoggingAdditions.m:47)
20 Pinterest                      0xce7c9 +[PIContextLogger contextForContextProvider:] (PIContextLogger.m:22)
21 Pinterest                      0xcea0d +[PIContextLogger logEvent:contextProvider:builderBlock:] (PIContextLogger.m:57)
22 Pinterest                      0x65534d -[ASDisplayNode(PIContextLoggingAdditions) contextLoggingVisibilityDidChange:] (ASDisplayNode+PIContextLoggingAdditions.m:66)
23 Pinterest                      0x3e2565 -[PIControlNode didEnterVisibleState] (PIControlNode.m:17)
24 Pinterest                      0x325215 -[PIPulserNode didEnterVisibleState] (PIPulserNode.m:103)
25 Pinterest                      0x82674b -[ASDisplayNode setInterfaceState:] (ASDisplayNode.mm:2868)
26 Pinterest                      0x826af1 __37-[ASDisplayNode enterInterfaceState:]_block_invoke (ASDisplayNode.mm:2882)
27 Pinterest                      0x82c729 ASDisplayNodePerformBlockOnEveryNode (ASDisplayNodeExtras.mm:51)
28 Pinterest                      0x826a5f -[ASDisplayNode enterInterfaceState:] (ASDisplayNode.mm:2881)
29 Pinterest                      0x826e71 -[ASDisplayNode setHierarchyState:] (ASDisplayNode.mm:2944)
30 Pinterest                      0x826ff5 __37-[ASDisplayNode enterHierarchyState:]_block_invoke (ASDisplayNode.mm:2977)
31 Pinterest                      0x82c729 ASDisplayNodePerformBlockOnEveryNode (ASDisplayNodeExtras.mm:51)
32 Pinterest                      0x826f65 -[ASDisplayNode enterHierarchyState:] (ASDisplayNode.mm:2976)
33 Pinterest                      0x824655 -[ASDisplayNode __setSupernode:] (ASDisplayNode.mm:2220)
34 Pinterest                      0x821f2b -[ASDisplayNode _addSubnode:] (ASDisplayNode.mm:1691)
35 Pinterest                      0x821dbd -[ASDisplayNode addSubnode:] (ASDisplayNode.mm:1660)
36 Pinterest                      0x56af13 -[PIPinCloseupNode showEducationPulser:atAnchorPoint:] (PIPinCloseupNode.m:377)
37 Pinterest                      0x68e9bb -[PIPinCloseupGalleryViewController showPulser:atAnchorPoint:completion:] (PIPinCloseupGalleryViewController.m:865)
38 Pinterest                      0x195a71 -[PIEducationTooltipManager showPulsersWithData:] (PIEducationTooltipManager.m:158)
39 Pinterest                      0x1953dd __77-[PIEducationTooltipManager showTooltipsForExperience:onPlacement:completed:]_block_invoke (PIEducationTooltipManager.m:77)
40 Pinterest                      0x1952b1 -[PIEducationTooltipManager showTooltipsForExperience:onPlacement:completed:] (CBLDefines.h:759)
41 Pinterest                      0x75fc75 -[PIExperiencePlacementController showTooltipsForExperience:completed:] (PIExperiencePlacementController.m:227)
42 Pinterest                      0x75f6c9 -[PIExperiencePlacementController showExperience:completion:] (PIExperiencePlacementController.m:160)
43 Pinterest                      0x75f62b -[PIExperiencePlacementController showPrefetchedExperienceWithCompletion:] (PIExperiencePlacementController.m:147)
44 Pinterest                      0x75ffad -[PIExperiencePlacementController handlePlacedExperience:completion:] (PIExperiencePlacementController.m:284)
45 Pinterest                      0x75fe47 -[PIExperiencePlacementController validateAndHandleExperience:completion:] (PIExperiencePlacementController.m:253)
46 Pinterest                      0x75f433 __67-[PIExperiencePlacementController refreshExperienceWithCompletion:]_block_invoke (PIExperiencePlacementController.m:104)
47 Pinterest                      0x47b74b __89-[PIExperienceAPIController experienceForPlacementId:withContext:withSuccess:andFailure:]_block_invoke (PIExperienceAPIController.m:303)
48 Pinterest                      0x109fad __134-[CBLPinterestClient requestMethod:path:parameters:queuePriority:constructingBodyWithBlock:operationConstructedBlock:success:failure:]_block_invoke_2 (CBLPinterestClient.m:524)
49 libdispatch.dylib              0x21c61823 _dispatch_call_block_and_release + 10
...
58 Pinterest                      0xd2e33 main (main.m:47)
59 libdispatch.dylib              0x21cab873 (Missing)

#12. com.apple.root.default-qos
0  libsystem_kernel.dylib         0x21d7ea08 __psynch_mutexwait + 24
1  libsystem_pthread.dylib        0x21e29877 _pthread_mutex_lock_wait + 74
2  libsystem_pthread.dylib        0x21e299ff _pthread_mutex_lock_slow + 230
3  Pinterest                      0x64935d ASDN::Mutex::lock() (ASThread.h:183)
4  Pinterest                      0x81ceab -[ASDisplayNode style] (ASDisplayNode.mm:732)
5  Pinterest                      0x86378f computeStackDimensionSum(std::__1::vector<ASStackUnpositionedItem, std::__1::allocator<ASStackUnpositionedItem> > const&, ASStackLayoutSpecStyle const&) (ASStackUnpositionedLayout.mm:259)
6  Pinterest                      0x862e5f ASStackUnpositionedLayout::compute(std::__1::vector<id<ASLayoutElement> __strong, std::__1::allocator<id<ASLayoutElement> > > const&, ASStackLayoutSpecStyle const&, ASSizeRange const&) (ASStackUnpositionedLayout.mm:308)
7  Pinterest                      0x861a2b -[ASStackLayoutSpec calculateLayoutThatFits:] (ASStackLayoutSpec.mm:136)
8  Pinterest                      0x8419cf -[ASLayoutSpec calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] (ASLayoutSpec.mm:100)
9  Pinterest                      0x8417f1 -[ASLayoutSpec layoutThatFits:parentSize:] (ASLayoutSpec.mm:92)
10 Pinterest                      0x8416bf -[ASLayoutSpec layoutThatFits:] (ASLayoutSpec.mm:87)
11 Pinterest                      0x825717 -[ASDisplayNode calculateLayoutThatFits:] (ASDisplayNode.mm:2466)
12 Pinterest                      0x8254bf -[ASDisplayNode calculateLayoutThatFits:restrictedToSize:relativeToParentSize:] (ASDisplayNode.mm:2420)
13 Pinterest                      0x81dc2b __97-[ASDisplayNode transitionLayoutWithSizeRange:animated:shouldMeasureAsync:measurementCompletion:]_block_invoke_2 (ASDisplayNode.mm:881)
14 libdispatch.dylib              0x21c61823 _dispatch_call_block_and_release + 10

#15. com.pinterest.closeupPinUpdateOperationQueue
0  libsystem_kernel.dylib         0x21d7ea08 __psynch_mutexwait + 24
1  libsystem_pthread.dylib        0x21e29877 _pthread_mutex_lock_wait + 74
2  libsystem_pthread.dylib        0x21e299ff _pthread_mutex_lock_slow + 230
3  Pinterest                      0x64935d ASDN::Mutex::lock() (ASThread.h:183)
4  Pinterest                      0x81e245 -[ASDisplayNode cancelLayoutTransition] (ASDisplayNode.mm:953)
5  Pinterest                      0x42a871 -[PIPinCloseupMetadataNode setNodes:] (PIPinCloseupMetadataNode.m:128)
6  Pinterest                      0x42b349 -[PIPinCloseupMetadataNode buildSubnodesForRelayoutForPin:withOldPin:nodeStates:] (PIPinCloseupMetadataNode.m:244)
7  Pinterest                      0x42af49 -[PIPinCloseupMetadataNode buildSubnodesForRelayoutForPin:withOldPin:] (PIPinCloseupMetadataNode.m:196)
8  Pinterest                      0x42ac6f __42-[PIPinCloseupMetadataNode updateWithPin:]_block_invoke (PIPinCloseupMetadataNode.m:167)
9  libdispatch.dylib              0x21c61823 _dispatch_call_block_and_release + 10

**Comment by appleguy** [comment] 2016-11-14 07:18
Remember objects should never ascend the node tree while holding their own __instanceLock__, not sure if that's the issue here — but it is ascending the tree, so that's a risk.

**Comment by nguyenhuy** [comment] 2016-11-15 18:14
I'm working on this issue, feel free to assign it to me. I think I figured out the root cause, working on a fix and maybe a unit test.

**Comment by garrettmoon** [comment] 2016-12-01 21:08
Sadly I think this needs to be punted to 2.0.1

**Closed** 2016-12-19 20:11 UTC
Labels: ASDisplayNode, Huy, P2
