### ISSUE TITLE
Resizing node contained in a UICollectionViewCell

### ISSUE THREAD

**Issue by cecilcosta** [facebook/AsyncDisplayKit#2374] opened 2016-10-13 16:55 UTC
I'm playing a video (ASVideoPlayerNode) inside a UICollectionViewCell (can't change it) and when I rotate the device I do a trick for moving the node from the old cell to the new one. It works believe or not, but there is an issue that the framesize doesn't respect the new orientation, basically the video keeps playing with the original size. Is there a way for resizing in real time videos that are being played?

**Comment by hannahmbanana** [comment] 2016-10-15 23:31
@cecilcosta: Although there are ways to make this work, it is dependent on how you've structured your code. The issue is that since your `ASVideoPlayerNode` is not within a node container (ASCollectionNode, ASTableNode, etc), nothing will trigger it to relayout. The API layout API has changed recently, so I'm not sure what the new way to do this is. 

We highly recommend that you switch to using a `ASCollectionNode` with `ASCellNode`s. This should be easy to do because ASCollectionNode's API is similar to UICollectionView.

**Comment by garrettmoon** [comment] 2016-11-14 21:48
Going to close this for now, if there's more info, reply back and we'll re-open.

**Closed by garrettmoon** 2016-11-14 21:48 UTC
Labels: community debugging
