### ISSUE TITLE
[ASTableView] Reloading table in background throws an exception.

### ISSUE THREAD

**Issue by tuyuan2012** [facebook/AsyncDisplayKit#891] opened 2015-11-29 00:55 UTC
When I in a view reload an ASTableView which is in an another view by notification, the tableView may crash sometimes. I use the reload method to reload the tableView. 
The follow is the crash log:
 -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
(null)
(
	0   CoreFoundation                      0x000000018544c2f4  + 160
	1   libobjc.A.dylib                     0x0000000196c780e4 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018532f85c  + 0
	3   66xue                               0x1005d77fc __ASIndexPathsForMultidimensionalArrayAtIndexSet_block_invoke + 60
	4   Foundation                          0x0000000186313200  + 1072
	5   66xue                               0x1005d76d8 ASIndexPathsForMultidimensionalArrayAtIndexSet + 304
	6   66xue                               0x100582ddc __56-[ASDataController deleteSections:withAnimationOptions:]_block_invoke_2 + 128
	7   Foundation                          0x00000001863331c4  + 16
	8   Foundation                          0x0000000186284604  + 96
	9   Foundation                          0x00000001862741cc  + 636
	10  Foundation                          0x0000000186335f28  + 228
	11  libdispatch.dylib                   0x00000001972c9954  + 16
	12  libdispatch.dylib                   0x00000001972d40a4  + 1448
	13  libdispatch.dylib                   0x00000001972cca5c  + 132
	14  libdispatch.dylib                   0x00000001972d6318  + 720
	15  libdispatch.dylib                   0x00000001972d7c4c  + 108
	16  libsystem_pthread.dylib             0x00000001974a922c _pthread_wqthread + 816
	17  libsystem_pthread.dylib             0x00000001974a8ef0 start_wqthread + 4
)

dSYM UUID: CF67341D-85EF-3F84-BFCA-12337B9C941B
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: 66xue
Base Address: 0x000000010000c000

**Comment by appleguy** [comment] 2015-11-29 01:20
@tuyuan2012 Thanks for the report.  This stack looks like a common issue that has been fixed in master.  Questions for you:

- What version of ASDK are you using?  Is it 1.9.1, or an earlier version?
- Is the issue reproducible?  Can you please try building your app against the master version of ASDK and re-testing?

The most common cause of this issue had been fixed in 1.9.1, but there is a final fix for a similar issue in master that isn't yet contained in any published release.  I am working on the 1.9.2 release now, which will include this.

Although you're welcome to wait a day or two for the 1.9.2 release, it would be a great help to hear confirmation from you that the issue is resolved on master.

If, for any reason, it's not resolved on master — I will make sure to coordinate an investigation with high priority to fix the problem (ideally before 1.9.2).

**Comment by tuyuan2012** [comment] 2015-11-29 02:31
Thank you very much, I will try it. The version of ASDK in our project is 1.9.1. And, the frequency of this crash is very low...I am very hopeful for the 1.9.1 version ASDK....@appleguy

**Comment by appleguy** [comment] 2015-12-04 04:03
@tuyuan2012 - Hi again - could you clear any local copy of the framework and install 1.9.2, then try again?  Very interested to hear the result.

If you are still seeing the issue, it would be tremendously helpful to get a test project that reproduces it.  If you're comfortable sending me the app code directly, I've done this with some people and will handle it with the strictest of confidentiality.

I am tagging this issue for 1.9.3 just in case it is not fixed.  1.9.3 is targeted for release this coming Sunday night.  If we don't have a project that can reproduce the issue, I can't guarantee we will be able to fix it for that release, however.  Even still, I won't close the issue until we have a resolution for you.

**Comment by appleguy** [comment] 2015-12-06 00:39
@tuyuan2012 ping - let me know when you have a chance!

**Comment by appleguy** [comment] 2015-12-06 00:40
@tuyuan2012 please reopen this task (or if you prefer, file a new one) if you experience the issue again.  I really want to hear from you if the problem (or a different one) occurs, so don't hesitate to do this - EVEN if you are not confident whether it is the app-layer code or the ASDK framework that has a bug, I want to make sure the issue is solved either way.

**Closed by appleguy** 2015-12-06 00:40 UTC
Labels: community debugging, fix landed
