### ISSUE TITLE
How to use -shouldRasterizeDescendants?

### ISSUE THREAD

**Issue by joostvandijk** [facebook/AsyncDisplayKit#471] opened 2015-05-31 10:02 UTC
I'm trying to use -shouldRasterizeDescendants, but I keep ending up with an empty node. What properties should I set on my subnodes to get them to correctly rasterize?

This is my current node hierarchy. None of the subnodes change after creation. Text is also immediately set on the textnodes.

```
<<ASDisplayNode> isLayerBacked:1 shouldRasterizeDescendants:1 backgroundColor:white>
 | <<ASDisplayNode> isLayerBacked:1>
 |  | <<ASTextNode> isLayerBacked:1>
 | <<ASDisplayNode> isLayerBacked:1>
 |  | <<ASTextNode> isLayerBacked:1>
 | <<ASDisplayNode> isLayerBacked:1>
 |  | <<ASTextNode> isLayerBacked:1>
```

When I disable rasterization, the node looks like this (as expected):
![ios simulator screen shot 31 mei 2015 12 10 18](https://cloud.githubusercontent.com/assets/8394738/7901543/1ee54f44-078e-11e5-871b-5b207dbbc19a.png)

Any help would be much appreciated. Thanks!

**Comment by appleguy** [comment] 2015-06-07 02:52
@joostvandijk Thanks for the report — I'm going to test rasterization now with the latest version of ASDK to make sure it is working correctly.  If so, we can start looking more closely at your code or node setup for any issues.  My hope is that once we find the issue, we can make the API more clear or provide explicit alerts / warnings if an important element is left out of the setup.

**Comment by appleguy** [comment] 2015-06-07 03:37
I was able to reproduce a similar issue, so I doubt it is your configuration.  I'm not sure how this may have failed, but am hoping the fix is straightforward.  With the knowledge that it's likely a framework issue, feel free to dive in, but I'll try to debug as soon as I get a chance.  WWDC week ahead means it might take a little while, though!

**Comment by appleguy** [comment] 2015-06-07 03:43
Fortunately was able to figure out what is most likely going on.  Background colors take on a particular significance with rasterization, and I believe it is interpreting [UIColor clearColor] as black for an opaque context.  You should be able to work around this by setting [UIColor whiteColor] on a few nodes in your hierarchy.

This behavior is unacceptably non-intuitive, so there is an important follow-up to improve either the behavior or documentation / developer-facing warnings.  Thanks again for your report and I hope to hear if the workaround is successful :)

**Comment by joostvandijk** [comment] 2015-06-07 07:36
@appleguy Thanks for the reply! Setting the background color to white works. However, I did run into #318. My rasterized node has a vertical offset, which somehow creates an inset in the rasterized node. I'll dive into it to see if I can find the cause.
![schermafbeelding 2015-06-07 om 09 30 33](https://cloud.githubusercontent.com/assets/8394738/8023036/e2376ef0-0cf7-11e5-8c51-66a886017eb9.png)

**Comment by appleguy** [comment] 2015-06-10 22:06
@joostvandijk very interesting — I bet you anything there is some relatively recently refactored code where a copypasta error resulted in a rectangle's x / y values being misused (e.g. y origin used for x as well, or such)

I am going to roll a 1.2.1 within a few days, and it would be fantastic to include this fix if you're able to find one soon.  My goal is to also include some improved default behavior for this, by either properly handling transparent backgrounds or defaulting to white for clearColor backgrounds.

**Comment by joostvandijk** [comment] 2015-06-13 18:24
@appleguy The following piece of code seems to be the cause. (ASDisplayNode+AsyncDisplay.mm)

It uses the node's bounds, position and anchorPoint to calculate the frame for the node to draw into during rasterization. This makes sense for the the subnodes, but it's also being applied to the rasterization container node.
```objective-c
- (void)_recursivelyRasterizeSelfAndSublayersWithIsCancelledBlock:(asdisplaynode_iscancelled_block_t)isCancelledBlock displayBlocks:(NSMutableArray *)displayBlocks {

[...]

// Capture these outside the display block so they are retained.
UIColor *backgroundColor = self.backgroundColor;
CGRect bounds = self.bounds;
CGPoint position = self.position;
CGPoint anchorPoint = self.anchorPoint;

// Pretty hacky since full 3D transforms aren't actually supported, but attempt to compute the transformed frame of this node so that we can composite it into approximately the right spot.
CGAffineTransform transform = CATransform3DGetAffineTransform(self.transform);
CGSize scaledBoundsSize = CGSizeApplyAffineTransform(bounds.size, transform);
CGPoint origin = CGPointMake(position.x - scaledBoundsSize.width * anchorPoint.x,
                               position.y - scaledBoundsSize.height * anchorPoint.y);
CGRect frame = CGRectMake(origin.x, origin.y, bounds.size.width, bounds.size.height);

[...]

}
```

If I check whether or not the node being drawn is the container node, and then simply use a frame with a zero origin, it works as expected.

```objective-c
CGRect frame;
if (self.__rasterizedContainerNode) {
// Pretty hacky since full 3D transforms aren't actually supported, but attempt to compute the transformed frame of this node so that we can composite it into approximately the right spot.
  CGAffineTransform transform = CATransform3DGetAffineTransform(self.transform);
  CGSize scaledBoundsSize = CGSizeApplyAffineTransform(bounds.size, transform);
  CGPoint origin = CGPointMake(position.x - scaledBoundsSize.width * anchorPoint.x,
                               position.y - scaledBoundsSize.height * anchorPoint.y);
  frame = CGRectMake(origin.x, origin.y, bounds.size.width, bounds.size.height);
} else {
  frame = CGRectMake(0.0f, 0.0f, bounds.size.width, bounds.size.height);
}
```


![ios simulator screen shot 13 jun 2015 20 16 41](https://cloud.githubusercontent.com/assets/8394738/8145470/2cfcaa48-1209-11e5-8ec5-6384d5c6eefd.png)

**Comment by appleguy** [comment] 2015-06-13 18:44
Thanks so much, @joostvandijk !  As you might expect by reading the code (since it is incorrect), this was one of the areas modified for open sourcing.  The container concept was added, and the transform logic was updated to be more generalized (rather than just enough for what Paper needed).  This is an important advanced feature of AsyncDisplayKit and I'm very grateful you took the time to debug it.

**Comment by joostvandijk** [comment] 2015-06-13 19:16
@appleguy No problem. 👊 I've submitted a pull request containing a cleaned up version of the fix seen above.

**Comment by appleguy** [comment] 2015-06-14 00:36
Love it, this is now fixed :) https://github.com/facebook/AsyncDisplayKit/pull/479

**Closed by appleguy** 2015-06-14 00:36 UTC
