### ISSUE TITLE
[Wrapping Views] `initWithViewBlock:` node works initially, then fails to display

### ISSUE THREAD

**Issue by molon** [facebook/AsyncDisplayKit#853] opened 2015-11-17 04:26 UTC
At first , sorry for my poor engilish.

I know we can use `ASTextNode` to draw text and it will provides more smooth performance.

But we need to use custom third-party lib in same cases. (we dont have much time to subclass `ASDisplayNode` for it)
Follow the docs, we can `addSubview` in `didLoad`, it's fine.
But I dont know how to use `layoutSpecThatFits:` with custom subview. maybe I can set a layout placeholder?

So I must find another way.
I test `initWithViewBlock:` method to create node for custom subview(UILabel for test, maybe another view actually):
```
//In a `ASCellNode`
_customNode = [[ASDisplayNode alloc]initWithViewBlock:^UIView *{
            UILabel *label = [[UILabel alloc]init];
            label.backgroundColor = [UIColor colorWithWhite:0.692 alpha:1.000];
            label.text = @"Hello World!";
            return label;
        }];
        _customNode.preferredFrameSize = CGSizeMake(100, 50);
        [self addSubnode:_customNode];
```
Then layout with `_customNode`.
The ASTableView's row number is 30.

First I scroll down,every would be ok. But  when I scroll back,the backgroundcolor and text in UILabel would be lost.(`Capture View Hierarchy` tells me the label is exist with preferredFrameSize)

I dont know why. So expect help.

Or How create a layout placeholder in `layoutSpecThatFits`?

**Comment by appleguy** [comment] 2015-11-19 21:21
@molon great question!  You found the right approach; if you want to use ASLayoutSpec with a traditional UIView, wrapping it with an ASDisplayNode is the best option.

I don't see any bugs with the code you just provided, so unfortunately the issue is a bit mysterious to me.  A few questions:

1) Can you try out using master?  There is an issue that is now fixed in master which affected rare cases when inserting rows and then scrolling down, and could cause content to disappear.  I doubt this is your problem, just want to make sure.
2) Could you provide a screenshot of the first display when it's apparently working correctly, and then a screenshot of when you have scrolled back and the content is incorrect?
3) You are not using any special features such as .isLayerBacked or .shouldRasterizeDescendants, right?
4) Understanding that this is not a solution - but still an important question - what features does ASTextNode lack that lead you to require the third-party library?
5) Lastly, if you are able to provide a test project — for example, a diff that can be applied to an existing sample app such as Kittens or SocialAppLayout — that can implement something similar and reproduce the issue, that would surely be the fastest way for me to understand and solve the issue with you.

Thanks for asking!

**Comment by molon** [comment] 2015-11-20 04:30
@appleguy 
I have provide a test project https://github.com/molon/ASDKIssue853 base on `SocialAppLayout`.
The source I added is in `PostNode.m` and sign with `#warning`

This is the screenshot gif below:
![image](https://raw.githubusercontent.com/molon/ASDKIssue853/master/screenshot.gif)

3. I havn't use any special features.
4. The UILabel is just for test to description the issue. Maybe I will use a third-party image view who can display animated gif or others in the future. After all, wrap traditional views is a necessary skill.

:)

**Comment by molon** [comment] 2015-11-26 13:29
@appleguy 
I find the problem location.
![image](https://cloud.githubusercontent.com/assets/3739161/11424006/6bf90f7c-9484-11e5-9c6b-6c208ebd24dc.png)

I have try to add below:
```
if ([_layer isKindOfClass:[_ASDisplayLayer class]]) {
        _layer.contents = nil;
    }
```
in the `- (void)clearContents`.

Then the UILable display ok. 

But I doubt that it's a not good fix.

**Comment by appleguy** [comment] 2016-01-26 05:33
@molon could you please test this in 1.9.6?  I really, really appreciate the detailed task and video, test project, etc.  It helped me fix this - it took longer than I would hope, but the good thing is that the fix is very comprehensive, a fully rewritten ASRangeController that is dramatically better!!  Reopen this task if you still see an issue.

**Closed by appleguy** 2016-01-26 05:33 UTC
Labels: community debugging

**Comment by WildDylan** [comment] 2016-06-16 10:46
i meet this....  what can i do ~

**Comment by appleguy** [comment] 2016-06-17 07:22
Could you all let me know what purpose you have for wrapping a synchronous element?  Have you tried using ASTextNode?  Wrapping UILabels like this avoids some of the greatest performance benefits of the framework, including async layout, async rendering, layer-backing, and rasterization...

It should definitely work, and I believe the cause is that you are trying to use rasterization or a related feature with a synchronous node (init with view block).  However, the question of why using this rare (should be less than 5% of developers that need this method) functionality is the most important, then we can analyze the circumstance and fix.

**Comment by molon** [comment] 2016-06-17 15:40
@appleguy it's just a test for `initWithViewBlock`, not only for `UILabel`. 
A example: ( `init` of `ASLazyLoadCellNode`)
```
- (instancetype)init
{
    self = [super init];
    if (self) {
        _textNode = [ASTextNode new];
        [self addSubnode:_textNode];
        
        __weak __typeof(self)weakSelf = self;
        _indicatorNode = [[ASDisplayNode alloc]initWithViewBlock:^UIView *{
            __strong __typeof(self)sSelf = weakSelf;
            sSelf->_indicator = [[UIActivityIndicatorView alloc]initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
            return sSelf->_indicator;
        }];
        _indicatorNode.backgroundColor = [UIColor clearColor];
        _indicatorNode.opaque = NO;
        [self addSubnode:_indicatorNode];
        
        self.status = ASLazyLoadCellNodeStatusInit;
    }
    return self;
}
```
I want to use `UIActivityIndicatorView`, so I must care about `initWithViewBlock` method.

Maybe the method is not used usually, but it is really needed sometimes.

It's really a bug which should be fixed. isn' it?
I think my solution is well, so I will send a PR to the project?
Please review it. :)

I love the project..

**Comment by appleguy** [comment] 2016-06-17 16:08
Thanks for the description! This is certainly a valid use of the API, and yes of course it should work.

In fact, several core objects like the table node and editable text node use this functionality. These elements work in a wide variety of situations without any known regressions, so I suspect there is something such as rasterization causing the issue here. Feel free to send a pull request, and we will continue looking at this in the next few days.

**Comment by hannahmbanana** [comment] 2016-06-18 03:46
@molon @WildDylan: Thanks for reporting this strange behavior! @maicki got to the bottom of this issue today and he has a plan for resolving it. Watch for an update from him.

**Comment by maicki** [comment] 2016-06-19 20:35
Looked into the internals of UIImageView a bit. I would recommend to not fix it this way universally. UIImageView is specifically optimized for performance and does not use the usual way to provide the content for the CALayer that backs the UIImageView.

Furthermore we cannot trigger a recreation of the contents of the UIImageView layer as if it get’s cleared and we call `setNeedsDisplay` on it it goes trough the normal flow to assign the contents to a layer via the `CALayerDelegate` methods. Unfortunately `UIImageView` does not do it, it actually does not implement some of the methods at all, so nothing will show up. It’s getting better, by calling `setNeedsDisplay` on an `UIImageView` layer it actually clears the contents and nothing is visible anymore. So we have to be careful to not calling that too.

Unfortunately I didn’t find a way yet to trigger a recreation of the `UIImageView` layers content except calling the private `_updateState` method.

That said it’s different for layers of other UIKit components like UILabel for example. Clearing the contents of a UILabel layer and calling `setNeedsDisplay` on the layer usually recreates the contents of the it and it will show up again.

So my recommendation is to not universally prevent to clear the contents of a layer and instead only *NOT* clear the content if the node wraps a UIImageView otherwise we should clear the contents of the layer to reclaim memory as usual.

I will put up a PR pretty soon that should fix that.

**Comment by molon** [comment] 2016-06-20 03:21
@maicki thanks for your detailed answer very very much.
And Can I invite you to solve another issue please.
https://github.com/facebook/AsyncDisplayKit/issues/864
I have my own solution, but I doubt my solution is not comprehensive like this issue.
:)
