### ISSUE TITLE
[Apple Bug] iOS system regression in thread safety - must avoid decoding the same image on two threads

### ISSUE THREAD

**Issue by ankorko** [facebook/AsyncDisplayKit#1068] opened 2016-01-15 17:09 UTC
I am facing a bug which I have a really hard time reproducing. I am using version 1.9.5 on an iPad 2. Sometimes when adding an ASTableView as a subview, cells will either not load at all or only parts of them will load. After that no rendering ever occurs. As you can see in the attached images there are many threads blocked on `    dispatch_semaphore_wait(__ASDisplayLayerConcurrentDisplaySemaphore, DISPATCH_TIME_FOREVER);
`

I have tried to reproduce this state by making the `ASCellNode`s really heavy (50 image subnodes), but still the occurrence of the freezing was random. The freezing never occurs later than (what seems to me to be) the very first rendering.

Any ideas on what the cause may be or at least how I can provide you with more info or a way to reproduce this?

<img width="647" alt="screen shot 2016-01-15 at 19 01 06" src="https://cloud.githubusercontent.com/assets/4014301/12359497/5c05d8f8-bbbb-11e5-81eb-e03098765804.png">
<img width="645" alt="screen shot 2016-01-15 at 19 00 22" src="https://cloud.githubusercontent.com/assets/4014301/12359498/5c0c523c-bbbb-11e5-8919-333caef86e28.png">

**Comment by appleguy** [comment] 2016-01-15 20:40
@ankorko I should be able to fix this with you.  Something is pretty wrong here :).

Are you using SDWebImage, by chance?

Can you email me at asyncdisplaykit@gmail.com, and give me a contact to reach you via iMessage so we can debug?

**Comment by appleguy** [comment] 2016-01-17 00:16
@ankorko Looking forward to a test app that thrashes the system by decoding the same asset in a lot of different image nodes.  It should be relatively easy to create.  Then we can develop and test a workaround for this Apple bug, and I can subsequently submit a Radar to them (and escalate it through channels at work).

**Comment by ankorko** [comment] 2016-01-17 17:37
@appleguy Tried to modify the Kittens example to load 4-50 image nodes per ASCellNode with the same  image assets I use (should it only occur with specific image types). No luck reproducing so far. Next step is to remove static assets loading from my project (or load UIImages that get reused a lot once in a singleton class) to verify that this is the cause. I will then try again to provide a sample project by simplifying mine. Maybe it's more complex than we initially thought.

**Comment by appleguy** [comment] 2016-01-23 21:24
[bt_all_result.txt](https://github.com/facebook/AsyncDisplayKit/files/102040/bt_all_result.txt)

**Comment by appleguy** [comment] 2016-01-23 21:24
[time-profiler.trace.zip](https://github.com/facebook/AsyncDisplayKit/files/102041/time-profiler.trace.zip)

**Comment by appleguy** [comment] 2016-01-23 21:25
I'm implementing a workaround for this that should allow clients to not worry about this issue at the API / product layer, including removal of .displaysAsynchronously = NO setters.

**Comment by appleguy** [comment] 2016-01-24 01:19
A stable workaround has been landed that should not have a measurably negative performance impact on any plausible use case I can imagine.  Going to leave this open for a little while to see how testing goes.

**Comment by ankorko** [comment] 2016-01-25 12:08
Great! I will keep you up to date if I encounter the freeze again, or if it never occurs during the week.

**Comment by appleguy** [comment] 2016-01-26 03:21
Will close this until that time - we will reopen the moment it's seen again, hopefully never...

**Closed by appleguy** 2016-01-26 03:21 UTC
Labels: discussion, fix landed

**Comment by ankorko** [comment] 2016-01-26 14:12
@appleguy, unfortunately, I managed to get the same bug on 1.9.6

[bt_all_1.9.6.txt](https://github.com/facebook/AsyncDisplayKit/files/104996/bt_all_1.9.6.txt)
[Instruments_1.9.6.trace.zip](https://github.com/facebook/AsyncDisplayKit/files/105002/Instruments_1.9.6.trace.zip)

**Comment by zaaroth** [comment] 2016-01-31 20:09
I might have a piece of information about this one. Not sure it is entirely related, though.

I was facing the very same issue until I disabled rasterization on the parent node. Perhaps this can be of any help.

BTW, I have async display turned on.

**Comment by zaaroth** [comment] 2016-02-08 01:29
I am still seeing this. Why is it closed?

**Comment by lappp9** [comment] 2016-07-26 21:08
@appleguy I seem to be seeing this issue fairly often, even with .displaysAsynchronously = NO on the image nodes.  I get it on the exception breakpoint, and can usually continue, but sometimes it seems to actually crash.

**Comment by lappp9** [comment] 2016-07-26 21:12
Also, it looks like our app is using SDWebImage.  Is the solution to that problem to just stop?

**Comment by SergeyPetrachkov** [comment] 2019-08-06 18:27
Hi guys, it seems to have re-appeared in iOS 13 beta with Xcode 13 beta5

**Comment by appleguy** [comment] 2019-08-07 04:12
@SergeyPetrachkov Please feel free to open a bug on texturegroup.org ! (this repository is archived)

Would definitely be helpful if you can share any iOS 13 stack traces or other details that are motivating your observation that it is an iOS 13 regression. We'd certainly appreciate that!
