### ISSUE TITLE
Crash on deleteRowsAtIndexPaths:withRowAnimation:

### ISSUE THREAD

**Issue by kanvuduc** [facebook/AsyncDisplayKit#1055] opened 2016-01-11 07:41 UTC
I got exception when trying to delete a row. It sounds similar to #484.

I use latest release, ADK 1.9.4.

*CODE*
```Objective-C
[_tableView beginUpdates];
[_lstItems removeObjectAtIndex:index.row];
[_tableView deleteRowsAtIndexPaths:[NSArray arrayWithObject:index]
                          withRowAnimation:UITableViewRowAnimationLeft];
[_tableView endUpdates];
```

*CONSOLE LOG*
```
2016-01-11 14:36:25.811 Handhome[2945:72549] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSArray objectsAtIndexes:]: index 8 in index set beyond bounds [0 .. 7]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001041d1e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000103948deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104113ad8 -[NSArray objectsAtIndexes:] + 952
	3   Handhome                            0x0000000101e22680 __ASFindElementsInMultidimensionalArrayAtIndexPaths_block_invoke + 128
	4   Handhome                            0x0000000101e216bd _ZL52ASRecursivelyUpdateMultidimensionalArrayAtIndexPathsP14NSMutableArrayPK7NSArrayRmP11NSIndexPathmU13block_pointerFvS0_P10NSIndexSetmE + 1533
	5   Handhome                            0x0000000101e2130a _ZL52ASRecursivelyUpdateMultidimensionalArrayAtIndexPathsP14NSMutableArrayPK7NSArrayRmP11NSIndexPathmU13block_pointerFvS0_P10NSIndexSetmE + 586
	6   Handhome                            0x0000000101e22243 ASFindElementsInMultidimensionalArrayAtIndexPaths + 675
	7   Handhome                            0x0000000101dc0d31 -[ASDataController nodesAtIndexPaths:] + 577
	8   Handhome                            0x0000000101e57b30 -[ASTableView rangeController:nodesAtIndexPaths:] + 96
	9   Handhome                            0x0000000101e34a9b -[ASRangeController _updateVisibleNodeIndexPaths] + 1547
	10  Foundation                          0x0000000103531b89 __NSFireDelayedPerform + 402
	11  CoreFoundation                      0x0000000104131c84 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	12  CoreFoundation                      0x0000000104131831 __CFRunLoopDoTimer + 1089
	13  CoreFoundation                      0x00000001040f3241 __CFRunLoopRun + 1937
	14  CoreFoundation                      0x00000001040f2828 CFRunLoopRunSpecific + 488
	15  GraphicsServices                    0x000000010858cad2 GSEventRunModal + 161
	16  UIKit                               0x0000000104b07610 UIApplicationMain + 171
	17  Handhome                            0x0000000101d063df main + 111
	18  libdyld.dylib                       0x000000010677492d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by vitalybaev** [comment] 2016-01-11 13:03
+1

Oh, I spend more than hour to trace this problem. My app worked find, but, now it crashes with exactly this reason.

This is certainly a bug

**Comment by vitalybaev** [comment] 2016-01-11 13:13
Yes, problem appears in 1.9.4.
1.9.3 works fine

cc @appleguy

**Comment by zhivkob** [comment] 2016-01-12 11:48
Duplicate of #1028.

**Comment by appleguy** [comment] 2016-01-14 03:08
@kanvuduc @vitalybaev thanks for the report, both of you.  This was definitely a bug.  Subtle in cause, big in impact.  I am releasing a hotfix release tonight, but please built your apps against master and email me immediately if you see this or any other issue on latest master (asyncdisplaykit@gmail.com)

**Closed by appleguy** 2016-01-14 03:08 UTC
