### ISSUE TITLE
If you turn on voice over (accessibility), when attempt to create table view.

### ISSUE THREAD

**Issue by lxcid** [facebook/AsyncDisplayKit#358] opened 2015-03-06 23:05 UTC
```
2015-03-07 07:04:26.546 Sample[7073:1162802] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSProxy methodSignatureForSelector:] called!'
*** First throw call stack:
(0x184dba59c 0x19550c0e4 0x184dba4dc 0x185c7d304 0x184dbe160 0x184cc2b6c 0x18320b278 0x18320b348 0x18963df00 0x1000fb944 0x100095c34 0x1000970e4 0x1895da6f0 0x1897f1688 0x1897f3e08 0x1897f24a0 0x18d02162c 0x184d72a28 0x184d71b30 0x184d70154 0x184c9d0a4 0x1895d3aac 0x1895ceaa4 0x100097c54 0x195b7aa08)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by lxcid** [comment] 2015-03-06 23:12
This is the causing method https://github.com/facebook/AsyncDisplayKit/blob/master/AsyncDisplayKit/ASTableView.mm#L153

**Comment by lxcid** [comment] 2015-03-06 23:22
When I remove the line (and the related line above), the crash don't happen anymore. I'm not sure if this is what you intended. The problem occurs when proxy delegate target is nil.

**Comment by rnystrom** [comment] 2015-03-07 00:47
duplicate of #349

**Closed by rnystrom** 2015-03-07 00:47 UTC
Labels: duplicate
