### ISSUE TITLE
[ASNetworkImageNode] Disk image cache may be cleared too early (e.g. -clearFetchedData should release only memory)

### ISSUE THREAD

**Issue by binchensjtu** [facebook/AsyncDisplayKit#1459] opened 2016-03-30 08:48 UTC
Case: Multiple ASNetworkImageNode using the same image URL
1. In clearFetchedData stage.  clearFetchedImageFromCacheWithURL is invoke and clear memory cache for current image data.
2. Another ASNetworkImageNode with same URL shows up in displayWillStart stage. synchronousImageFromCacheWithCacheKey in PINRemoteImageManager is invoked. This Line https://github.com/pinterest/PINRemoteImage/blob/93d02586804e8c7515e6d2353a434b5f1318a38c/Pod/Classes/PINRemoteImageManager.m#L725 will clear both memory and disk cache for this image.  than the same image is downloaded again from network.

I check all the outgoing requests and found  same image is downloaded multiple times.

**Comment by appleguy** [comment] 2016-03-31 05:34
@binchensjtu thanks for reporting this issue. What is an example of an application user interface that has this kind of access pattern? It seems likely that the clear fetch data call could occur slightly before the display call for the next item, or even before the next item is in the fetch data range, so fixing this specific case does not seem likely to address the overall issue with your application reusing images regularly.

That said, I believe the disk cash is intended to keep the information even in a situation like this. Which version of the framework are you using? Note that there were several improvements to the behavior of caching with 1.9.7.1 and 2.1.2.

cc @garrettmoon

**Comment by binchensjtu** [comment] 2016-03-31 05:41
@appleguy Thanks for response. I am using 1.9.7.1 with 2.1.2. Actually I am testing large image. So I hard code all my cell nodes to use the same image URL. Normally this should not happened. You can decide if this should be improve or not. It is acceptable.

**Comment by appleguy** [comment] 2016-03-31 05:44
@binchensjtu it should definitely be the case that if you were to scroll away from the image, and then scroll back to it, it should be possible to retrieve from the disk cash as long as the size of the image fits within that cash. So, if we can verify what you have reported here, it definitely sounds like a bug if the disk cash is being cleared at the same time as the memory cache for all images.

**Comment by binchensjtu** [comment] 2016-03-31 06:01
@appleguy Ah. Yes. If many cell using the same icon. This is definitely unsuitable. You can easily reproduce by set the same url and much more cells in kitten example. The same image will be download multiple time while scroll up and down fast.

**Comment by garrettmoon** [comment] 2016-03-31 17:45
@binchensjtu 

Two things:

1. There was a bug in PINRemoteImage, which has been fixed, which would *not* store un-decoded images in the memory cache: https://github.com/pinterest/PINRemoteImage/pull/162/files
2. The line you pointed out in PINRemoteImage is meant to remove invalid items from the cache. I.e. ones that can't be instantiated as an image or animatedImage. It shouldn't be hit on a regular basis. I'd love to know repro steps if you are hitting it regularly.

**Comment by binchensjtu** [comment] 2016-04-02 11:22
@garrettmoon 
I print out the clearFetchedImageFromCacheWithURL log ```NSLog(@"clearFetchedImageFromCacheWithURL %@ ", [URL absoluteString]);``` for URL and downloaded image log in  ASPINRemoteImageDownloader ```NSLog(@"downloaded image %@ from %zd", [URL absoluteString], result.resultType);```
The below log show that the same image is suddenly change from cache(```PINRemoteImageResultTypeMemoryCache``` or ```PINRemoteImageResultTypeCache```) to network (```PINRemoteImageResultTypeDownload```) 

```
2016-04-02 19:13:50.181 Sample[28819:98391] downloaded image https://dn-meitiantest.qbox.me/pic.png from 2
2016-04-02 19:13:50.181 Sample[28819:98356] downloaded image https://dn-meitiantest.qbox.me/pic.png from 2
2016-04-02 19:13:50.675 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.674 Sample[28819:98371] downloaded image https://dn-meitiantest.qbox.me/pic.png from 1
2016-04-02 19:13:50.675 Sample[28819:98356] downloaded image https://dn-meitiantest.qbox.me/pic.png from 1
2016-04-02 19:13:50.675 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.675 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.732 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.732 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.848 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.998 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:50.998 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:51.665 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:51.666 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:51.666 Sample[28819:98324] clearFetchedImageFromCacheWithURL https://dn-meitiantest.qbox.me/pic.png 
2016-04-02 19:13:51.718 Sample[28819:98371] downloaded image https://dn-meitiantest.qbox.me/pic.png from 3
2016-04-02 19:13:51.718 Sample[28819:98386] downloaded image https://dn-meitiantest.qbox.me/pic.png from 3
```

You can reproduce this by change Kittens example.
1. Make KittenNode use one hard coded URL like ```_imageNode.URL = [NSURL URLWithString:@"https://dn-meitiantest.qbox.me/pic.png"];```
2. Increase the kMaxLitterSize much larger in ViewController. like ```static const NSInteger kMaxLitterSize = 10000; ```
3. Run this project and fast scroll down. Keep scrolling. You can check in log as above or observe in Charles proxy. You should notice that this image will be downloaded from network multiple times while scrolling.

**Comment by garrettmoon** [comment] 2016-11-15 21:40
I'll try and take a look at this one.

**Comment by garrettmoon** [comment] 2016-11-19 23:28
Hey @binchensjtu I just tried your test with the latest master (which specifies the latest PINRemoteImage beta 6) and I wasn't able to reproduce. I believe this was the bug I described above and is now fixed.

Thank you for bringing this up and please reply if you don't believe the issue to be resolved.

**Closed** 2016-11-19 23:28 UTC
Labels: Garrett, P3, Performance
