### ISSUE TITLE
Workaround UICollectionView "Deallocated while an Update is In Flight" Issue

### ISSUE THREAD

**Issue by Adlai-Holler** [facebook/AsyncDisplayKit#2612] opened 2016-11-16 01:40 UTC
There is an issue where UICollectionView does not like to be deallocated during an update animation.

See https://github.com/Citrrus/MBContactPicker/issues/66 and https://www.fabric.io/pinterest6/ios/apps/pinterest/issues/5821237c0aeb16625b99b785 

We should:
- Create a unit test that reproduces this issue:
  - Create an ASCollectionNode and add it to a visible window
  - Issue it an update with animation
  - Remove its view from the window
  - Clear the strong reference to the node (use `NS_VALID_UNTIL_END_OF_SCOPE` to get precise object lifetime)
  - Ensure that the collection view is indeed deallocated (use a weak reference and check it against nil). This is important because the test could start passing later if we leak the collection view, which we don't want.
  - Hopefully see it crash
  - If it doesn't crash, add logs in `ASCollectionView _superPerformBatchUpdates` to log when the update is submitted and when the completion is called. Then set a breakpoint in `-[ASCollectionView dealloc]` and see that the deallocation occurs after the update is submitted to super, but before the completion handler is called.

Once we have the failing test, build the fix:
- Add a temporary retain cycle for all updates – modify `_superPerformBatchUpdates` to intentionally add a strong reference to self into the completion handler.
- This should fix the failing test.

**Comment by nguyenhuy** [comment] 2016-11-16 14:34
@hannahmbanana: Please assign this ticket to me. Thank you!

**Comment by hannahmbanana** [comment] 2016-11-16 23:21
@nguyenhuy - Odd, but I am not able to assign it to you for some reason (you don't show up in the list)

**Comment by nguyenhuy** [comment] 2016-11-16 23:32
@hannahmbanana: no worries then. Maybe because I'm not in the Facebook org. I'm gonna stop asking people to assign and leave comments instead. Thanks!

**Comment by garrettmoon** [comment] 2016-12-02 01:31
Sadly this is going to have to go into 2.0.1 :(

**Comment by nguyenhuy** [comment] 2017-01-10 13:13
Given my failed attempts to reproduce this bug, and the fact that this crash occurred mainly in 6.14.1 and completely disappeared in 6.16. I suspect that it's caused by our client code. I suggest that we close this ticket, or at least deprioritise until it resurfaces.

![screen shot 2017-01-10 at 1 06 39 pm](https://cloud.githubusercontent.com/assets/587874/21807417/80e1f5fc-d736-11e6-873d-27eebead5c21.png)

**Closed** 2017-01-17 19:22 UTC
Labels: Bug, Collection Table  Pager, Huy, Needs Volunteer, P1
